### ISSUE TITLE
Deprecate diagnostics feature

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#1052]
OPA has a feature called diagnostics that allow you to configure it (via command line) such that it will record decisions it's making in-memory and serve them at /system/diagnostics.

This feature was added long ago and I suspect that it's essentially unused. Given that it overlaps heavily with the decision logging feature, I'd like to remove it.

**Comment by rahanar** [comment]
hey @tsandall,

I understand the reasoning behind deprecating the diagnostics feature however, the decision logging requires (based on documentation) a remote server in order to make use of it. I am new to the project and I am trying to write some basic rules for kubernetes admission controller in order to get familiar with the project and I would like to avoid dealing with setting up a remote server in order to debug my policies. 

Would it make sense to combine the functionalities of both features and make decision logging available via file/stdout/api?

thanks!

**Comment by tsandall** [comment]
@rahanar a stdout (or logrus) based decision logger could be useful.

We currently have HTTP server logs in OPA that emit the HTTP method, path, and body at debug level. I think a lot of folks have been using those to debug policy decisions, but the experience is not great (e.g., the messages are emitted on a single line, JSON values have to be encoded which makes the output quite noisy, there are two messages for every decision, etc.)

An alternative would be to have a stdout decision logger that emits the decisions in a prettier format that's more easily consumed by humans.

**Comment by rahanar** [comment]
I can relate with the experience you have described so far - debug logs while are useful, but are are very noisy. It is not easy to create policies (at least at the beginning) for kubernetes admission controller and it is a fair bit harder to debug them. 

I think stdout/logrus based decision logger should be available at least for debugging purposes - it would make onboarding to the project a lot easier.

Thanks!
