### ISSUE TITLE
opa cli does not run in Docker alpine container

### ISSUE THREAD

**Issue by dblackhall-tyro** [open-policy-agent/opa#1056]
I am trying to run `opa` from within an alpine docker container but am experiencing problems. I have included a very basic alpine container and script that reproduces the issue:

Dockerfile
```Dockerfile
FROM alpine:3.8

ARG OPA_VERSION=v0.10.1

RUN apk add --no-cache --update curl

# opa (https://www.openpolicyagent.org/)
RUN curl -SsL --retry 5 "https://github.com/open-policy-agent/opa/releases/download/${OPA_VERSION}/opa_linux_amd64" > /usr/local/bin/opa && \
    chmod +x /usr/local/bin/opa

ADD . /workdir

CMD /workdir/opa-test.sh
```

opa-test.sh
```shell
#!/bin/sh

/usr/local/bin/opa version
```

**Comment by migueleliasweb** [comment]
_Quick context: I'm working with Daniel on this._

Just expanding a little bit the description for this issue.

If we just run `opa` inside the container, we receive a message regarding a missing `$SHELL`.
```bash
/ # opa
sh: opa: not found
/ # echo $SHELL

```

Even if we install `bash`with `apk --update add bash`:
```bash
/ # apk --update add bash
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
(1/5) Installing ncurses-terminfo-base (6.1_p20180818-r1)
(2/5) Installing ncurses-terminfo (6.1_p20180818-r1)
(3/5) Installing ncurses-libs (6.1_p20180818-r1)
(4/5) Installing readline (7.0.003-r0)
(5/5) Installing bash (4.4.19-r1)
Executing bash-4.4.19-r1.post-install
Executing busybox-1.28.4-r1.trigger
OK: 15 MiB in 23 packages
/ # opa
sh: opa: not found
/ # bash
bash-4.4# echo $SHELL
/bin/ash
bash-4.4# opa
bash: /usr/local/bin/opa: No such file or directory
```

Our best guess is that this might be related to specific bash references/functions used by the executable. Since alpine does not supports bash (even though we installed it, it actually gives us `ash` instead of `bash`) this weird messages arise.

Changing the base image to a debian based one, indeed seems to solve the problem.

**Comment by tsandall** [comment]
I think the issue stems from the fact that OPA is built with CGO enabled so that we can dynamically load plugin libraries (e.g., to implement custom built-in functions.)

If you need to run an alpine image, you could re-build OPA with `CGO_ENABLED=0 make build`. This'll produce a binary that doesn't link to libc and should run inside an alpine container.

As a side note, we already publish lightweight OPA docker images, see https://hub.docker.com/r/openpolicyagent/opa/tags/. The images are based on the Google distroless images which are quite good IMO.

**Comment by dblackhall-tyro** [comment]
Thank you for the prompt response! As suggested, I solved this by building the opa project in an intermediate `golang:1.11-alpine` container which produced a working OPA cli.
Thanks again for your help, I am really excited about this project.
