### ISSUE TITLE
readyness check

### ISSUE THREAD

**Issue by kfox1111** [open-policy-agent/opa#1153]
There needs to be a way to probe to see if all policies specified to opa (not via http) are loaded. This will let kubernetes do seamless rolling upgrades of opa.

**Comment by tsandall** [comment]
Whether OPA is ready will depend on how the polices are loaded. There are three ways:

1. Policy/data on disk. Loaded via command line args
2. Pushed into OPA via HTTP.
3. Pulled into OPA via Bundle feature (preferred).

The current health check is sufficient for (1).

I don't think there's a good solution for (2) because OPA will not know when all of the policies are loaded. In this case, assuming pusher is a sidecar like kube-mgmt, the readiness check can be put there.

I could imagine extending the server /health check to take bundle activation into account. Let me know if you'd be interested in working on this and I can provide more info.

**Comment by kfox1111** [comment]
2. can/maybe should be a readyness check on the sidecar thats pushing.

1. might be good enough for what I need for now. I could build the policy directly into the container then kick off the rolling upgrade.

3. would be nice for those keeping policy in a bundle server.

I've got too many things cooking right now to contribute to implementing number 3 at the moment. Sorry. Ill ping you if time does free up though.
