### ISSUE TITLE
Safety check incorrect for := and with

### ISSUE THREAD

**Issue by tim-styra** [open-policy-agent/opa#1154]
# Expected Behavior
Both of the following rules should be safe.  They only differ in that one assigns `x :=` and the other assigns `x =`

```
package foo
bar {
    q := 1
    x = data.qux with input as q
}
```

```
package foo
bar {
    q := 1
    x := data.qux with input as q
}
```

# Actual Behavior
First rule is safe.  Second rule is unsafe:

`error: compile error: 1 error occurred: t.rego:2: rego_unsafe_var_error: var q is unsafe`

# Steps to Reproduce the Problem

`opa run` with either one of the above modules.

# Additional Info

**Comment by dineshppatilgmi** [comment]
@tsandall 
I am facing same issue.
The issue is coming when I try to do opa test against the gatekeeper library/podsecurity policy.
like below for flexvolume-drivers
opa test -r src.rego src_test.rego -v 

it gives error like below
src_test.rego:9: rego_unsafe_var_error: var violation is unsafe 
![image](https://user-images.githubusercontent.com/33516150/81923157-d704cc80-95fa-11ea-9b9a-8a7c231396a7.png)

please advise
