### ISSUE TITLE
Updating policy in configmaps doesn't reflect in decisions in kubernetes environment.

### ISSUE THREAD

**Issue by hasinthaindrajee** [open-policy-agent/opa#1175]
# Expected Behavior

I would like to see that policies which are updated in configmaps getting reflected in decisions.

# Actual Behavior

Policy change in the config map is not getting reflected until the opa pod is recreated.

# Steps to Reproduce the Problem

  1. Deploy OPA in a kuberenetes environment following https://www.openpolicyagent.org/docs/deployments.html
  2. Call the rest endpoint and will receive response as deny true.
  3. Even if I change policy in kubernetes configmaps to return a different decision, the decision doesn't reflect the change I did.
  4. If I restart opa pod, the new policy is getting reflected in decisions. 

# Additional Info

**Comment by tsandall** [comment]
@hasinthaindrajee OPA loads the policy from disk on startup but doesn't watch it for changes unless you explicitly tell it to with `-w/--watch`. Note, I'm not sure that filesystem watches are reliable in Kubernetes environments.

An alternative to volume mounting the policies is to use [kube-mgmt](https://github.com/open-policy-agent/kube-mgmt). This what we do in the admission control on openpolicyagent.org: https://www.openpolicyagent.org/docs/kubernetes-admission-control.html.

Closing this issue because i don't think there's anything to be done in OPA.
