### ISSUE TITLE
Add documentation in the REST API section for error 405

### ISSUE THREAD

**Issue by anadon** [open-policy-agent/opa#1181]
In https://www.openpolicyagent.org/docs/rest-api.html there is no mention of error 405, but in server/server.go it seems to exist to tell the caller the path requested is unavailable.  This is generally useful debugging information.

**Comment by repenno** [comment]
ok, there are a couple of things reported here: lack of 405 errors, missing return codes. 

I decided to go through the entire REST API manual while comparing with the code and found more discrepancies.  These are the changes I've done:

1 - Restructured the sections to read

..rest api spec
..example

as opposed to:

..part of rest api spec
..example
..part of rest api spec.

As I went through the manual this break in the spec made things confusing. If I was going to implement a client I would prefer to have the complete spec for a certain method followed by an example as opposed to the example break.

2 - Fixed missing or inconsistent return codes

There were quite a few of these.

3 - Added an overall 405 return code.

Since the sections are per *method* it does not make sense to have a 405 return code there. Therefore I added a small overall section in the beginning that explains that we return 405 for non-allowed methods.

**Comment by anadon** [comment]
Great! I just finished an initial version of a python REST wrapper. I'll
check about sending it your way once I update it in order to hammer out any
other potential discrepancies.

**Comment by anadon** [comment]
With the introduction of the compile API for partial evaluation, should "Get Policy (with Input)" be deprecated?

**Comment by repenno** [comment]
You can look at what we did sometime back here:

https://github.com/open-policy-agent/client-python

**Comment by anadon** [comment]
I took a very different, but reconcilable approach.  I'm aware of it, but over here we've been worried about that code's long term support.

**Comment by anadon** [comment]
Need to reopen this for a bit.
in https://www.openpolicyagent.org/docs/rest-api.html#partially-evaluate-a-query The first example conflicts with the first example in the section with respect to the top level key.  In testing, I am seeing a top level key of "result", but according to the possible responses table.

**Comment by anadon** [comment]
Yes, but what is really throwing me off is this:

![screenshot_2019-01-31 rest api gitbook](https://user-images.githubusercontent.com/3113477/52076342-7c0daa00-255c-11e9-8a98-f08bffe56a96.png)
