### ISSUE TITLE
Fix cmd integration tests to cleanup plugin directory

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#1185]
# Expected Behavior

Unexpected exits in any of the OPA tests should not result in generated files being left around in the working copy (or elsewhere).

# Actual Behavior

Currently, if the cmd tests are exited unexpectedly, e.g., due to the developer ctrl+c-ing out in the middle, the plugin tests leave a bunch of files on disk.

# Steps to Reproduce the Problem

  1. Run `go test -v ./cmd`  
  2. Ctrl+c after 1 second
  3. Run `git status` to see dirty files

For example:

```
(add-eval-coverage)torin:~/go/src/github.com/open-policy-agent/opa$ go test ./cmd  -v
^Csignal: interrupt
FAIL	github.com/open-policy-agent/opa/cmd	1.124s
(add-eval-coverage)[*]torin:~/go/src/github.com/open-policy-agent/opa$ git status
On branch add-eval-coverage
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	cmd/plugin_test_tempdir435644132/

```

# Additional Info

**Comment by repenno** [comment]
Analysis: The problem is that there is no signal handler to clean up directories and files created by WithTempFS or MakeTempFS. There are defer() calls here and there but that does not catch SIGKILL, SIGINT, etc

I have a fix for the tests in plugins_test.go but the issue can be easily reproduced in any tests that use WithTempFS(). There are quite a few of those. Ideally a signal handler would need to be installed as part of WithTempFS() or MakeTempFS().  Installing a signal handler on the caller of WithTempFS() is not enough because the code can a signal can be sent while directories/files are in the process of being created and would not be cleaned - I managed to reproduced this easily as well by sleeping and pressing ctrl-c:

	fmt.Println("Sleeping for 10 seconds")
	time.Sleep(10 * time.Second)
	fmt.Println("Finished sleeping")

Recommendation: We go with my proposed fix and  a point solution for plugins_test.go which include pulling up some functionality of MakeTempFS() into plugins_test.go and later code a signal handler in tempfs.go.

thanks,
