### ISSUE TITLE
Add support for scoping bundles to one or more data roots

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#1201]
# Overview

OPA currently erases all existing policy and data when activates a new bundle. This works fine if all the policy and data can aggregated in a single place, but in some cases (e.g., kube-mgmt) that's not possible.

To allow policy and data to come from multiple places, we can extend the bundles to include an optional notion of scope. The scope of a bundle will be defined as a set of roots in the data namespace that are owned by the bundle. When the bundle activates, the OPA will only erase the policy and data under those roots. Other policy and data will be left untouched. Moreover, the server can validate writes to ensure the caller is not attempting to modify a bundle-owned root (replying with HTTP Bad Request in this case.)

# Implementation

1. The bundle manifest should need to be extended to include roots. For example:

```json
{
  "revision": "sdjfh98a7r9aysdfasdf98asdf",
  "roots": ["a/b/c", "c/d"]
}
```

2. The bundle decoder should validate that roots in the manifest do not overlap/conflict (e.g., `["a/b", "a/b/c"]`) and that bundle contents are contained under roots. The default value is `[""]`. A value of `[]` would indicate that the bundle does not own any roots. Bundle validation failures must be reported in status updates.

3. The bundle plugin will need to remember the roots from the last bundle that activated and only erase those.

3. The HTTP server should validate write operations do not conflict with bundle-owned roots. This applies to v1/data PUT/PATCH/DELETE and v1/policies PUT/DELETE.

# Future work

- Extend API to allow callers to declare their own roots and specify their own revisions.

**Comment by repenno** [comment]
As per @tsandall

1) should just be https://github.com/open-policy-agent/opa/blob/master/bundle/bundle.go#L46
GitHub
open-policy-agent/opa
An open source, general-purpose policy engine. Contribute to open-policy-agent/opa development by creating an account on GitHub.

tsandall   [41 minutes ago]
Extending that struct to include a field for roots

tsandall   [39 minutes ago]
2) should just be extending the Read function in that file (line 77) to validate the roots at the end. (edited)

tsandall   [38 minutes ago]
3) would require extending https://github.com/open-policy-agent/opa/blob/master/plugins/bundle/plugin.go#L24 to keep track of the roots so that the erase could be done properly
GitHub
open-policy-agent/opa
An open source, general-purpose policy engine. Contribute to open-policy-agent/opa development by creating an account on GitHub.

tsandall   [38 minutes ago]
the erase/overwrite currently happens here: https://github.com/open-policy-agent/opa/blob/master/plugins/bundle/plugin.go#L187
GitHub
open-policy-agent/opa
An open source, general-purpose policy engine. Contribute to open-policy-agent/opa development by creating an account on GitHub.

**Comment by tsandall** [comment]
Currently working on this. Should have something available this week.
