### ISSUE TITLE
Extended Roadmap: Establish SQL isomorphism property and AST translators

### ISSUE THREAD

**Issue by anadon** [open-policy-agent/opa#1227]
Building off the ANTLR4 work, if we could prove that Rego is truly isomorphic with SQL then that opens up more general and agnostic tools.

**Comment by tsandall** [comment]
Because of built-in functions there will always be limitations.

We've kicked around a `pragma` statement in Rego so that policy authors could indicate the fragment of Rego that their policy must fit inside of. This could have other uses like requiring that policies are linear-time.

The pragmas would be backed up with static analysis that would warn authors when they exit the supported fragment.

**Comment by anadon** [comment]
So long as there is some kind of equivalency which can be established, those don't matter.  This has the interesting implications that the runtime could be backed by an SQL DB engine, which could lighten the development load and run more quickly.  But this can either be a week long project or a years long project and it is hard to tell until you've already started.

**Comment by tsandall** [comment]
We don't have plans to prove this for the time being. In the future, we may move SQL translation into OPA proper as a first-class feature.
