### ISSUE TITLE
Document how statements in a rule body are evaluated

### ISSUE THREAD

**Issue by F21** [open-policy-agent/opa#1294]
I am new to rego and do not have any experience with datalog.

I spoke to @ashutosh-narkar on slack and was somewhat surprised to learn that on line 62 of https://play.openpolicyagent.org/p/OllKtocCdQ , `group_id` is a string and line 63 will be invoked multiple times for each `group_id`.

My initial assumption was that line 62 is executed once and `group_id` will be a set containing multiple strings, which we then use elsewhere.

I think it would be immensely helpful if the documentation can include a few examples of how rule bodies are evaluated and executed by the compiler.

**Comment by tsandall** [comment]
@F21 the _How Do I Write Policies?_ page goes into detail on different concepts and constructs in the language. We've also updated the docs with a more detailed FAQ and Rego cheat sheet that'll be live soon. You can see a preview here: https://openpolicyagent.netlify.com/docs/.

I'm going to close this issue because I don't think there's any more work to do.
