### ISSUE TITLE
Support AWS signatures for bundle HTTP operations

### ISSUE THREAD

**Issue by nhw76** [open-policy-agent/opa#1340]
# Use case

It would be useful to us (and I suspect to others) to source a bundle from an AWS S3 bucket directly without an interposing web service. Managing access to the bundles using native AWS IAM is desirable, which implies a need for the bundle request to include a signed authentication header.

# Proposal

OPA could leverage the AWS Go SDK to sign requests; with this option being selected as an alternative authentication options within the service configuration. e.g.

```
services:
  - name: bundle-s3
    url: https://myawesomebundles.s3.amazonaws.com/
    credentials:
      s3_signing:
        s3_region: us-east-2
```

I have some code that implements this; would there be interest in my contributing the changes back? The AWS Go SDK is Apache V2 licensed.

**Comment by tsandall** [comment]
@nhw76 I agree that this could be generally useful for people deploying on AWS. I'm wondering if we can avoid the dependency on the AWS Go SDK.

Would you be configuring OPA with an access key/secret or relying on the SDK to fetch and refresh credentials from the EC2 metadata service?

**Comment by nhw76** [comment]
@tsandall I had been assuming a dependency on the session management in the AWS SDK to bootstrap the credential chain to include the EC2 metadata service / config file / environment variable options that are idiomatic for the SDK and handle refreshing. 

However, I do see that since I started doodling this the contributor's guide has been updated to indicate a bias against vendoring. For my particular use-case, I care principally about ECS tasks, and therefore the metadata service.

The actual V4 signing does not seem particularly complex once the credentials are available (given HMAC 256 in the library), and supporting the metadata service is probably not that hard. That said, it is a bit of wheel-reinventing, and exposes users to changes in contracts for the signing part and the metadata service. 

I don't have a very strong feeling about whether those risks are better or worse ones than the maintenance implications of vendoring the SDK.

An alternative would be to allow service plugins that would be alternatives to the default REST implementation. That would (theoretically) permit the SDK to be brought in as part of an "S3 bucket" service only for users that cared about the capability. I don't know if there are other useful cases for such generality though.

**Comment by tim-styra** [comment]
It'd be great if we could support a bunch of these kinds of integrations while at the same time (i) making them composable (e.g. AWS bundle + stdout decision logger or http bundle + stdout decision logger), (ii)  avoiding the vendoring problem, (iii) keeping binary size small.  OPA flavors (CI support for multiple repositories that vendor and specialize OPA) seem to be the best solution we have.  Any other ideas?

**Comment by nhw76** [comment]
I have some work-in-progress over [here](https://github.com/open-policy-agent/opa/compare/master...nhw76:s3signing) that implements the V4 signing for S3 as well as environment variable and metadata service credential providers without bringing in the AWS SDK dependency. I think this integrates reasonably well, although some refactoring for testability is required.

**Comment by tsandall** [comment]
@nhw76 that's excellent. @patrick-east could you take a look at the WIP implementation?

**Comment by patrick-east** [comment]
Will do

**Comment by nhw76** [comment]
On the first point: the current version of the signing algorithm (V4) is, at this point, at least seven years old, and is the only supported option in new regions since 2014. Amazon is only turning off support for V2 effective this year in the "old" regions. 

I'm not sure about the metadata service; but it seems to have had a stable API since at least 2014.

Although past performance is not indicative of future results, I'm not too worried about excessive churn.

**Comment by nhw76** [comment]
I did think about proxies; I don't particularly like the solution - as you say, you end up needing a way to enforce that only opa talks to the proxy otherwise other processes can promote into opa's privilege context. 

The simple options (like run it in the same container as the opa) are a bit anti-pattern and complicate process supervision and error handling. The other options either depend on adoption of a more complex orchestration (e.g. K8s) or an alternate authn method from the opa to the proxy.

**Comment by patrick-east** [comment]
> I'm not sure about the metadata service; but it seems to have had a stable API since at least 2014.

>Although past performance is not indicative of future results, I'm not too worried about excessive churn.

👍  That sounds good.

I tend to agree with the proxy stuff. Some solutions make it easier than others but it can be kind of a pain.

So.. I'm thinking maybe there are a few ways we could extend OPA to integrate this sort of functionality more cleanly. My primary concern with the integration right now is that its probably not sustainable for like every auth mechanism we'll eventually have deployers want to use. I think we have a lot of stuff using the plugin model for this pretty successfully so I'm leaning towards leveraging that framework here too.

Closest to what is already implemented. I would propose is adding a new class of OPA plugin for doing auth on these kind of http requests. Similar to what you're doing now where it hooks into the service config we instead just point it at some plugin by name like:

```yaml
services:
  bundle-s3:
    url: https://myawesomebundles.s3.amazonaws.com/
    credentials:
      plugin: s3_signing

s3_signing:
  s3_region: us-east-2
  etc: etc
```

The goal here to make them more re-usable since there are probably other places that having the signing might come in handy. Like, what if we wanted to also expose this signing capability to the built-in http requests? The "aws-auth" (or whatever we call it) plugin could be a one stop shop for aws auth goodies. Making it a plugin means we can keep it in-tree but also keeps the door open for other 3rd party auth plugins to do whatever they need.

The interface for these plugins could be pretty simple (on top of the base Plugin API), for example the logger one is like a single API: https://github.com/open-policy-agent/opa/blob/master/plugins/logs/plugin.go#L26-L31

Thinking out loud, we could have something with like pre and post processing hooks for http requests. Probably very much like the API you made for the `SignV4`:

```go
type HTTPAuthPlugin interface {
    NewClient() (*http.Client, error)
    Prepare(req *http.Request) error
}
```
_(totally not tied to the names, just throwing something out there)_

The idea being that the first one can give the opportunity for configuring whatever might be needed on the http.Client (transport/ssl details, cookies, redirect policies, etc). And the second is where, after the rest of the request has been filled in by the bundle rest plugin, it can prepare the request for the auth mechanism it needs with additional content, headers, encryption, whatever.

In theory we could refactor the bearer token and x509 auth mechanisms today to be plugins like this too.

Alternatively we could just make the rest plugin configurable. Looking at https://github.com/open-policy-agent/opa/blob/master/plugins/rest/rest.go just now I'm seeing that if we _did_ remove the credential stuff, and added in the auth plugin API I outlined, it wouldn't really do a whole lot... So maybe a better alternative is to just have the rest plugin configurable.

The plugin API would pretty much just be that `Do()` call: https://github.com/open-policy-agent/opa/blob/master/plugins/rest/rest.go#L241

We could potentially refactor some of the code to make parts of it more re-usable so additional rest plugins wouldn't need to duplicate so much just to do their extra auth steps.

Last up on my list of crazy ideas, and potentially more work but a cooler solution... is to make the https://github.com/open-policy-agent/opa/blob/master/download/download.go either use a different interface for getting content (currently it calls into the rest plugin with that `Do()` function and is very HTTP specific) or make the downloader itself a configurable plugin type instead of the auth or rest stuff. One reason I like that is it opens the door for someone to, for example, keep bundles in a storage backend without a REST API and provide a plugin for it.

**Comment by tsandall** [comment]
@patrick-east I'd err on the side of scoping this to the providing authentication/credentials to the REST client used by the plugins. I.e., let's avoid generalizing it to the point of an "authentication" plugin that anything with access to the manager can use.

Extending the `rest.Client` to take an "authentication plugin" like you defined seems like a good option to me. We can refactor the existing bearer token and client TLS credential options to implement that API. Moreover, the WIP implementation that @nhw76 has could be easily modified to fit.

**Comment by nhw76** [comment]
That sounds reasonable to me as well - how would you like me to proceed with my current implementation?

**Comment by patrick-east** [comment]
@nhw76 I think next steps would be to add the new simple plugin interface for the http auth plugins. I think we're all on board with that approach. If you can modify the current implementation to that it should be a pretty easy PR to get landed 😄

Let me know if you would like help with any of this, I'm happy to collaborate.

**Comment by nhw76** [comment]
Let me take a quick look at what's involved - would we want the authn plugins at the top level in the config (like your original example), or maybe push them down into their own section? i.e.

```
services:
  bundle-s3:
    url: https://myawesomebundles.s3.amazonaws.com/
    credentials:
      plugin: s3_signing

s3_signing:
  s3_region: us-east-2
  etc: etc
```

vs.

```
services:
  bundle-s3:
    url: https://myawesomebundles.s3.amazonaws.com/
    credentials:
      plugin: s3_signing

http_auth:
  s3_signing:
    s3_region: us-east-2
    etc: etc
```

**Comment by tsandall** [comment]
@nhw76 I'd lean toward your original config example.:

```
services:
  bundle-s3
    url: https://myawesomebundles.s3.amazonaws.com/
    credentials:
      aws:
        region: us-east-2
```

> It has been a little while since I've looked into AWS signing schemes. If signing is not S3 specific then I would reflect that in the configuration credential schema.

I think if we structure the configuration like this, the changes required in the `rest` package will be fairly straightforward.

**Comment by patrick-east** [comment]
The only reason I can think that splitting up the plugin config from the services is if there would be >1 service sharing the same credential config. I'm not sure if thats really a use-case we want to tackle though, or if just copying the config in a couple spots is a big deal.

I would lean towards @tsandall 's suggestion above (https://github.com/open-policy-agent/opa/issues/1340#issuecomment-488293706) It would make moving the existing credential stuff into plugins much easier without breaking changes to config or more complex config loading.

**Comment by nhw76** [comment]
I refactored the rest auth plugins out; the diff is fairly inscrutable but I think it looks fundamentally reasonable. I hope that's roughly what you guys had in mind? The coupling between the insecure TLS configuration (which is orthogonal from the auth plugins) and the construction of HTTP client means the separation is not maximally beautiful.

**Comment by patrick-east** [comment]
@nhw76 that is looking pretty good. Couple of things I would request:

* Have the auth plugins implement the `plugins.Plugin` interface, similar embedding as here: https://github.com/open-policy-agent/opa/blob/master/plugins/logs/plugin.go#L28
  * With that change we can move the config parsing/handling out of the rest plugin and just pass down the plugin specific config blob to it so it can deal with whatever handling it needs.
  * Initialization wouldn't need to be done in the create client API, the plugin factory API's should be nicer for handling it.
* Split up the different auth plugin implementations to separate files instead of all in `plugins/rest/rest_auth.go` We can keep them in the same package, although it might be nicer to move them to separate packages too. For example the AWS one could live in `plugins/rest/aws/`. The shared client code can still be shared in that rest_auth package.

Feel free to put this up as a PR at any point now, it'll be easier to add more comments/suggestions that way (and I won't be as likely to forget to check updates, so quicker feedback 😃)
