### ISSUE TITLE
Safety check seems wrong for a set comprehension inside a set document rule

### ISSUE THREAD

**Issue by jer** [open-policy-agent/opa#1376]
I apologize if I didn't use the correct words in the description. I'm fairly new to rego.

# Expected Behavior
Given the following rego: https://play.openpolicyagent.org/p/TqceNxo0iK

I would expect to be able to define the following rule:

```
node[name] = all {
  all :={ podname |
    pods[ns][podname].spec.nodeName = name
  }
}
```
Because `name` can be resolved in the set comprehension.

# Actual Behavior

I get the error `rego_unsafe_var_error: var name is unsafe` unless I add an extra line outside of the comprehension like this:

```
node[name] = all {
  nodes[name]
  all :={ podname |
    pods[ns][podname].spec.nodeName = name
  }
}
```

# Steps to Reproduce the Problem

  1. Go here https://play.openpolicyagent.org/p/TqceNxo0iK
  2. Delete line 37

Thank you!

**Comment by srenatus** [comment]
I am not entirely sure I understand what your goals are, but have a look at this playground: https://play.openpolicyagent.org/p/LsXjdO9g3I

When evaluating, its output includes
```json
    "pods_to_nodes": {
      "foopod": "node1",
      "foopod2": "node1",
      "foopod3": "node2"
    }
```
and I believe I remember you asking for some dictionary like that in slack.

If you're interested in all pods, there's no need to include the `[name]` in the `node` rule.

Hope this helps 😃

**Comment by timothyhinrichs** [comment]
Thanks Jeremiah for filing this issue!

It's useful to have a list of those cases where our safety check could
potentially be relaxed.

In this example, without the nodes[name], OPA says that the 'name' variable
is unsafe.  But as people we can inspect the rule and realize that the
'name' variable will always have a finite set of possible values.

So in theory the safety check is overly restrictive here.  Not sure
algorithmically what we should do, but it's a good example to think through.

**Comment by srenatus** [comment]
@jer It just _clicked_ and I've understood what you wanted, and why my comment wasn't really useful -- sorry for the noise 😉

**Comment by jer** [comment]
Hey no worries! Thanks for trying to help anyway :) I’m basically just
trying to group by nodename to do some rules around collections of pods and
node data

**Comment by tsandall** [comment]
On it's own the statement `pods[_][podname].spec.nodeName = name` will find all bindings for `podname` and `name` that satisfy the expression. Without something to constrain the values of `name`, the statement `{podname | pods[_][podname].spec.nodeName = name}` will generate a set containing ALL pod names (which is not what we want). What we want is to aggregate pods by node which is why `nodes[name]` is required.

Unfortunately we can't simplify the solution any further without changing the semantics of partial objects and object comprehensions or introducing another construct that implicitly maps keys to a set of values.

However! We could update the safety check error message to acknowledge that `name` is found inside the comprehension but that it must be made safe in the rule body, i.e., outside of the comprehension.

**Comment by tsandall** [comment]
I'm closing this issue because the safety check cannot be easily relaxed in this case and we haven't seen a strong need to improve the error messaging.
