### ISSUE TITLE
documentation typo: Getting started links incorrect

### ISSUE THREAD

**Issue by rficcaglia** [open-policy-agent/opa#1382]
# Expected Behavior
Links to download opa in Getting Started docs:
https://www.openpolicyagent.org/docs/v0.10.7/get-started/#prerequisites
should download OPA

# Actual Behavior
They download a 404 error page

# Steps to Reproduce the Problem

  1. Goto https://www.openpolicyagent.org/docs/v0.10.7/get-started/#prerequisites
  2. Try the links for the opa download, eg for linux x64: curl -L -o opa https://github.com/open-policy-agent/opa/releases/download/vv0.10.7/opa_linux_amd64 (note the typo vv0.10.7)
  3. look at the downloaded file, a 404 error

**Comment by Sai-Adarsh** [comment]
**`{{< latest >}}`** in [get-started.md#prerequisites](https://github.com/open-policy-agent/opa/blob/549fda49e47601e608a090c479b93c93bfe939c5/docs/content/get-started.md#prerequisites) generates the latest release during website run time. But I'm not sure which file has the **`$latest`** var that points to the latest release version per se.

**Comment by patrick-east** [comment]
@Sai-Adarsh you are correct, and that latest shortcode is being defined here: https://github.com/open-policy-agent/opa/blob/master/docs/website/layouts/shortcodes/latest.html which in is just reading the first entry on our list of tag names that the docs are showing.

The problem is that the older versions of the markdown files have `v{{< version >}}` but the latest changes make the versions be full tag names :(

We we will probably need is a little backwards compat shim to inject the right one, drop the older version we show right now, or just roll back the change I made to use the full versions and the "edge" version.
