### ISSUE TITLE
kube api server getting timed out while connect with opa service

### ISSUE THREAD

**Issue by sandeepsharmadevops** [open-policy-agent/opa#1437]
# Expected Behavior
kube-api server should be able to connect to opa service

# Actual Behavior
kube-api server is getting timed out to connect with opa service

# Steps to Reproduce the Problem

  1. deploy k8s cluster using kops
  2. deploy configure opa k8s admission control validating webhook
  3.  check kube-api server logs

# Additional Info
- i checked the firewall where all communication is allowed from master --> node and node --> master
- kube-api logs
W0516 12:09:25.729316       1 admission.go:236] Failed calling webhook, failing open validating-webhook.openpolicyagent.org: failed calling admission webhook "validating-webhook.openpolicyagent.org": Post https://opa.opa.svc:443/?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by tsandall** [comment]
@sandeepsharmadevops this sounds like an issue in the environment where OPA is deployed as opposed to an issue with OPA itself.

> i checked the firewall where all communication is allowed from master --> node and node --> master

Are you able to run `curl https://opa.opa.svc:443/?timeout=30s` from the node where the apiserver is running? What does the opa.opa.svc hostname resolve to? Is DNS and networking working for other k8s services from the master node?

I'm going to close this issue because I don't think there's much more we can provide from OPA itself. I'd recommend following up with kops or k8s people directly.

**Comment by sandeepsharmadevops** [comment]
thanks for the update here @tsandall I think the issue is with the master node as it is not able to connect any services running in other namespaces.
