### ISSUE TITLE
SEO issue with documentation versions

### ISSUE THREAD

**Issue by lucperkins** [open-policy-agent/opa#1448]
When I search for "opa rego" in Google, the second result is the [0.10.7](https://www.openpolicyagent.org/docs/v0.10.7/how-do-i-write-policies/) version of the "How Do I Write Policies?" doc. I suspect that there are many instances of the same behavior, though I have not verified.

We need to explore ways to ensure that true "latest" docs score more highly. I'm happy to take this on.

**Comment by tsandall** [comment]
I think it might be transient since we did have the v0.10.7 links for a little while. It should be fixed now. A quick incognito search returned the latest page. 

![Screenshot from 2019-05-29 08-56-30](https://user-images.githubusercontent.com/238885/58572066-d60f3b00-81ef-11e9-885d-7136a951834a.png)
