### ISSUE TITLE
OPA Status - expose as prometheus metrics

### ISSUE THREAD

**Issue by omerlh** [open-policy-agent/opa#1472]
# Expected Behavior
Bundle information that exposed via status API should be exposed also as Prometheus metrics (last bundle load time, last bundle version, etc) 

# Actual Behavior
Exposed only by implementing status API

If this makes sense, I might be able to provide a PR.

**Comment by srenatus** [comment]
Hmm I'm not too well-acquainted with prometheus, but which of [these four metric types](https://prometheus.io/docs/concepts/metric_types/) would fit here?

**Comment by omerlh** [comment]
It's not ideal, but it's common to "abuse" counters for this - a good example is the `up` metrics, which is a counter that is either 0 or 1. This requires some thinking, but I would maybe imagine metrics like the following:
```
Gauge - last_bundle_fetch_duration
Counter - last_bundle_fetch_status{status="success|failure"} 1/0
```
And maybe some other metrics, so the status API will be used for logging that enhances Prometheus metrics. I can use `last_bundle_fetch_status` for alerting, and the logging to understand what happened.

**Comment by srenatus** [comment]
Thanks for explaining this. I'm not familiar with what's common in prometheus land. Taking your word for it, I'd suppose this could be a useful addition. 😃 (But it's really not up to me to say...)

**Comment by omerlh** [comment]
I just looked yesterday on [Kube State Metrics docs](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/cronjob-metrics.md), look like it's also common to have a metric which is time :)

**Comment by tsandall** [comment]
If we add support for this, I'd like find the least "abusive" option.

A couple thoughts:

- Is there a reason to use a `counter` instead of a `gauge` for the success/failure status?
- We should fold download _and_ activation status into a single gauge. I interpreted "fetch" as "download". Might be my bias.  
- OPA currently reports status on discovery and normal bundles. The status exported to Prometheus should do the same. For simplicity, I'd say we should fold discovery and normal bundle status into a single gauge, e.g., `bundle_status{status=success|failure} 0/1`. I'd make success `0` so that we have right to use non-zero values to communicate different errors in the future. If we don't want to fold discovery and bundle status into a single gauge, we need to namespace them. This will become even more important when we support multiple bundles (#721).

**Comment by anderseknert** [comment]
From what I can tell, this was resolved by https://github.com/open-policy-agent/opa/pull/4251

Let me know if that's not the case, and I'll re-open.
