### ISSUE TITLE
Contribution of a Front-End for OPA

### ISSUE THREAD

**Issue by tlawrie** [open-policy-agent/opa#1557]
I wanted to see if there was any interest in us contributing a front end for OPA for specific purpose of CICD based policies

Whilst we started this effort in closed development, we have only completed an alpha / proof of concept and before we continue, if there is interest, we would like to develop it in the open and contribute back to OPA.

We could create both a repository for the front end and backing microservice if the community would be interested.

# Background
Me and my team at IBM built a prototype ReactJS front end for OPA that allows the user to create specific policies that can then be used as gates.

I have written about it [here on medium](https://medium.com/ibm-cloud/extending-openpolicyagent-for-cicd-gates-3a260852d626). There have also been other articles and submissions about using OPA as a CICD gate / policy engine so I feel that it is a valid use case.

**Comment by tsandall** [comment]
@tlawrie this sounds very promising. I've reached out on Slack so that we can find time to sync up over a higher bandwidth medium. The answer is most likely yes--we just need to figure out the specifics and I think a quick call would be the best way to introduce each other. Looking forward to it!

**Comment by tlawrie** [comment]
**Mission**
1. Provide a UI and services for generic policy creation 
2. Policies are made of rules which can be used for validation

**Scope**
We have currently achieved an alpha specific to CICD gating. We would like to mature this and adjust to a more generic implementation.

**Current Architecture**
Spring Boot service
MongoDB instance
React web app
OPA

**Roadmap**

- Update source code for contribution to community
- Support broader than CICD
- Determine if mongoDB dependency is required
- More rules
- Detailed responses of where the rule was not met.

**Contributors**
Tim Bula
Tyson Lawrie
Glen Hickman 
Marcus Roy

**Comment by garethr** [comment]
Hi @tlawrie. Super interested in different user interfaces to OPA. Some thoughts, based on reading the blog post.

1. It would be great to see some screenshots of the UI as it stands. I think it's worth considering whether that's coupled to the specific usecase you have in a CI pipeline, or if it's a more general purpose policy editor. I think the more general case might be useful for lots of other usages of OPA.

2. I'd be interested to see how this fits into modern CI platforms like GitHub Actions or Tekton. Do you envisage this running as an external service or something more distributed? The OPA project I maintain, [conftest](https://github.com/instrumenta/conftest) is proving popular in CI environments mainly because its point and shoot, embedding OPA as a library rather than running it as a service. I'd be happy to chat about that too.

3. On the security angle, I'd love to chat with my work hat on. I work at Snyk and have some similar ideas. Ping me on the Slack channel maybe?

**Comment by tlawrie** [comment]
Hey @garethr it would be great to work with you on it and happy that it has interest. 

We are talking with @tsandall to make it a set project and working out the use cases and your input will be useful in that discussion.

1. There are animated gifs in the [medium article](https://medium.com/ibm-cloud/extending-openpolicyagent-for-cicd-gates-3a260852d626). At the moment I don't feel there is too much that is specific to CICD other than the types of definitions we have by default.

2. Some really good questions. We are trying to figure this out at the moment. Its meant to be installable via helm chart and you can point your CI at the validation endpoint and pass through to it. However the 'how' is up for discussion as there are a few ways to achieve this.

3. Sounds good

**Comment by dgreene1** [comment]
@tlawrie is any of the source code available for people to fork or to observe how you did it?

**Comment by tlawrie** [comment]
Hey @dgreene1 all the code is available in [GitHub](https://github.com/boomerang-io?q=bosun&type=all&language=&sort=)

Also see [Docs](https://www.useboomerang.io/docs/boomerang-bosun/1.0.0/introduction/getting-started)

Its aged a fair bit, have been meaning to revitalise but haven't had the time.
