### ISSUE TITLE
goroutine safety of various OPA types

### ISSUE THREAD

**Issue by aidansteele** [open-policy-agent/opa#1602]
Hi,

Thanks for the wonderful library - it's superb.

Is `*ast.Compiler` safe to use concurrently from multiple goroutines? Specifically, I am wondering if I am able to do the following from multiple goroutines:

```go
engine := rego.New(
	rego.Query("data.mypolicy.allow"),
	rego.Compiler(s.compiler), // s.compiler is a shared instance of *ast.Compiler
	rego.Input(opaInput),
)

res, err := engine.Eval(ctx)    
```

Likewise, is it safe to concurrently use a single `rego.PreparedEvalQuery` from multiple goroutines?

**Comment by tsandall** [comment]
Yes, the compiler and prepared queries are treated as read-only after they have been created so you can safely share them across multiple goroutines.

**Comment by aidansteele** [comment]
That’s great news! Thanks for the insanely speedy response and the information.

**Comment by cretz** [comment]
Sorry to respond on such an old thread, but for those integrating the lib into their Go programs, this would be worth documenting in Godoc either at the package level or for each object/method. It took me a while to find this statement. By default, unless otherwise stated, libraries in Go are not assumed to be thread-safe unless explicitly stated as such. I can open a fresh issue for this if that's OK.

**Comment by tsandall** [comment]
@cretz sure feel free to file an issue. If you feel comfortable improving the godoc you can also just submit a PR.
