### ISSUE TITLE
API Documentation error

### ISSUE THREAD

**Issue by gwkunze** [open-policy-agent/opa#1619]
The API documentation for [PartialResult.Rego](https://godoc.org/github.com/open-policy-agent/opa/rego#PartialResult.Rego) contains the following text:

> In those cases using rego.PartialResult#Eval is likely to be more performant.

But that function does not exist.

**Comment by tsandall** [comment]
@patrick-east can you take a look and fix this? One option would be to fix the underlying issue that's eluded to in the comment. Alternatively, we could just say that PartialResult is deprecated in favor of PrepareForEval.

**Comment by patrick-east** [comment]
I'll fix this. I don't think we need to do anything, iirc this was a remnant from part-way through the revisions on the prepared query stuff. There isn't a `rego.Rego#Prepare` _or_ an `Eval` on `PartialResult. This was back before we added the `PreparedEvalQuery` and `PreparedPartialQuery`. By adding those specialized returns from the prepare functions we avoided the issue it alludes to because you can no longer access the Rego object directly on them like you could with the PartialResult.
