### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by liorlevtov** [open-policy-agent/opa#1666]
# Expected Behavior
Opa should not panic and exist 

# Actual Behavior
 panics

# Steps to Reproduce the Problem

  1. during everyday operation we saw panic in the log

# Additional Info
attached the whole stack trace that OPA
[OPA_Full_trace.txt](https://github.com/open-policy-agent/opa/files/3538205/OPA_Full_trace.txt)

**Comment by tsandall** [comment]
I think this is caused by this change: https://github.com/open-policy-agent/opa/commit/66fb55f40ee697274c636e81151db50c8c143be8#diff-304927c4591ee459ab6e909666e945d0R662. The server goroutines share an instance of the compiler. On [this line](https://github.com/open-policy-agent/opa/commit/66fb55f40ee697274c636e81151db50c8c143be8#diff-d1223116db97f693fadbd56db087b32aR287) the compiler's map could be modified concurrently. I'll review the calling code and figure out the right solution.
