### ISSUE TITLE
Search results on docs are not very useful right now

### ISSUE THREAD

**Issue by patrick-east** [open-policy-agent/opa#1736]
Searching on the website we don't get super useful results sometimes. For example, if you search for "kubernetes" you get one good result and then several links deeper into the middles of the kubernetes tutorial. We may need to do additional refactoring or tweaks to the site config to this to ignore some of the non-useful sections that can be linked to.

We also see duplicate search results for pages with trailing `/` and `latest` + hard coded version that == latest.

Filing this issue to track improving this. There is a somewhat significant re-org of the documentation in `edge` so we will see if this improves much.

After the next release (v0.14.0) we will need to revisit this.

**Comment by kenfdev** [comment]
With the new docs, I can confirm the duplicate search results is now gone (checked with "regex" in `latest` )

![image](https://user-images.githubusercontent.com/3941889/64895510-c7be2f80-d6b7-11e9-975b-532a5487034d.png)

Looks like `kubernetes`'s first hit is linked to `Operations > Deployment > Kubernetes > Kicking the tires`.

Would be much better if it show links from the `Kubernetes` section.

The biggest issue here is that the `Kubernetes` section doesn't have a dedicated (suppose) `h1` for the section. It just starts with [Overview & Architecture](https://www.openpolicyagent.org/docs/latest/kubernetes-introduction/).  That's why `deployments > Kubernetes` has a higher rank as the search result (which has `h2` specified). The tutorials have `h3`s as well hence the rank is pretty high.

These issues should be adjustable by [applying the tips from docsearch](https://community.algolia.com/docsearch/tips.html).

**Comment by patrick-east** [comment]
I opened up https://github.com/open-policy-agent/opa/issues/2244 which i think is the last step in getting the docs search to be in a really good place. Going to close this issue in favor of the more specific one.
