### ISSUE TITLE
Default masking of sensitive data in decision logs 

### ISSUE THREAD

**Issue by ashutosh-narkar** [open-policy-agent/opa#1781]
Users can mask sensitive data in the input provided to OPA from showing up in the decision logs. See [this](https://www.openpolicyagent.org/docs/latest/management/#masking-sensitive-data) for more info.

OPA can take a proactive approach and mask sensitive fields from the input based on certain keywords such as `passwords`, `secrets` etc. This would help prevent accidental leaking of sensitive data.

**Comment by tsandall** [comment]
Closing this issue because taking a proactive approach would be problematic. By design, OPA is general-purpose. Encoding domain-specific masks into OPA would violate that principle. Users and vendors that embed OPA as part of their platforms are free to include common, pre-defined masks for their use cases.

**Comment by tsandall** [comment]
Baking default decision masks into OPA is problematic because it violates one of the core design principles of project (i.e., domain-agnosticism). Moreover, shipping default decision masks could also be problematic as it gives users a false sense of safety.

I'm going to close this issue for now because there's nothing to be done within OPA itself.
