### ISSUE TITLE
decision log - print only relevant bundles revisions

### ISSUE THREAD

**Issue by brumer** [open-policy-agent/opa#1784]
OPA prints all the loaded bundle's revisions in each decision log.

In an environment with a large number of bundles, this can be confusing and have a performance impact because of the additional information.

I think it would be better if OPA will include in the decision log only the revisions of bundles that took part in the decision process.

**Comment by tsandall** [comment]
We report all revisions because policies can refer to policies/data in other bundles. We don't keep track of which bundles participated in the decision process today (and doing so would be fairly complicated.) How bundles are you loading into OPA?

**Comment by brumer** [comment]
at the moment it could be 300+,
maybe you could add the option to remove this key (or any other) from the log?

**Comment by tsandall** [comment]
Removing the revisions from the decision log would prevent you from being able to replay the decision offline (because you would not know which revision of policy/data was used during policy evaluation.) I'm surprised that you're loading that many bundles into OPA. Each bundle load requires a recompile. Can you share more details about how these bundles are structured? E.g., do you have a single bundle that contains policy and then many other bundles that hold data?

**Comment by brumer** [comment]
Each bundle represents a tenant with different data and a potentially different policy.
there are no connections between the bundles (i.e "imports")

**Comment by tsandall** [comment]
So each bundle is completely isolated and the clients querying OPA know to ask for specific decisions, e.g., the queries they execute are for `acmecorp/tenant1/allow`, `acmecorp/tenant2/allow`, etc. Is that right?

**Comment by brumer** [comment]
Yes

**Comment by tsandall** [comment]
@brumer for the time being, if you want to remove the revision IDs from your decision logs because you're not using them, I would recommend implementing a custom decision logger (and deploy your own version of OPA).

Longer term we could look at adding support loading sets of isolated bundles into OPA.

**Comment by tsandall** [comment]
Closing this for now because we can't feasibly implement this right now.
