### ISSUE TITLE
[K8s] Add metrics for nb of policies OK/NOK & nb of deployments OK/NOK

### ISSUE THREAD

**Issue by manicole** [open-policy-agent/opa#1816]
Would it be possible to expose new functional Prometheus-friendly metrics in OPA in a Kubernetes cluster ?

I'm thinking of
* number of validating / mutating policies successfully deployed
* number of validating / mutating policies deployed with error (thus not applied)
* number of K8s objects successfully deployed against validating / mutating policies
* number of K8s objects not deployed against validating / mutating policies (not conform)

As fas as I know, these currently do not exist natively and would require heavy log processing using Fluentd or equivalent to be exposed ...

**Comment by tsandall** [comment]
@manicole thanks for filing this. The functionality you're describing is similar to #1821. I think it's worth considering whether this belongs in OPA proper or some other component that can aggregate information from multiple OPAs (e.g., what happens if you have multiple OPA replicas for HA? what happens when you have OPA deployed on multiple clusters?)

**Comment by manicole** [comment]
Thanks for answering, and sorry for the delay, I was off for a few days.

I am not sure how #1821 (update in changelog) relates to my proposal ..?

I am not sure neither about the problem multiple clusters / OPA replicas could cause. How is it working currently with metrics at /metrics ? Couldn'it it work the same way ? I mean, these metrics could just appear at /metrics too and behave like, let's says for instance, request duration count metrics.

**Comment by tsandall** [comment]
oops, I linked to the wrong issue. Meant to refer to #1811.

> I am not sure neither about the problem multiple clusters / OPA replicas could cause. How is it working currently with metrics at /metrics ? Couldn'it it work the same way ? I mean, these metrics could just appear at /metrics too and behave like, let's says, request duration count metrics.

Some cases are easier to add to /metrics than others. For example, rule/policy-level counters like `# of admission reviews denied because of missing required labels` need more information from the evaluation engine than we currently return to the HTTP server.

**Comment by manicole** [comment]
Thank you.
Considering policies counts, my issue is related to [#1811](https://github.com/open-policy-agent/opa/issues/1811) : _v1/policies_ returns all the policies taken in account by OPA on the cluster, then we could query all configmaps and discriminate by _status: ok_.

Considering deployments, here are my thoughts. What the HTTP server returns is wether a deployment against existing policies is `allowed: true` or `allowed : false`, and in the latest situation the associated error message. Then wouldn't it be useful to count these `allowed` groupe by value (true / false) ? And would it be possible to count the `allowed: false` grouped by error messages ?

**Comment by tsandall** [comment]
It's difficult to do that kind of grouping inside of OPA proper since OPA does not know the meaning of the values generated by your policies. I.e., there is nothing built-in to OPA that knows about the structure of the response. I think there are a few ways this could work:

1. Implement this kind of functionality in another component that consumes [Decision Logs](https://www.openpolicyagent.org/docs/latest/management/#decision-logs).

2. Implement this kind of functionality specifically for Kubernetes in OPA Gatekeeper.

3. Experiment with doing this inside of OPA somehow. Perhaps OPA could have some special policy that tells it how to do the grouping.

**Comment by manicole** [comment]
Hm, I understand ...

1. Could be the best thing to do, although I tried somehow with Fluentd and found it was a lot of work for a small increment of knowledge ... If anyone tried it successfully, please post here ;)

2. Not familiar with OPA Gatekeeper, and not sure of which new functionnalities it brings compared to OPA. I'll investigate, thanks.

3. Seems complex, if anyone can help, please do so :)

Many thanks for your answer, let's see if anyone want to participate on this thread.

**Comment by anderseknert** [comment]
I don't think there's much actionable here in the scope of OPA core, so I'll close this. Using a project or product based on OPA is probably the way to go for those looking for opinionated options based on some specific use-case.
