### ISSUE TITLE
Missing input causes policy to return without error with Sprintf

### ISSUE THREAD

**Issue by jpreese** [open-policy-agent/opa#1857]
# Expected Behavior
The policy to fail (or have sprintf return some error)

# Actual Behavior
Policy "succeeds"

# Steps to Reproduce the Problem
An example can be found at the playground: https://play.openpolicyagent.org/p/tuPqkiyKCy
(all defaults are fine)

Due to `input.bar` missing, the policy succeeds. This caused a little bit of confusion at first. 

Removing sprintf() correctly returns the failed policy message.

**Comment by tsandall** [comment]
Deny doesn't generate a value because undefined values cascade in Rego. E.g., since `input.bar` is undefined the `sprintf(..., [input.bar])` expression is undefined. Since the `sprintf` expression is undefined, `msg` is undefined. Since `msg` is undefined, the set defined by `deny` is empty.

To get the policy to "fail" we would need some way to assign a value to `msg`. One option would be to use helper functions to select `input.bar`, falling back to a default on undefined. For example:

```
deny[msg] {
  not input.foo
  msg := sprintf("my message %s", [get(input, "bar", "<missing>")])
}

get(value, field, _) = value[field]
get(value, field, orElse) = orElse { not defined(value, field) }
defined(value, field) { _ = value[field] }
```

We've talked about the need for an another operator to handle undefined cases like this in past. Something like: `sprintf("my message %s", [input.bar | "<missing>"])` (we'd probably have to use something other than `|` because it's already overloaded for comprehensions and union). This is discussed a bit in #1617.

Having the sprintf call (or the `.` operator or a new field selection operator) error is another option but that would introduce a whole set of other issues. One problem is that errors are unrecoverable today. This means that if _any_ sprintf call in the entire policy errors, policy evaluation halts.

I'm tempted to close this issue because we have #1617 tracking addition of built-ins/operators that would help make the policy fail and there's no clear path forward involving errors.

**Comment by jpreese** [comment]
@tsandall you can feel free to close, I assumed it was a result of what you described. `input.bar` being undefined/null, which in turn, nulls out the entire line, causing `msg` to never return.

If it's already a known "gotcha" and tracked elsewhere, we don't need to pollute the issue tracker.

**Comment by murphyke** [comment]
@tsandall wrote:
> get(value, field, _) = value[field]
> get(value, field, orElse) = orElse { not defined(value, field) }
> defined(value, field) { _ = value[field] }

Cool incantation. For us Rego duffers, could you explain the relationship between the first two statements?

I take the second statement to mean "define a `get` function that returns its third argument if `value[field]` is not defined."  I would guess that the first statement is an alternative definition of `get` with a null body, meaning the return value of that function is always `value[field]`.

But what's going on with the underscore? I don't remember seeing an explanation of this sort of usage in the docs. I recall that functions with the same signature must return the same result or else there is an error. So these functions must not have the same signature. But given that, how is it determined which one to invoke?

Thanks!
