### ISSUE TITLE
bundle/data does not work in CLI

### ISSUE THREAD

**Issue by dimakievua** [open-policy-agent/opa#1860]
# Expected Behavior
According to documentation the --bundle flag will load data files and Rego files contained
the bundle specified by the path. It can be either a compressed
tar archive bundle file or a directory tree.

# Actual Behavior
I created project:
```
$> tree data/
data/
├── manifests
│   ├── egress-config-search-config-cache.yaml
│   ├── egress-directexport-easybib.yaml
│   └── egress-sessionmanagement.yaml
└── policy.rego
```
Try to run OPA in docker with `eval` to test manifests, but it does not see manifests or report merge error.
```
$> docker run -v /opa/data:/data openpolicyagent/opa eval -d /data 'data' -f pretty --explain full
error loading paths: 2 errors occurred during loading:
/data/manifests/egress-directexport-easybib.yaml: merge error
/data/manifests/egress-sessionmanagement.yaml: merge error
$> docker run -v /opa/data:/data openpolicyagent/opa eval -b /data 'data' -f pretty --explain full
Enter data = _
| Eval data = _
| Index data = _ matched 0 rules)
| Index data = _ matched 0 rules)
| Exit data = _
Redo data = _
| Redo data = _
{
  "example": {
    "deny": []
  }
}
```
Here is rego:
```
package example

allow {
  input.kind = "ServiceEntry"
  input.spec.resolution = "DNS"
}

deny[msg] {
  input.kind = "ServiceEntry"
  input.spec.resolution = "STATIC"
  msg = "STATIC ServiceEntry is not allowed"
}

deny[msg] {
  input.kind = "ServiceEntry"
  ports := input.spec.ports[_].number
  ports["9000"]
  msg = "Port 9000 not allowed!"
}
```

but when I use `-i` option and point it on one file everything works ok:
```
$> docker run -v /opa/data:/data openpolicyagent/opa eval -i /data/manifests/egress-sessionmanagement.yaml -b /data 'data' -f pretty --explain full
Enter data = _
| Eval data = _
| Index data = _ matched 2 rules)
| Enter data.example.deny
| | Eval input.kind = "ServiceEntry"
| | Eval __local0__ = input.spec.ports[_].number
| | Eval __local0__["9000"]
| | Fail __local0__["9000"]
| | Redo __local0__ = input.spec.ports[_].number
| | Redo input.kind = "ServiceEntry"
| Enter data.example.deny
| | Eval input.kind = "ServiceEntry"
| | Eval input.spec.resolution = "STATIC"
| | Eval msg = "STATIC ServiceEntry is not allowed"
| | Exit data.example.deny
| Redo data.example.deny
| | Redo msg = "STATIC ServiceEntry is not allowed"
| | Redo input.spec.resolution = "STATIC"
| | Redo input.kind = "ServiceEntry"
| Index data = _ matched 0 rules)
| Exit data = _
Redo data = _
| Redo data = _
{
  "example": {
    "deny": [
      "STATIC ServiceEntry is not allowed"
    ]
  }
}

```
# Steps to Reproduce the Problem

  1. Create the same structure as described above. Create `policy.rego` file with the content described above.
  2. Download any `ServiceEntry` manifest. For example https://github.com/istio/istio/blob/master/tests/e2e/tests/pilot/testdata/networking/v1alpha3/service-entry-bookinfo.yaml
  3. Change resolution to STATIC or port to 9000
  4. Run command above

# Additional Info

**Comment by patrick-east** [comment]
Hi @dimakievua 

This is the expected behavior. 

With the `-d`/`--data` flag they are being loaded and OPA is attempting to merge them together for the virtual document under the `manifests` key. They all contain some shared top level keys (eg `kind`, `apiVersion`, etc) so you get the merge conflict.

With the bundle flag it is attempting to load them as if they were bundles which is not working as you expected because OPA is treating them as bundles and the manifest files are not named `data.json` or `data.yaml` (see https://www.openpolicyagent.org/docs/latest/management/#bundle-file-format for more details.)

Now, if they _were_ called `data.yaml` and were in the directory structure in your example you would receive the same merge conflict errors as if using `-d`.

> but when I use -i option and point it on one file everything works ok:

Correct. That is because you avoided the merge conflict and have provided the structure that the policy is expecting (it uses `input.kind` and `input.spec.X`). If you didn't load them as `input` with `-i` the policy would not evaluate as expected.


So, you're left with a few options:

1) Load them one at a time with `-i`
1) Load the files individually with `-d` and specify a prefix either by placing each in a sub-directory or loading them like `-d my_prefix:./data/manifests/some-manifest.yaml` (in that example the contents of the yaml file will be loaded into the `my_prefix` key)
1) Pre-process the yamls into a list and provide that to OPA as data or input
1) If the intention is to test the yaml manifests maybe check out [Conftest](https://github.com/instrumenta/conftest) which uses OPA to evaluate policies on these types of files and handles a bunch of these details around loading multiple test yamls automatically.

**Comment by dimakievua** [comment]
This option does not work with YAML:
`Pre-process the yamls into a list and provide that to OPA as data or input`
I tried and tool parse only first entry.
