### ISSUE TITLE
Add built-in function support to verify PGP signatures

### ISSUE THREAD

**Issue by platten** [open-policy-agent/opa#1873]
We have a use case for verifying annotations containing GPG signatures for Kubernetes manifests. It would be great to have a built-in function in rego which would support that!

**Comment by tsandall** [comment]
This is related to #1740. I'd like to understand whether this can be implemented by just exposing the Go standard library crypto APIs or whether we need something else. If it's more than just exposing the stdlib APIs then I'd like to understand if it's feasible to implement inside OPA (as opposed to having to pull in a 3rdparty library.)

**Comment by koponen-styra** [comment]
Having golang.org/x/crypto as a dependency sounds useful, indeed. I'm my limited experience with the library its exported APIs have been stable.

**Comment by patrick-east** [comment]
+1 for golang.org/x/crypto being pretty safe as a dependency

**Comment by ashutosh-narkar** [comment]
@platten would you be able to provide an example of how you plan to use the proposed builtin? I would imagine the builtin takes the public key, signed file and signature file.

**Comment by eshaanm25** [comment]
Hey @ashutosh-narkar! I know this thread is a bit old, but I wanted to add some interest for a GPG decryption function. GPG is often utilized to [sign images](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/building_running_and_managing_containers/assembly_signing-container-images_building-running-and-managing-containers) and is [natively used by container runtimes (like CRI-O) to verify if images can be deployed to an environment](https://medium.com/cri-o/secure-your-kubernetes-production-cluster-7ec607749583). Since a great use case of OPA is in Kubernetes, a built-in GPG decryption function would allow for shift-left verification of an image's GPG signature validity prior to deployment using OPA.

I think a GPG decryption function that takes GPG encrypted data and a public key as an input, and outputs the decrypted data would be a great addition to OPA's built-in function library.

**Comment by ashutosh-narkar** [comment]
@eshaanm25 that sounds like a useful builtin. Would you like to contribute? We are happy to help you through the process.

**Comment by eshaanm25** [comment]
I'd love to! Would you happen to have some resources or initial guidance on where custom functions exist in the OPA codebase so I can take a look at a few examples? I'll take a look at the repository tonight and also attend the next open-hours session as well 😄

**Comment by ashutosh-narkar** [comment]
> I think GPG functions would be an addition to this collection, what do you think?

That looks right. You can find an example of adding a builtin [here](https://www.openpolicyagent.org/docs/latest/contrib-adding-builtin-functions/) and also checkout the code for the recently added builtins for more examples. General code contribution guidelines can be found [here](https://www.openpolicyagent.org/docs/latest/contrib-code/). Thanks for looking into this!

**Comment by ashutosh-narkar** [comment]
Closing for now. We can re-open based on future need and demand.

**Comment by yogisinha** [comment]
Hi @ashutosh-narkar ,  I can pick this one if this is needed.
