### ISSUE TITLE
io.jwt.encode_sign HS256 created JWT fails to verify_hs256 or decode_verify

### ISSUE THREAD

**Issue by timhavens** [open-policy-agent/opa#1916]
# Expected Behavior
io.jwt.encode_sign() should create a JWT using alg HS256 that can be io.jwt.decode_verify() as valid, as well as io,jwt.verify_hs256() return true.

# Actual Behavior
both io.jwt.decode_verify() and io.jwt.verify_hs256() fail to validate even the most basic JWT created with encode_sign() **always returns false.**

# Steps to Reproduce the Problem

  1. package authz.orders.policy3    
  
default result = {"allow": false}

result = {"allow": verified_signature} {    
  secret := "3fbe6978b13f492454084fac1419dcfd"
  jwt_token := io.jwt.encode_sign({"typ":"JWT","alg":"HS256"},{},{"kty":"oct","k":secret})
  verified_signature := io.jwt.verify_hs256(jwt_token, secret)
}
  2. always returns false

# Additional Info
see: https://play.openpolicyagent.org/p/j10PtIDC0T
and: https://play.openpolicyagent.org/p/JezP8JLRWa

**Comment by timhavens** [comment]
This one shows that what verify_hs256() and decode_verify() both function as expected, when the JWT is created outside of rego/opa. [https://play.openpolicyagent.org/p/JztPnDavSd](url)

I think possibly this points towards the creation of the signature, or the application of the signature in the JWT.  Part of encode_sign() & encode_sign_raw() (perhaps?)

**Comment by tsandall** [comment]
@timhavens thanks for filing this. Sorry for the delayed response, most folks were at KubeCon last week. The problem in that example is that `io.jwt.encode_sign` expects a base64 url encoded key whereas `io.jwt.verify_hs256` does not. Here is a working example:

https://play.openpolicyagent.org/p/6arEUdqE56

Note that the `io.jwt.encode_sign` and `io.jwt.encode_sign_raw` functions return different answers. The reason is that `io.jwt.encode_sign` does not use the compact serialization format for the header and payload (e.g., it just calls String() on the terms and does not remove whitespace.)

I think we should at the very least improve the docs so that it's clearer that the encoding expects a base64 url encoded string whereas the verification functions do not.

**Comment by timhavens** [comment]
@tsandall THANK YOU for the clarification, this was very helpful.  I was certainly spinning my wheels on that for a while.  And no worries about any delay, I was aware of Kubecon and suspected as you said.
