### ISSUE TITLE
RBAC for GET Operations on CRD based on data

### ISSUE THREAD

**Issue by debianmaster** [open-policy-agent/opa#1949]
<This is question, not issue hence removed template format>

I understand OPA can be used for restricting PUT/POST operations of CRD's.
Can i also restrict CRD objects access based on user role and data of CRD instances?

i understand k8s native RBAC can restrict GET operations, but not at data level.
Im looking for something more that can act like a filter for CRD instances data.

**Comment by debianmaster** [comment]
im seeing there are no examples which bulk filter data.  most of the examples cover filtering one record only.

**Comment by tsandall** [comment]
@debianmaster I think we covered some of this on Twitter but you can definitely write a policy that accepts multiple records and filters them. Here's a simple example: https://play.openpolicyagent.org/p/c762NCgk0g. I'm going to close this for the time being because I think the question has been answered.
