### ISSUE TITLE
Log level debug

### ISSUE THREAD

**Issue by R3TA** [open-policy-agent/opa#1971]
# Expected Behavior
When i run the command by terminal: 
opa run --log-level debug --server
I must have now the level log with value equals to "debug"

# Actual Behavior
Level is set with default value "info".
# Steps to Reproduce the Problem
  1.opa run --log-level debug --server
  2.load query with policy that contains a function that use trace(string).
  3. Send query and after from terminal can't see the trace result.

# Additional Info
Some guide for load múltiples policies inside server opa at the same time and debugging locally.
Maybe exists other option for debug the opa policy.
The indication inside official documentation for me don't works, specifically in the part associated to the item debugging.
Exists some manner to force level to debug mode.
I hope that you can give me somes tips.
Thanks

**Comment by tsandall** [comment]
@R3TA thanks for filing this and sorry for the delay! Due to the holidays and catching up after the new year, responses have been a bit slow.

It sounds like the problem you're describing is that `trace()` is not printed to the console? That is the case today, we do not log trace() output to the console. The `trace()` output is included in the explanation which you can enable when you execute the policy query. For example, here is a trivial example:

```rego
package example

allow {
   input.method = "GET"
   trace("inside allow rule")
   not startswith(input.resource, "admin")
}
```

If you query OPA with explanations enabled, you can see the trace output:

```
$ curl 'localhost:8181/v1/data/example/allow?explain=full&pretty' -d '{"input": {"method": "GET", "resource": "foo"}}'
{
  "explanation": [
    "Enter data.example.allow = _",
    "| Eval data.example.allow = _",
    "| Index data.example.allow = _ (matched 1 rule)",
    "| Enter data.example.allow",
    "| | Eval input.method = \"GET\"",
    "| | Eval trace(\"inside allow rule\")",
    "| | Note \"inside allow rule\"",
    "| | Eval __local0__ = input.resource",
    "| | Eval not startswith(__local0__, \"admin\")",
    "| | Enter startswith(__local0__, \"admin\")",
    "| | | Eval startswith(__local0__, \"admin\")",
    "| | | Fail startswith(__local0__, \"admin\")",
    "| | Exit data.example.allow",
    "| Exit data.example.allow = _",
    "Redo data.example.allow = _",
    "| Redo data.example.allow = _",
    "| Redo data.example.allow",
    "| | Redo __local0__ = input.resource",
    "| | Redo trace(\"inside allow rule\")",
    "| | Redo input.method = \"GET\""
  ],
  "result": true
}
```

The explanations can be very verbose so there are some built-in filters for them. For example, to only see the `trace()` output (and some context which is useful debugging) set `explain=notes`:

```
$ curl 'localhost:8181/v1/data/example/allow?explain=notes&pretty' -d '{"input": {"method": "GET", "resource": "foo"}}'
{
  "explanation": [
    "Enter data.example.allow = _",
    "| Enter data.example.allow",
    "| | Note \"inside allow rule\""
  ],
  "result": true
}
```

It's arguable that we should have a way to print notes to the console.

Regarding the expected-vs-actual behaviour in the issue, you _will_ see DEBUG logs if you have things like decision logging, bundles, etc. enabled. If you are only running OPA as a server w/o any of those things enabled, there will be no DEBUG logs. You will see the full request/response body as part of the access log.

I'm going to close this issue because it seems the core problem was that you could not find the `trace()` output and that should be handled by what I've described above. We can revisit the console logging question in the future.

**Comment by rmetcalf9** [comment]
I really wish traces would be printed on the server console.
My use case is I want to confirm a third party library is sending the correct inputs.

**Comment by anderseknert** [comment]
@rmetcalf9 you could use decision logging for that, no?

**Comment by anderseknert** [comment]
For printing arbitrary values to console, there’s an issue for adding a “print” function here https://github.com/open-policy-agent/opa/issues/3319
