### ISSUE TITLE
expose input.identity for upstream evaluation

### ISSUE THREAD

**Issue by nmnellis** [open-policy-agent/opa#2000]
# Expected Behavior
All permissions in our system are scoped per user based on their jwt token. We would like to verify the jwt up front using system.authz and then decode the token in other policies to use the uid to evaluate user permissions on that token.

# Actual Behavior
input.identity is blank after system.authz

# Steps to Reproduce the Problem

  1. Enable token authorization basic
```
      - "--authentication=token"
      - "--authorization=basic"
```
  2. Submit request with Authorization: Bearer <token>
  3. input.identity should be available

**Comment by srenatus** [comment]
Isn't this somewhat at odds with input being provided by the query already? I.e. the only restriction on `input` is that it's JSON -- it could be an array or [a plain number](https://play.openpolicyagent.org/p/D2YZTd0HCU) even. If it's non an object, how would `identity` fit in? (Also, if it's an object, but, for some reason already has a key `identity`, what would win?)

That said, I can see how this would be useful... but we might need a better place to put it than `input` 😃

**Comment by nmnellis** [comment]
I agree `input` might not be the best location for it but its really nice to check the user authentication up front (so we dont have to check it in every allow). Also i believe there is no way to get headers within a non system policy so i thought this might be a way around that. rather than supplying the token in the header and the body

example
```
package system.authz

import data.tokens.verify_token

# Deny access by default.
default allow = false

# Allow token access to something
allow {
  verify_token
  input.method = "POST"
  input.path = [ "v1" , "data" , "something" ]
}

```

**Comment by srenatus** [comment]
🤔 I used to think of the system policy and the others as separate things insofar as the former govern _who may speak to OPA_, and the latter being used in answering that request. So, the identity in the system policy is that of another service (making a request), that checks if some user is allowed to do a thing.

But if it's the same entities in your use case, I suppose the identity being exposed on an object separate from input, say, `meta.identity`, would do the trick? Just trying to understand your issue though, curious what others think about this proposal...

**Comment by nmnellis** [comment]
i like the `meta.identity`. I plan to use mTLS to communicate with OPA so that will be my mode of of auth for system to system authentication. Since my users will always be providing an Authorization header, it's simple to pass the header along to OPA. Im not too familiar with the internals of OPA but having the JWT verification up front also saves me from having to check it in every allow block (possibly a performance improvement?)

**Comment by tsandall** [comment]
> Since my users will always be providing an Authorization header, it's simple to pass the header along to OPA.

It's hard to say without seeing the code, but my guess is that supplying the user's Authorization header as an HTTP header in the request to OPA vs. as part of the message body in the request to OPA is not a big difference. I could be wrong--but that's my guess.

> Im not too familiar with the internals of OPA but having the JWT verification up front also saves me from having to check it in every allow block (possibly a performance improvement?)

You can avoid repeating the token check in every allow block like this:

```rego
package example

default main_allow = false

main_allow {
  verify_token
  upstream_allow
}

verify_token {
   # logic to verify token
}

upstream_allow {
  data.user[decoded.uid].permissions[_].name == "admin"
}

# ... many other upstream_allow definitions
```

In this case, your clients would query for `example/main_allow` (or you can configure OPA to serve this as the default decision so that clients don't have to specify any name at all). The `main_allow` rule would be responsible for dispatching to the `upstream_allow` rules. Putting these rules into separate packages would let you call them all `allow` and also help with delegation, for example:

file1.rego:

```rego
package main

default allow = false

allow { verify_token; upstream.allow }
```

file2.rego:

```rego
package upstream

allow { data.user[decoded.uid].permissions[_].name == "admin" }
```

**Comment by tsandall** [comment]
I'm going to close this issue because the requested feature does not seem to be needed. When it comes to exposing the transport protocol to the policy, I get a bit worried about portability since it means the policy can only be evaluated with a specific protocol. If we wanted to evaluate the policy in another context (e.g., in-memory using Wasm, in development for test purposes, etc.) we need to have some way to supply that data.
