### ISSUE TITLE
Need Suggestion on my thought

### ISSUE THREAD

**Issue by 99ashish** [open-policy-agent/opa#2016]
Hi

I am working on a idea and in that i am facing one issue about security. Then i started googling about that problem then i came to know that may be openpolicy agent may fit So posting my thoughts over here .

**Idea**
I have some classified data along with url and now i am trying to publish that data on a public social group which is organization based like **yammer, Microsoft teams**.

**Issue**
When a user clicking on a particular url then i am not able to validate the authenticity of the user before redirecting to the page.

**Expectation**
I want that when a user click on that particular url then i want to check the authenticity of that user, if it a valid user then i will redirect to that url otherwise through an error.
For this use-case, can i take the advantage of openpolicy agent? if yes then how?

Any lead will be appreciated.
Thanks

**Comment by tsandall** [comment]
@99ashish we don't have any specific examples for your use case. With OPA you could express a policy that says something like (in English):

* By default, deny access
* If user is valid but insufficient permissions, redirect to another url
* If user is admin, allow access

For example: https://play.openpolicyagent.org/p/bdlqbkX8od

That said, the specifics of how you represent this kind of non-boolean decision, validate the user, integrate into the system in question, and more require more information.

I would recommend reading through the OPA documentation to get a better idea of what the project can do and perhaps trying out one of the tutorials (e.g., https://www.openpolicyagent.org/docs/latest/http-api-authorization/). This should give you a sense of whether OPA can help solve your problem at this point in time.

I'm going to close this issue because I don't think there's anything else I can say/do right now.
