### ISSUE TITLE
Remove deprecated plugin code to produce static executables

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#2049]
In v0.14.0 we deprecated the `--plugin-dir` flag that let users load dynamic libraries that could extend the OPA standalone server. That feature required that we build the OPA executable w/ CGO enabled which pulls in libc. Since there have been no complaints about removal of the `--plugin-dir` flag we should go ahead and remove the underlying code and update the build to set `CGO_ENABLED=0`. This will let us produce simpler OPA executables w/o any dependency on libc.

I think the plugin registration is tested by the code that does dynamic loading so we should make sure we don't regress on test coverage when we remove this feature.

**Comment by petemounce** [comment]
I bumped into this yesterday - I'm installing `opa` into an alpine linux 3.11 docker container so I can do `opa fmt` within a [pre-commit](https://pre-commit.com) check, but had an error. Here is the output from my efforts to repro within the container:

```txt
bash-5.0$ OPA_VERSION=0.17.1 curl --location --show-error --silent "https://github.com/open-policy-agent/opa/releases/download/v${OPA_VERSION}/opa_linux_amd64" -o ~/opa
bash-5.0$ chmod +x ~/opa
bash-5.0$ ~/opa
bash: /home/ci/opa: No such file or directory
bash-5.0$ file ~/opa
./opa: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, Go BuildID=5gH0Bz3j0LU8LJn4baHj/90H1PNr1w3lfpHYr9aSR/_72BNzbCyV4nyHKYFTZR/-2DhIAfdNAbwwiCJONYY, BuildID[sha1]=12d1e9f170dc1f64da8365d6cd85d63d2ebdfd7c, not stripped
```

That lead me to "oh, it's dynamically linked, I wonder if it's being built with CGO_ENABLED", and here I am.

My alpine linux container has `musl-dev` installed to it for a different dependency; this was not the package I am looking for. `libc6-compat` turned out to be the thing - at that point, I might as well use debian/ubuntu :(

PS - I'm finding `pre-commit` a bit of a local-dev-workflow joy - would you like a PR contributing my `opa fmt` plugin? That would look like a `.pre-commit-hooks.yaml` inside your repo root with an entry per plugin.

**Comment by tsandall** [comment]
@petemounce glad you found this issue. FWIW, you can build OPA with CGO_ENABLED=0 today: `CGO_ENABLED=0 go build`. I believe the Makefile will also respect the environment variable if you set it: `CGO_ENABLED=0 make build`.

RE: pre-commit hooks, thanks for pointer. I'll put it on my list of things to look into.

**Comment by petemounce** [comment]
@tsandall thanks. I'm ok with libc6-compat for the time being until this gets resolved.

In the meantime, I made #2127 on the offchance you'd want it.
