### ISSUE TITLE
Return non-zero exit codes in opa fmt

### ISSUE THREAD

**Issue by ironhalo** [open-policy-agent/opa#2149]
# Expected Behavior
Running `opa fmt` always returns a success exit code, even when formatting is not correct.  This is problematic in CI pipelines that check linting before allowing a merge.  Is it possible to either change the return codes for existing flags or such as `--list` or add a `--check` flag?

# Actual Behavior
`opa fmt` always returns a successful exit code

**Comment by patrick-east** [comment]
Seems like this might be useful. The impression I have though is that in general other formatting tools don't necessarily return error codes unless something went wrong trying to format (eg gofmt or goimports). The idea being that the exit code is related to the formatting operation itself not whether it made changes or not.

A pretty standard pattern for doing format checks/linting in CI's with these tools is to use the option to only show a diff or changes and then do the "right" thing based on that. Usually you don't only want a non-zero exit code, you want some actionable thing in the output to help the person reading the CI logs fix it.

Something pretty simple would be a script step like:

```bash
#!/usr/bin/env bash

set -e

DIFF=$(opa fmt --diff $@)

if [[ -n "${DIFF}" ]]; then
    echo 'ERROR: `opa fmt` requires the following changes...'
    echo "$DIFF"
    exit 1
fi

```

So you get the exit code that makes sense for your workflow and some useful info for the dev who needs to fix the policy. Could swap in `--list` instead of `--diff` too if maybe you don't want to spew out the actual changes/policy source in the console. 

Anyway, if we do want to move ahead with changing the return code, I think adding a like `--error` or something flag to let users opt in would make the most sense. The idea being you can just add it in with whatever other flags were included and have the command return an error code if any changes were made.

Personally I'd lean towards not changing the error codes and sticking with using the output as a building block for making those kind of decisions. I'm curious if other folks have opinions on this too.

**Comment by srenatus** [comment]
> Personally I'd lean towards not changing the error codes and sticking with using the output as a building block for making those kind of decisions. I'm curious if other folks have opinions on this too.

We're using [some awk magic over here](https://github.com/chef/automate/blob/0de8065086367dadc8e99b42d2b9b54b5b1d1657/components/authz-service/engine/opa/policy/Makefile#L1-L2), but it's basically the same, "if there's output, fail".

Comparing to `gofmt`, `opa fmt` has the same behaviour... I think I prefer that, too.

**Comment by srenatus** [comment]
Another data point, `git diff` has [an `--exit-code` flag](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---exit-code) for this behaviour:

> `--exit-code`
>
> Make the program exit with codes similar to diff(1). That is, it exits with 1 if there were differences and 0 means no differences.)

(...but `diff` and `git diff` are not formatters... 💭)

**Comment by johanneslarsson** [comment]
Isn't this solved using? 

`
test -z "$(opa fmt -l *)"
`

Or didnt "-l" exist back then?

**Comment by anderseknert** [comment]
It's mentioned in the issue description, so it probably did exist ;) 
I agree though, this should be easy enough to test for, and formatting changes are not really errors, so I think that's the better way of doing it.

**Comment by dudicoco** [comment]
Can this please be added as an additional flag?
Some fmt/diff tools do exit with error, it is an important functionality as part of a CI process, without resorting to bash scripts to make it work.

Thanks

**Comment by tsandall** [comment]
Given that we don't ship a shell inside the standard OPA Docker image, it would be nice if `opa fmt` could optionally exit w/ a non-zero status code to avoid the bash tricks.
