### ISSUE TITLE
Docs: Kubernetes policy primer example is missing output box

### ISSUE THREAD

**Issue by rleekin** [open-policy-agent/opa#2177]
in the documentation, under the *Policy Primer via Examples* section, in the *Deny Rules* section. The last sentence of that section ends without an image or answer. 

"When the deny rule is evaluated with the input above, the answer is:"

I think this is an error and I would be happy to fix it if you tell me what should be there. Thanks

**Comment by patrick-east** [comment]
Thanks @rleekin that is indeed an error.

It looks like it should be showing the output of the "live doc" snippets above, the GitHub markdown renderer shows it a little different (although still broken) https://github.com/open-policy-agent/opa/blob/master/docs/content/kubernetes-primer.md#deny-rules

![image](https://user-images.githubusercontent.com/3614287/76246795-a324b980-61fb-11ea-96d7-6cae67290daf.png)

In the source code it has https://github.com/open-policy-agent/opa/blame/master/docs/content/kubernetes-primer.md#L83-L88 (linking to blame since all the nicer views hide the markdown 😢 ) Where the  `live:container_images:query:hidden` section isn't closed, so it breaks the `output` section. For reference on those blocks take a look at https://github.com/open-policy-agent/opa/tree/master/docs#live-code-blocks

So.. I think what we need to do is add the ``` to close the `query` section, which should get the output box to appear. Then for the query we probably want `data.kubernetes.admission.deny` since it is referencing the policy up above, which should then populate the output box correctly with the result.

**Comment by rleekin** [comment]
okay, I'll work on fixing this. Thanks Patrick
