### ISSUE TITLE
Support incremental policy downloading from Bundle API

### ISSUE THREAD

**Issue by WeiZhang555** [open-policy-agent/opa#2182]
I want to make a standalone OPA service for providing authz services to other workloads, then I found that OPA doesn't persist policy data, then  I read the [external-data](https://www.openpolicyagent.org/docs/latest/external-data/) chapter,  and found that Bundle API may help. 

But I want to check first that does the Bundle API support incremental downloading? For example, when OPA service started, it pulled initial bundle with lots of existing policies, then it would pull only some updated policies periodically. This could help when there're lots of policies in the bundle service. I know the bundle file format supports this, but does the Bundle API support this？ I can't find any evidence from documents and codes.

**Comment by patrick-east** [comment]
Hi! The bundle API supports using ETags so that it will only download and process the bundle when there are changes to it. However, OPA does not currently support incremental changes to the bundle. It will download and process the entire bundle. There is a feature request tracking this https://github.com/open-policy-agent/opa/issues/1055 with the goal to allow for downloading what are essentially patches to the bundle rather than the whole thing.

**Comment by WeiZhang555** [comment]
@patrick-east Thanks for your response, I think the proposal from the link is exactly what I want. I will track the threads. Looking forwards to this feature!

**Comment by WeiZhang555** [comment]
Close this.
