### ISSUE TITLE
Allow `default ... := ...`

### ISSUE THREAD

**Issue by mikol** [open-policy-agent/opa#2222]
# Expected Behavior

```
default allow := false
```

# Actual Behavior

```
1 error occurred: policy.rego:3: rego_parse_error: default rules must use = operator (not := operator)
	default allow := false
	^
```

# Additional Info

Maybe there’s a very good reason to reject `default ... := ...`. But from the surface, it seems arbitrary.

**Comment by tsandall** [comment]
It is somewhat arbitrary. The underlying reasoning is that rules declared with `:=` cannot be redeclared. Since `default` is only ever meaningful/useful when you have another rule with the same name, it doesn't make sense to use `:=`.

The reason not to permit `:=` on default is that people will almost certainly do something like...

```rego
default allow := false

allow {

}
```

...and then complain when it gets rejected.

**Comment by tsandall** [comment]
@mikol I'm going to close this for now. If you think we should revisit we can discuss it further.

**Comment by mikol** [comment]
I’ll allow it 😉

**Comment by tsandall** [comment]
![i see what you did there](https://media.giphy.com/media/5gw0VWGbgNm8w/source.gif)
