### ISSUE TITLE
OPA re_match unexpected behaviors

### ISSUE THREAD

**Issue by yehaolan** [open-policy-agent/opa#2304]
Result from the terminal:
```
# (1)
> re_match("aws-*-manager", "aws-cluster1-manager") # expect true
false

# (2)
> re_match("aws-cluster*-manager", "aws-cluster1-manager") # expect true
false

# (3)
> re_match("aws-cluster[0-9]+-manager", "aws-cluster1-manager") # expect true
true

# (4)
> re_match("*-manager", "aws-cluster1-manager") # expect true
1 error occurred: re_match("*-manager", "aws-cluster1-manager"): eval_builtin_error: re_match: error parsing regexp: missing argument to repetition operator: `*`
```

I believe `*` means 0 or more characters. Why (1) and (2) are evaluated to `false`? And why (4) can cause an error?
Can it be consider as bug? If not, can someone explain why? 
By the way, https://www.openpolicyagent.org/docs/latest/policy-reference/#regex does not provide enough details or examples. Is there any docs showing more examples or guidance on `re_match` function?

**Comment by tsandall** [comment]
@yehaolan in most regular expression syntaxes, quantifiers like `*` match preceding the token. That's why (1) and (2) produce false and why (4) produces an error.

You'll need to figure out what characters can exist in the different parts of these string identifiers. Assuming they can be word characters (a-z A-Z 0-9 _) then you could say:

```
re_match(`aws-\w+-manager`, "aws-cluster1-manager")
```

Note that `*` matches zero or more and you probably don't want to match `aws--manager` right?

Also, lastly, note that I used backtick instead of quotes for the regexp pattern. This is a "raw string" in Rego (https://www.openpolicyagent.org/docs/latest/policy-language/#strings) similar to the same thing in Go. This means you don't have to escape the backslash required to specify \w.

**Comment by yehaolan** [comment]
Make sense!
Thank you @tsandall. I am going to close the issue because it's not a bug.
