### ISSUE TITLE
Enable golang race detection by default with unit tests

### ISSUE THREAD

**Issue by patrick-east** [open-policy-agent/opa#2388]
There is a `-race` option we can supply when running `go test` that will enable race detection and report errors. We should have this enabled by default (unless its too slow) with the opa unit test target (`make test`) or at a minimum as part of the travis job.

Checking with the current state of things when run we do have failures so we will need to correct those first.

**Comment by tsandall** [comment]
After discussing this offline we've decided to enable the race detector only for PR builds with a special test target--we don't want to slow down normal builds or block releases based on the result of the race detector (since the race detector cannot detect all races, it may not find a race until we cut a release which could be problematic.)
