### ISSUE TITLE
Update introduction page to use double quotes instead of single quotes in command line examples

### ISSUE THREAD

**Issue by debasisc-opa** [open-policy-agent/opa#2391]
Working in this site
https://www.openpolicyagent.org/docs/latest/

Environment - Windows 10

When I try example as mentioned in this website, I receive following error.
Can you please check and advise?

Thank you

``
C:\OPA>opa_windows_amd64.exe eval -i input.json -d example.rego 'data.example.violation[x]'
{
  "errors": [
    {
      "message": "illegal token",
      "code": "rego_parse_error",
      "location": {
        "file": "",
        "row": 1,
        "col": 1
      },
      "details": {
        "line": "'data.example.violation[x]'",
        "idx": 0
      }
    }
  ]
}

C:\OPA>
``

**Comment by tsandall** [comment]
@debasisc-opa I believe this is a cmd.exe issue. As you can see from the details, the actual line fed into OPA is `'data.example.violation[x]'`. In other shells, the `'` characters would have been removed--hence the parse error. Change `'` to `"`--that should work in cmd.exe.

I'm going to rename the issue and mark it as a docs fix because I think others on Windows will run into this and it's easy enough to update the introduction to use `"` instead of `'`.

**Comment by debasisc-opa** [comment]
Thanks everyone. Double quotes - work fine for Windows environment.
