### ISSUE TITLE
React App getting CORS error while accessing opa server using REST API

### ISSUE THREAD

**Issue by drkhosla** [open-policy-agent/opa#2453]
I am developing app in React and wanted to access REST API of opa data. When I try to get user role using url http://localhost:8181/v1/data/app/userrole, but get a CORS error and unable to access data. To resolve this, either I disable web security of client browser or run proxy/middleware to access opa data. This is not practical while access multiple API.

How can I set headers of opa server so that client get CORS header. I mean, can I set server responding header of opa server to "Access-Control-Allow-Origin:*" or "Access-Control-Allow-Origin:http://localhost:3000" so that react app, which is a browser JavaScript client, can access opa data using REST API. 

My opa server details
Version: 0.19.2
Build Commit: 40f9c1fe
Build Timestamp: 2020-04-27T22:51:01Z

**Comment by tsandall** [comment]
It's not currently possible to configure OPA to set CORS headers in server. I recommend running a simple proxy (like nginx) in front to solve this. I'm going to close since there are no plans to support this soon.

**Comment by francoisauclair911** [comment]
So basically there is no way to query OPA directly from a frontend without using a proxy ?

**Comment by anderseknert** [comment]
@francoisauclair911 the deployment model for OPA usually entails running OPA as a sidecar, or at least not exposed directly to the frontend. Could you expand some on your usecase? Would be interested in learning more!

**Comment by francoisauclair911** [comment]
@anderseknert, I was thinking about loading user roles via bundles and then fetch these roles via the frontend to build the UI/UX depending on the roles of the user.

**Comment by anderseknert** [comment]
Thanks @francoisauclair911 👍 

I think your best bet currently is to add a new endpoint in your backend app that talked to OPA in order to push this to the frontend. Adding CORS support for OPA itself would be problematic, as you'd additionally need to secure the OPA server from tampering requests or else "anyone" would be able to modify or delete policies via the exposed REST API. 

You _could_ of course store a token for authentication against OPA in the front end, but you'd normally want to avoid that, and I doubt that implementation would be less effort/complex than adding a new backend route. 

Another option would be to only allow CORS on specific endpoints like `/v1/data`, with the risk of misconfiguration having quite dire consequences.

All that said, I'm not entirely opposed to the idea.. it just seems to introduce about as many problems as it solves, or more :)
