### ISSUE TITLE
opa rego files for validate and mutation and Webhooks configuration

### ISSUE THREAD

**Issue by yaminisridaran** [open-policy-agent/opa#2499]
I am  using opa and Kube-mgmt.
I am using the example for validate and mutate rego files as mentioned at https://github.com/teq0/opa-k8s-admission which uses package system. 
Is this recommended way to have both vallidation and mutation rego files?
(or)
Do we need to have a Webhooks configuration with a path configured and mention the package as per the path and have multiple main rego files is the recommended?

Can you suggest me which is the recommended model

**Comment by patrick-east** [comment]
I think that typically if you had a need for both validating _and_ mutating it makes sense to do them as a single webhook configuration and rego query entrypoint. Otherwise you are adding in additional latency to the API server as it must make two separate requests (assuming the resource applies to both webhook configurations)

The example you linked to shows a very nice way to do it. Unless you have a reason _not_ to use that method I would personally recommend following that approach.

Another point of reference is the official OPA library sample for mutating admission which does the same kind of thing: https://github.com/open-policy-agent/library/tree/master/kubernetes/mutating-admission There is a single "main" entry point which handles both cases.

Other folks in the community may have different insight or opinions however.

**Comment by yaminisridaran** [comment]
Thank You @patrick-east
