### ISSUE TITLE
High memory consumption

### ISSUE THREAD

**Issue by amar1728** [open-policy-agent/opa#2523]
We are evaluating OPA for our use case and found that it is consuming very high memory. We have data around 250 MB and one rego policy. When an opa server is started with this data it consumes around 4500MB of RAM and goes up to 7500MB during evaluation of queries. 

The idea is to deploy OPA as a side car with other application servers and may have 1000's of such servers. Since ~8GB of RAM requirement for a side car is not a viable solution, is there any other way to reduce the memory footprint?

Even with this scale of data the evaluation time is very good (~500us). Is there a solution so that we can have less memory consumption at the cost of eval time.

**Comment by patrick-east** [comment]
The expected guideline for OPA (well for golang really) unpacking JSON data is something like 20x increase over the serialized size once it is in-memory and in golang structs. So for 250MB I would expect to see something like 5000MB, which is pretty much on part with what you are seeing.

The increase while evaluating is potentially due to the structure of the policies, it could be possible to lower that.

Typically the way to lower the memory usage is to limit how much data you put into OPA. Do you need all 250MB for each evaluation? Can you supply only a small portion as part of the `input` context for an evaluation instead?

**Comment by patrick-east** [comment]
One more thing to add, there are a few options listed in https://www.openpolicyagent.org/docs/latest/external-data/ along with some trade-offs. The [Summary](https://www.openpolicyagent.org/docs/latest/external-data/#summary) mentions which ones are going to have size problems.

**Comment by amanhigh** [comment]
Hi Patrick,
I am a colleague of amar. Thanks for a quick reply. 

As amar mentioned of 250MB of Bundle Size. We have various tenants with varying sizes of Bundles. Although not all tenants  would need 250MB but this is scenario in worst case. In such cases we have on Business Unit having lakhs of business partners which has a dozen different roles. Also these roles then vary based on location etc hence their bindings.

We were looking at a mechanism where this memory can scale and reduce say on need bases like lazy loading and then unused structs being unloaded where we sacrifice latency but gain on memory.

Not sure if such a tune-ability today exists in OPA.

On Second suggestion we have gone through various external-data means. Here since we have large number of servers hosting the application. We are ok with bundle sitting (say as a bundle file) on disk but memory seems a concern.  

Push and Pull both involve getting data from another server. rather than the local bundle file. We will explore those as well.

**Comment by tsandall** [comment]
Closing this for now since there's not much that can be done in terms of memory usage. I'd recommend exploring whether `Option 2` from the external data page would work for your use case. It sounds like the bundles contain user or resource attributes for all users/resources in the system. If you have a proxy in between the app and OPA, that proxy could fetch the relevant user and resource attributes to supply as `input`. This way you don't have to worry about replicating all of the users/resources into OPA.
