### ISSUE TITLE
Rule name hides builtin functions thus "undefined function" on call

### ISSUE THREAD

**Issue by SuchSkill** [open-policy-agent/opa#2567]
Running rego with rule name the same as builtin function will produce obscure error.

```
package play
regex{
	regex.split(" ", "str ing")
}
```

# Expected Behavior
Forbid rule name that may hide builtin functions

# Actual Behavior

> 1 error occurred: policy.rego:5: rego_type_error: undefined function data.play.regex.split

# Steps to Reproduce the Problem
https://play.openpolicyagent.org/p/5gNrsNDZBV

**Comment by tsandall** [comment]
@SuchSkill thanks for a filing an issue!

As is, rejecting rules that overlap with built-in functions would be problematic since addition of any new built-in functions could potentially break existing policies. We definitely do not want that.

I'm not sure there is a great way around this. One option is to namespace all builtins under a reserved keyword (e.g., `builtin`) however that would need to be done over time in a backwards compatible manner.

**Comment by tsandall** [comment]
This is related to #2600.

**Comment by tsandall** [comment]
Closing this for now because we can't reject polices that redefine built-in functions as that would make any new built-in function addition (potentially) backwards incompatible.
