### ISSUE TITLE
'input' and 'data' should be reserved identifiers

### ISSUE THREAD

**Issue by jpeach** [open-policy-agent/opa#2600]
## Expected Behavior

If I define a function whose name is `data`, the compiler should probably emit an error that directly specifies that's not going to work.

## Actual Behavior

I ended up with this compiler error:
```
 rego_type_error: undefined function data.contour.configmap.data.contour.configmap.data.contour.resources.get
```

## Steps to Reproduce the Problem

```
package contour.resources.configmap

import  data.contour.resources

data(name) = obj {
  config := resources.get("configmaps", name)
  obj := object.get(config, "data", {})
}
```

## Additional Info

I'm using OPA  v0.19.2 as a library.

**Comment by tsandall** [comment]
We currently allow policies to override built-in functions as well as the `input` and `data` global variables.

`input` overriding can actually be quite useful during development/debug cycles if you want to quickly replace the value of `input` inside of a package for test purposes. `data` overriding is less useful because you're unlikely to replace the value of `data` correctly.

In this case, I'm assuming the import `data.countour.resources` was resolved to the local `data` function (so the reference `data.contour.resources` became `data.contour.resources.configmap.data.contour.resources` like in the error message.) I would have expected imports to be fully qualified so it's arguable this is a bug and should be fixed. That said, I'm not sure how I feel about disallowing overriding entirely.

cc @timothyhinrichs WDYT?

**Comment by timothyhinrichs** [comment]
Thanks for the reminder @tsandall that supporting overriding for functions is necessary to ensure backwards compatibility of policies.  I could see prohibiting overriding `data` (especially) and `input` (possibly).  Tooling around the playground, vscode plugin, etc. has improved to the point where I don't personally use `input` overriding anymore for debugging.
