### ISSUE TITLE
Novice problem

### ISSUE THREAD

**Issue by andyyumiao** [open-policy-agent/opa#2657]
1. If i want to use the library integration, is there a java sdk?
2. How many QPS does the default HTTP service support?
3. External storage is not supported,  so service restart will cause policy and data lossing, how to solve the problem？

**Comment by tsandall** [comment]
1. There is no Java SDK. The primary library support is for Golang.
2. The SLO for query latency is 1 millisecond, so ~1K QPS. Query latency can be lower (e.g., 100s of microseconds or less) in some cases. Other tricks like using Unix domain sockets instead of TCP sockets also improve performance.
3. See the https://www.openpolicyagent.org/docs/latest/management page in the docs--specifically the sections on Bundles.
