### ISSUE TITLE
Allow set() to take arguments

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#2669]
Having spent some time recently with people entirely new to OPA/Rego, the array to set conversion has been perceived as clunky, especially so if coming from a language where comprehensions are not the norm. Extending the `set()` built-in to take arguments would help in this, without adding extra syntax / built-ins.

## Expected Behavior

list := ["a", "b", "c"]
s := set(list)
or
s := set("a", "b", "c)

## Actual Behavior

list := ["a", "b", "c"]
s := { x | x := list[_] }

**Comment by tsandall** [comment]
Clunky can be a bit tough to define. Users do need to learn what comprehensions are, but they'll have to do that anyway if they want to transform collections (without defining rules) or compute aggregates (both of which are common operations). 

From my point of view, introducing multiple ways of expressing the same thing creates it's own challenges. What we currently have is quite simple and consistent (with the exception of the `set()` syntax which is a necessary evil to resolve ambiguity.)

Empty values:

```
[]
{}
set()
```

Static values:

```
["a", "b", "c"]
{"a": 1, "b": 2}
{"a", "b", "c"}
```

Dynamic values:

```
[x | ...]
{x: y | ...}
{x | ...}
```

> Where `...` is any valid Rego query.

All in all, I think we'd be better off introducing comprehensions sooner rather than later. I'm inclined to close the issue.

**Comment by anderseknert** [comment]
Thanks @tsandall . I don't feel strongly about this myself, but figured I should at least forward the request. At least there's a ticket for searchability now should others feel the same and want to chip in. I'm closing the issue then.
