### ISSUE TITLE
Have pprof endpoints exposed on diagnostic port

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#2727]
When running OPA with the `diagnostic-addr` enabled, it would make sense to expose the pprof endpoints there as they definitely fall into the diagnostic category.

## Expected Behavior

Running `opa run --server --pprof --diagnostic-addr :8282` exposes pprof endpoints on port 8282.

## Actual Behavior

Running `opa run --server --pprof --diagnostic-addr :8282` exposes pprof endpoints on port 8181.

## Additional information

If running OPA with `--pprof` but without `--diagnostic-addr` the current behavior is expected/OK.

**Comment by patrick-east** [comment]
This came up when we first added the diagnostic port. IIRC the reason they are not included was that they potentially expose more sensitive data, so we didn't want to make it easy to expose them "publicly" next to the less sensitive probes/metrics endpoints.

**Comment by anderseknert** [comment]
That's an interesting point, and good to know it's been taken under consideration :) 

I also noticed yesterday that the `/health` and `/metrics` endpoint still are exposed on the "regular" 8181 port too even when running with `--diagnostic-addr :8282`, so if that would also be the case for `--pprof` it would just add one more exposure point. My idea was rather to have all those endpoint exposed _only_ on the `--diagnostic-addr` address so that those could be exposed or isolated independently from the main server.

**Comment by tsandall** [comment]
The `--diagnostic-addr` option was added so that certain endpoints could be served on a public interface separate from the rest of the API. Only endpoints that are considered "safe" to expose publicly w/o any additional configuration should be added. In this case, --pprof is not considered safe because it could expose sensitive info (e.g., command line arguments, filenames, etc.) and create potential for DoS attacks. Because of this, I don't think we want to expose pprof on the diagnostic listener.

I'm tempted to close this because I don't think it's worth it to disable the /metrics and /health endpoints on the normal listener when the diagnostic listener is enabled.

Maybe a note in docs/content/security.md page mentioning that /metrics and /health are still exposed on the normal server address would be enough? E.g., in the `## Secure Health and Monitoring` section:

```
> Note, the `/metrics` and `/health` APIs will still be exposed on the normal server address as well.
```

**Comment by anderseknert** [comment]
Sounds good to me! I think the definition of "public" here is key, as even a public interface obviously wouldn't need to be exposed to the outside world. In the normal kubernetes cluster case I would think that if you've made it far enough to have access from the inside, some OPA pprof endpoint is probably not your most interesting target ;) But there are obviously many other server setups that OPA needs to take into consideration. What I wanted was more or less an easy way for the same tools or scripts that do health checks to be able to quickly download the pprof data should something not look right. The few times we've needed it so far it's always been too late.

The doc addition looks good regardless!
