### ISSUE TITLE
input data when run on server mod

### ISSUE THREAD

**Issue by cometta** [open-policy-agent/opa#2740]
may i know after started ./opa run --server  --input input.json ; if we update the content of input.json, how do we load the new changes into opa without restarting the server. can we re-input the file through interactive mode ?

**Comment by patrick-east** [comment]
Couple of things to maybe clarify. First up, the input when using `opa run --server` is on a per-request basis, there isn't (afaik) an `--input` flag to let you pass it in on the CLI. You would provide it as part of the API request to the server.

Now, if you meant to use the json document as external data (ie, stuff under `data.*` in the policy instead of under `input.*`, and running OPA with something like `opa run --server data.json`) you can use the `--watch` flag to get the document reloaded, but that isn't really recommended for production use-cases. Typically if you have data changing over time you will want to look into using bundles (check out https://www.openpolicyagent.org/docs/latest/management/ for details)
