### ISSUE TITLE
Use data.* in mask upsert

### ISSUE THREAD

**Issue by gshively11** [open-policy-agent/opa#2753]
## Expected Behavior

We pass an encoded JWT in `input.sso_jwt` to our `/v1/data` calls. We don't want this full JWT to appear in our decision logs. We also do a bunch of trimming/shaping of the JWT in our rego policy. We would like to replace the encoded JWT in the decision logs with our trimmed/shaped JWT from policy. 

## Actual Behavior

When we create a mask upsert rule that references data.* rules, the mask operation fails and the encoded JWT still appears in the decision log.

## Steps to Reproduce the Problem

OPA version: 0.24.0-dev

```
package system.log

import data.employee_payload

mask[{"op": "upsert", "path": "/input/sso_jwt", "value": x}] {
  x := {
    "employee": employee_payload
  }
}
```

**Comment by tsandall** [comment]
The decision log mask rules can refer to any of the other rules/data loaded into the engine when the policy was evaluated (under the hood, the decision log mask is evaluated inside the same transaction as the rest of the policy query so any observed values will be consistent.)

Can you double check that the path `data.employee_payload` is correct? It looks a bit fishy because rules are namespaced by a package so unless you've loaded raw JSON at `data.employee_payload` the reference to that document will be undefined.

**Comment by gshively11** [comment]
I'll try again, what I posted above was mostly pseudo code.

**Comment by gshively11** [comment]
Ah, I think this is due to #2752.  The data I'm referencing is using the input I'm masking. If I just create a simple rule that returns a string, it works fine.  Closing this.
