### ISSUE TITLE
OPA bench fails to find custom functions

### ISSUE THREAD

**Issue by eatwithforks** [open-policy-agent/opa#2756]
I have two rego files with one importing another and trying to run opa bench against the main rego file but receive an undefined function error message.

### Reproduce 

pod_template.rego
```
package lib.pod_template

# pods
pod_template() = pod {
  input.review.object.kind == "Pod"
  pod := input.review.object
}

# statefulsets, deployments, daemonsets, jobs
pod_template() = pod {
  input.review.object.spec.template.spec.containers[0]
  pod := input.review.object.spec.template
}
```

k8sdiagnosticsreadinessprobe.rego
```
package k8sdiagnosticsreadinessprobe.rego
import data.lib.pod_template

violation[{"msg": msg}] {
  c := pod_template.pod_template().spec.containers[_]
  c.readinessProbe.httpGet.path == "/z/diagnostic"
}
```

**Running OPA bench:**
```
opa bench -d policies/k8sdiagnosticsreadinessprobe.rego "data.k8sdiagnosticsreadinessprobe.violation"
```

**Fails with**
```
1 error occurred: policies/k8sdiagnosticsreadinessprobe.rego:16: rego_type_error: undefined function data.lib.pod_template.pod_template
```

I also tried with `--import "policies/lib/pod_template.rego"` flag but received the same error.

## Expected Behavior
Expect to properly import the functions from pod_template.rego and not error out.

opa version
Version: 0.21.0
Build Commit: 3807c481
Build Timestamp: 2020-06-16T15:39:55Z
Build Hostname: 2ff9448ee1c6

**Comment by patrick-east** [comment]
Thanks for filing the issue!

You will need to provide both rego files on the CLI for `opa bench` so that OPA can load the helper function. The `import` keywords in the Rego policies (and `--import` CLI flag) do not affect which files are loaded.

Try something like:
```
opa bench -d policies/k8sdiagnosticsreadinessprobe.rego -d pod_template.rego "data.k8sdiagnosticsreadinessprobe.violation"
```
(substitute in the correct path to the `pod_template.rego`)

One thing to note too is that you can load entire directories of policy too, eg `opa bench -b policies/`

**Comment by eatwithforks** [comment]
ah perfect! Thanks @patrick-east.
