### ISSUE TITLE
OPA and DataBase

### ISSUE THREAD

**Issue by subbukoutlook** [open-policy-agent/opa#2770]
Hi ,

We would like to store OPA policy and data in Database. Is there any documentation which explains the integration of OPA and Database.

If OPA to DB connection is not supported is there any alternate approach in OPA to store data and policy.

Please Advice.

Thanks,
Subbu

**Comment by tsandall** [comment]
OPA doesn't integrate with any databases out of box because (i) OPA is not intended to be the source of truth for policy (and data/context) and (ii) OPA is intended to enable a distributed policy enforcement model where policy decision-making occurs as close to the enforcement point as possible.

To load policies and data into OPA you have a few options however the default is to use Bundles. You can read more about managing policy & data in OPA here: https://www.openpolicyagent.org/docs/latest/management/ and https://www.openpolicyagent.org/docs/latest/external-data/.

Closing this issue because there's nothing else to answer at the moment.
