### ISSUE TITLE
Mask rules that upsert data.* rules that use input don't work

### ISSUE THREAD

**Issue by gshively11** [open-policy-agent/opa#2809]
## Expected Behavior

```rego
package data.foo

default bar = null
bar = e {
  input.sensitive
  e := "no longer sensitive"
}
```

```rego
package system.log

import data.foo

mask[{"op": "upsert", "path": "/input/sensitive", "value": x}] {
  x := foo.bar
}
```

Decision log should contain
```json
{
  "input": {
    "sensitive": "no longer sensitive"
  }
}
```

## Actual Behavior

Decision log contains
```json
{
  "input": {
    "sensitive": null
  }
}
```

This appears to be because when the AST is rebuilt for masking, input actually exists at `input.input`. If I modify the `bar` rule to check `input.input`, it works as expected.

## Steps to Reproduce the Problem

* OPA version: 0.25.0-dev
* See example policy above

**Comment by tsandall** [comment]
The input provided when the `system.log.mask` decision is evaluated is different from the input provided when the policy evaluated. This is necessary so that `system.log.mask` can inspect other fields in the event like the result. If you want to re-use rules from the rest of the policy that depend on input, use `with`:

```rego
mask[{"op": "upsert", "path": "/input/sensitive", "value": x}] {
  x := foo.bar with input as input.input
}
```

This should resolve the problem you're running into.

**Comment by gshively11** [comment]
Oh slick, didn't know about `with`.  Thanks!
