### ISSUE TITLE
Find difference between 2 json objects

### ISSUE THREAD

**Issue by MahikanthNag** [open-policy-agent/opa#2812]
Do we have any built-int method that we can use to find difference between two json objects? It would help if a method can return the json_paths where the values are different between them. (OR something similar)

## Expected Behavior
x := {"a": true, "b": false, "d": {"hi":"bye"}}
y := {"b": "foo", "c": 4, "d": {"hi":"hey"}}
json.diff(x, y) // Should return "d/hi" since the values are different at that path

**Comment by tsandall** [comment]
This kind of thing has come up in the past (#1617). If we add diff support for JSON structures we should probably just use JSON Patch to represent the diffs (RFC 6902) and then we can both diff and patch JSON structures.

**Comment by MahikanthNag** [comment]
@tsandall Thank you for considering this feature. But till then, is there an elegant way we can parse a json object field by field and write a custom method? I tried but had hard time parsing more than one level deep for a JSON object.

**Comment by tsandall** [comment]
If performance is a concern then I would not recommend implementing this in Rego--however, I think you could compute a diff like so: https://play.openpolicyagent.org/p/5cFNv0Siio. Note, the correct answer for your original input should include "b" since that key appears in both objects.

**Comment by MahikanthNag** [comment]
That snippet is all we are looking for! Thanks a ton!
The JSON objects we use are not so huge so performance should not be a huge issue, will still talk to my team about it. 👍

**Comment by PapashaEnot** [comment]
@tsandall  Hello!  Is the diff function still planned for implementation? Unfortunately, the proposed solution does not always work, for example, I have a spec field in which a new element is added ("test") and and other is updadet ("ports"). Is it possible to create json diff using only rego ? Or I have to call some extarnal service/util (for example by HTTP) ?

##### Old  object
`"spec":{"ports":[{"name":"https","protocol":"TCP","port":443,"targetPort":443}]}
`
##### New object
`"spec":{"test":"rest","ports":[{"name":"https","protocol":"TCP","port":443,"targetPort":443},{"name":"grpc","protocol":"TCP","port":5454,"targetPort":5454}]}
`

##### Expected behavior:
**{"spec/ports", "spec/test"}**

**Comment by srenatus** [comment]
Hello there! It's not on the backlog right now.

From looking into the playground example @tsandall shared, with your objects, it doesn't look too bad, I think: https://play.openpolicyagent.org/p/dTy2IEVwuN

When evaluating `diff`, the output is
```
[
    "",
    "spec",
    "spec/ports"
]
```

`spec` is what covers that the keys under the spec object have changed: there's a new one, `test`, with value `rest`. It won't return `spec/test` because that doesn't make sense given `old`, there's no `test` key there.

**Comment by anderseknert** [comment]
Another issue for creating diffs between objects exists [here](https://github.com/open-policy-agent/opa/issues/1143), so I'll close this one in favor of that. Let me know if I missed anything and I'll add it to that ticket, or can re-open this one if requested.
