### ISSUE TITLE
Build to test capabilities does not work on v0.24.0

### ISSUE THREAD

**Issue by motionsuggests** [open-policy-agent/opa#2848]
## Expected Behavior
Using the examples here https://github.com/open-policy-agent/opa/releases/tag/v0.23.0 for testing capabilities should return errors.

## Actual Behavior
Running the example for testing capabilities via `opa build` in v0.24.0 does not return errors. 

**OPA version:** 
```
Version: 0.24.0
Build Commit: b69b80b
Build Timestamp: 2020-10-13T21:36:15Z
Build Hostname: ffabd2c9ce42
Go Version: go1.14.9
```
**OS:** macOS 10.15.6 

## Steps to Reproduce the Problem

1. install `opa` via `curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_darwin_amd64`
1. create a policy file 
```rego
package example

deny["missing semantic version"] {
  not valid_semantic_version_tag
}

valid_semantic_version_tag {
  semver.is_valid(input.version)
}
```
1. get the capabilities file from  `capabilities/v0.21.1.json`
1. run the command 
```
opa build ./policies/example.rego --capabilities ./capabilities/v0.21.1.json
```
1. no errors returned, no response

## Additional Info
I also tried installing using version number instead of latests
`curl -L -o opa https://openpolicyagent.org/downloads/v0.24.0/opa_darwin_amd64`

**Comment by tsandall** [comment]
Thanks for filing this. Looks like the bug was introduced in b535cbfde11445df658878af9e8290ed38b9b4ab. The issue is that the build command is looking at another sub-commands parameters: https://github.com/open-policy-agent/opa/commit/b535cbfde11445df658878af9e8290ed38b9b4ab#diff-5794c40aa4c9301aaf9c39eacf7d3c8511f2511cb24bdd95e0a08704ba583a5fR256-R257. It just slipped through code review.

**Comment by srenatus** [comment]
I've just been stumbling over this myself 😅 #2854 seems to do the trick indeed.
