### ISSUE TITLE
Ingress Validation Tutorial/OPA Implementation Fails on Kind 1.19 Cluster

### ISSUE THREAD

**Issue by ozhankaraman** [open-policy-agent/opa#2858]
Hi;
I try to setup https://www.openpolicyagent.org/docs/latest/kubernetes-tutorial/ over Kind 1.19.1 cluster but this tutorial fails with "tls: bad certificate error" on opa deployment pods. Error is below.

2020/11/03 14:52:25 http: TLS handshake error from 10.244.0.1:30902: remote error: tls: bad certificate
2020/11/03 14:52:27 http: TLS handshake error from 10.244.0.1:19395: remote error: tls: bad certificate

While same exact configuration/steps works with Kind version 1.16.15 cluster as expected. But somehow on 1.19.1 Kubernetes cluster it fails. I checked the tutorial it says OPA needs Kubernetes 1.13+. 

I am using OPA 0.24.0. Also for certificate creation steps i did not changed anything and Opa service name is exact same as mentioned on the tutorial and both clusters are new OPA testing clusters.

**Comment by tsandall** [comment]
The problem has to do with the certificate generation step in the tutorial. It's [fixed in master](https://github.com/open-policy-agent/opa/commit/2daeeccaaaaa01e384d27044c37066cbfc67fc40). See the edge version of the docs for the working command: https://www.openpolicyagent.org/docs/edge/kubernetes-tutorial/#3-deploy-opa-on-top-of-kubernetes
