### ISSUE TITLE
Add support for YAML encoded input documents

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#290]
Currently OPA supports YAML encoded input documents via the command line but not as inputs to queries. It would be nice to be able to POST YAML inputs. The server has two helper functions that read the input from the request: `readInputV0` and `readInputV1`. These functions should be extended to check the request header content-type (defaulting to `util.Unmarshal` if no header is supplied.)

**Comment by repenno** [comment]
I thought this would be useful and worked on a fix, but it turns out the changes needed are deeper than originally thought (although very doable). 

The code today is very much hardwired to JSON everywhere. For example, although my changes allow input documents in YAML, the response comes back in JSON, which I am sure is not what a potential client would expect. 

In order to send responses back in YAML (including explain, pretty, diag, etc) we would need to change v1DataPost() to either:

- Produce everything in YAML and we write to yaml to response.writer
- At the very end check if Content-Type is yaml and if yes, convert from JSON to yaml and write to response.writer
- Others?

thanks
