### ISSUE TITLE
add builtin: jsonpath

### ISSUE THREAD

**Issue by srenatus** [open-policy-agent/opa#2940]
For reporting violations in config files, it would be handy to be able to specify exactly **where** some offending setting is. While it generally depends on the file structure in question, it could be simplified by having a function that turns any ref into its [jsonpath](https://goessner.net/articles/JsonPath/) representation.

For example, this could be
```
jsonpath(input) == "input"
jsonpath(input.foo.bar.baz[1]) == "input.foo.bar.baz[1]" with input.foo.bar.baz as [1,2,3,4]
```

The `ast` methods for this should already be present: https://github.com/open-policy-agent/opa/blob/5c6c96331803c17158bc0a1b1b705cecef023ea1/ast/term.go#L1003-L1023

The tricky part might be to get to the `ast.Ref` from the `ast.Value` passed to the builtin. 🤔

**Comment by timothyhinrichs** [comment]
This wouldn't be a builtin however because it changes the evaluation semantics by stopping OPA from evaluating the argument before passing it to the builtin, which I see now is getting `ast.Ref` from `ast.Value`.

Intermediate variables cause trouble, if the idea is that you can pass in a value and gets its JSON-pointer out.  

```
input_container[container]
not trusted_image(container.image)
json_pointer(container.image).    // what does this return?
```

**Comment by tsandall** [comment]
I'm going to close this issue because as @timothyhinrichs mentioned it would be tricky to implement this as a normal built-in function. Also, we have #2935 which (IMO) would be more useful for users.
