### ISSUE TITLE
trace should support all objects

### ISSUE THREAD

**Issue by grosser** [open-policy-agent/opa#2957]
```rego
trace(obj)
```
fails with `rego_type_error: trace: invalid argument(s)` which is assnoying and then I have to know to type

```rego
trace(sprintf("%v", [bad]))
```

... please make it always do the `sprintf` by default

**Comment by srenatus** [comment]
Yeah I think I've been there more than once, too. 😄 Thanks for bringing this up.

**Comment by grosser** [comment]
@srenatus  can this issue be added to a "project" ? 
... since that seems to be the only thing that stale bot ignores

**Comment by srenatus** [comment]
The way the bot has been configured for now, staleness only means having a label applied. It will not auto-close the issue or anything. I think having an "inactive" label on this is accurate, since the discussion is pretty much inactive.

Furthermore, with the `print()` functionality that _accepts anything_, even undefined things, I wonder if there really is a need for this. 🤔 Is there?

**Comment by anderseknert** [comment]
@grosser have you tried the new print function, which works exactly like this? :)

The trace function can probably be considered deprecated at this point, at least for the purpose of printing variables and values.

**Comment by grosser** [comment]
yeah I guess that's good enough
I was afraid all my issues would be closed, just labeling them seems fine :)
