### ISSUE TITLE
SDK for another language other than go

### ISSUE THREAD

**Issue by t57root** [open-policy-agent/opa#2959]
I'm wondering if there're any solutions to use rego in other language other than go? Because using rego as a library should be more efficient than making HTTP requests to OPA.
Is rego API(https://godoc.org/github.com/open-policy-agent/opa/rego) safe to be exposed to another language using cgo?

Thanks

**Comment by srenatus** [comment]
What language(s) do you have in mind? I think rather than embedding the rego lib, it might be reasonable to build a WASM module from your policy code and use that from your host application?

There're SDKs for making this simpler:
- Node, https://github.com/open-policy-agent/npm-opa-wasm
- and Golang, https://github.com/open-policy-agent/golang-opa-wasm

(But I assume the Golang SDK is not help here 😅)

To your question,
> Is rego API(https://godoc.org/github.com/open-policy-agent/opa/rego) safe to be exposed to another language using cgo?

I don't know if anyone has done that before. _Maybe?_ 🤔 (I'd go with WASM. 😄)

**Comment by t57root** [comment]
@srenatus Thanks for the reply. I mainly focus on java, but supporting more languages is more wonderful. Speaking of
 WASM, it seems that java doesn't have much sophisticated sulutions to integrate with WASM. My final goal is to provide a general way for applications to do authorization in the corp: I'm responsible to distribute the policies as data, and the applications read and evaluate the distributed policies.

**Comment by tsandall** [comment]
@t57root thanks for sharing those extra details. If you need a short-term solution, we recommend running OPA as a separate process on the same host and communicating via HTTP. The latency budget for authz checks with this kind of deployment is ~1ms. If that's too high then OPA might not be a good fit unless you can find a way to integrate Wasm into the JVM. There are some projects emerging in that space but we haven't had time to build SDKs that leverage them. We don't have any near-term plans to implement SDKs in other languages _without_ leverage Wasm.
