### ISSUE TITLE
Unable to push policy using Policy API

### ISSUE THREAD

**Issue by deepuec** [open-policy-agent/opa#3118]
## Expected Behavior
Existing policy get replaced with one pushed to through API

## Actual Behavior
Getting Error message
```
{
    "code": "invalid_parameter",
    "message": "path opa/examples is owned by bundle \"bundle.tar.gz\""
}
```
## Steps to Reproduce the Problem
I was following steps mentioned in the [official document](https://www.openpolicyagent.org/docs/latest/rest-api/#create-or-update-a-policy) 
I created file auth.rego with the content mentioned in the example
Executed **opa build .** on the current folder path, it created bundle.tar.gz file
Executed **opa run -s -b bundle.tar.gz**
Opa server started listening on port 8181
Executed below cURL command and was expecting to get 200 status code, but instead got 400 Bad Request
curl --location --request PUT 'localhost:8181/v1/policies/example1' \
--header 'Content-Type: text/plain' \
--data-raw 'package opa.examples

import data.servers
import data.networks
import data.ports

public_servers[server] {
  some k, m
	server := servers[_]
	server.ports[_] == ports[k].id
	ports[k].networks[_] == networks[m].id
	networks[m].public == true
}'

* OPA version : 0.25.2 Windows 10

**Comment by anderseknert** [comment]
Hi @deepuec!

A policy which has been included in a bundle can't be overwritten by queries to the OPA REST API, since that policy is considered to be _owned_ by that bundle. You can still upload new policies via the REST API, but not on a path owned by a bundle. See the docs on [working with multiple sources of policy and data](https://www.openpolicyagent.org/docs/latest/management/#multiple-sources-of-policy-and-data) for more info.

**Comment by deepuec** [comment]
Thank you for confirming @anderseknert
