### ISSUE TITLE
Pull external data through memcache during policy evaluation

### ISSUE THREAD

**Issue by xia0pin9** [open-policy-agent/opa#3201]
It seems we can only pull external data through HTTP (`http.send`) for now. 

It will be great if we can also pull data through memcache, with a new interface like `result := memcache.get(request)`.

**Comment by anderseknert** [comment]
Supporting external datasources (like SQL, Redis, memcache, ...) directly via built-in functions is a request that comes up from time to time. The recommended way of doing this is to rather use the in-memory store in OPA for [external data](https://www.openpolicyagent.org/docs/latest/external-data/), or as you mentioned, via `http.send`. Another option is to provide a custom built-in function to do this by [extending OPA](https://www.openpolicyagent.org/docs/latest/extensions/). In the future, I'm hoping we'll be able to use Wasm as an alternative mechanism for [providing plug-ins](https://github.com/open-policy-agent/opa/issues/3631) as well, as that would allow plugins to be written in any language, and would work without having to build OPA.

Since there are no plans to extend OPA with more built-ins of this type, I'll close this for now. If there are compelling reasons for adding this later — which are not covered by the alternatives above — we could reconsider that.
