### ISSUE TITLE
How to use `opa eval --import` option

### ISSUE THREAD

**Issue by onelittlenightmusic** [open-policy-agent/opa#3228]
I am using `opa eval` for JSON filtering. 
I have two files.

`filter1.rego`

```rego
package f

getFamily(i) = { rtn |
  rtn := i.characters[_].family
}

getChildren(family) = { rtn |
  rtn := family[_].children
}
```

`data.json`

```json
{
  "characters": [
    {
      "id": 0,
      "name": "Marty McFly",
      "cast": "Michael J. Fox",
      "family": {
        "children": [
          "Marty McFly Jr.",
          "Marlene McFly"
        ]
      },
      "occupation": "student"
    }
  ]
}
```

The following command works well.
```
opa eval -I --format=pretty -d filter1.rego 'data.f.getChildren(data.f.getFamily(input))' < data.json 
[
  [
    "Marty McFly Jr.",
    "Marlene McFly"
  ]
]
```

I found `opa eval --import` option and it says `set query import(s)`.
I thought `--import` option could simplify a query. But it doesn't work.

## Expected Behavior

Run this command and get this result.

```
opa eval -I --format=pretty -d filter1.rego --import 'data.f' 'f.getChildren(f.getFamily(input))' < data.json
[
  [
    "Marty McFly Jr.",
    "Marlene McFly"
  ]
]
```

## Actual Behavior

```
opa eval -I --format=pretty -d filter1.rego --import 'data.f' 'f.getChildren(f.getFamily(input))' < data.json
2 errors occurred:
1:15: rego_type_error: undefined function f.getFamily
1:1: rego_type_error: undefined function f.getChildren
```

## Steps to Reproduce the Problem

Create two files `data.json` and `filter1.rego`.

Run this command.

```
opa eval -I --format=pretty -d filter1.rego --import 'data.f' 'f.getChildren(f.getFamily(input))' < data.json
```

* OPA version: 0.26.0

Thank you, the community!

**Comment by tsandall** [comment]
@onelittlenightmusic thank you for filing this issue!

It looks like there's a bug in OPA. The problem is that `--import` does not work unless `--package` is also given. You could set `--package` to anything and it would work.

The source of the problem is here: https://github.com/open-policy-agent/opa/blob/master/ast/compile.go#L1594. The imports for the query are only applied when the package is also supplied.

I think the query compiler ought to generate a package if one was not provided and one or more imports _were_ provided. The generated package name could even be an empty string to avoid conflicts (it doesn't have to be valid syntactically).

**Comment by onelittlenightmusic** [comment]
I appreciate your clarification and suggestion. As you mentioned,  I tried `--package` with random package name, and it was successful! Awesome!!
```
opa eval -I --format=pretty --package x -d filter1.rego --import 'data.f' 'f.getChildren(f.getFamily(input))' < data.json
[
  [
    "Marty McFly Jr.",
    "Marlene McFly"
  ]
]
```
 I adopted this remediation in my use case.

I would love your idea of automatic package generation. The possibility to omit `--package` will make `opa eval` more easier. I would like to think about contribution.
