### ISSUE TITLE
wasm: ordering issue in concat

### ISSUE THREAD

**Issue by srenatus** [open-policy-agent/opa#3252]
This is one we cannot fix by comparing using #3244...

```interactive
$ opa eval -t rego  'concat(",", { "3", "2", "1" })' --format=pretty
"1,2,3"

$ opa eval -t wasm  'concat(",", { "3", "2", "1" })' --format=pretty
"3,2,1"
```

**Comment by tsandall** [comment]
I think the issue here is that the set implementation does not retain the insertion order...so the iteration order is determined by the hash table. I don't think we want to guarantee that insertion order is used for iteration because it's harder to optimize #2569. Given this, I don't think we should treat this as a bug.

**Comment by srenatus** [comment]
Agreed. I suppose these are wasm/rego differences we'll have to live with.

**Comment by srenatus** [comment]
Anyone running into this should consider using an array instead. `concat` will accept both, and array iteration order is not implementation-dependent. (https://www.openpolicyagent.org/docs/latest/policy-reference/#strings)
