### ISSUE TITLE
Console loggers for status and decision log plugins still have hard dependency on logrus

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#3275]
When console logging is enabled (`status.console=true` or `decision_logs.console=true`) OPA should use the user-provided loggers not the hardcoded logrus loggers.

* In the decision logger: https://github.com/open-policy-agent/opa/blob/master/plugins/logs/plugin.go#L761
* In the status reporter: https://github.com/open-policy-agent/opa/blob/master/plugins/status/plugin.go#L320

The console logger is returned here: https://github.com/open-policy-agent/opa/blob/master/plugins/plugins.go#L174

Related: #3204

**Comment by anderseknert** [comment]
This was intentionally left out of #3204 as I don't believe the expected behavior is as clear cut in this case. For the original case we've basically had "import and use OPA as a library - things will start logging to console whether you want it or not" while in this case we have "import an use OPA library, have an end user _explicitly_ request that some events be printed to console, but ignore that". So while I don't disagree about doing this it was more of a delayed design decision than a bug ;)

**Comment by tsandall** [comment]
Ah, my bad. I didn't see the that decision mentioned in #3204 so I assumed it was an oversight. I think we should fix this but it's not high prio (so it's not in planned). Library users will probably want to control the logging library that's used as well as the fields that are included in those log messages (#3268).
