### ISSUE TITLE
wasm: opa build param changes for 0.27

### ISSUE THREAD

**Issue by christophwille** [open-policy-agent/opa#3291]
https://github.com/open-policy-agent/opa/blob/master/docs/content/wasm.md

I decided to to wait until .27.1 to see if I can make it work on my own, but I am still stuck at https://github.com/christophwille/dotnet-opa-wasm/issues/13#issuecomment-795866863

Ie the simple `opa build -t wasm -e example/allow example.rego` from the docs link doesn't work any more, at least on Windows. And on specifying a correct capabilities.json, I am totally lost. Is there somewhere a guidance that I am (obviously) missing?

**Comment by tsandall** [comment]
@christophwille sorry for the inconvenience!

In v0.27 we started versioning the wasm module ABI. Unfortunately, the check we have in the compiler was a bit too strict. We've since relaxed it. The fix will be rolled out in the next release in a couple weeks. Can you build from master in the mean time?

The same issue was raised and discussed here: https://github.com/open-policy-agent/opa/issues/3270

**Comment by christophwille** [comment]
I can wait for the next release

**Comment by tsandall** [comment]
Closing this issue as it's raised/fixed in #3270. The release will be out in the next day or so.
