### ISSUE TITLE
how to operate Object with rego？

### ISSUE THREAD

**Issue by andyyumiao** [open-policy-agent/opa#3335]
How to initialize an object? And how to incrementally add or modify the properties of the object? I want an effect like this：

```
person={}
person.name="xxx"
pserson.age=12323
```

**Comment by anderseknert** [comment]
That's a really old person! 😄  

Rego does not support mutation. You can however use one of the object "modifying" functions to return a new object with the specified modifications made.

```rego
p1 := {}
p2 := object.union(p1, {"name": "xxx"})
p3 := object.union(p2, {"age": 12323})
```

If you want a rule to [generate objects](https://www.openpolicyagent.org/docs/latest/policy-language/#generating-objects) (rather than scalar values or sets) you can do that too.

```rego
person["name"] = "xxx"
person["age"] = 12323
```

**Comment by andyyumiao** [comment]
> That's a really old person! 😄
> 
> Rego does not support mutation. You can however use one of the object "modifying" functions to return a new object with the specified modifications made.
> 
> ```rego
> p1 := {}
> p2 := object.union(p1, {"name": "xxx"})
> p3 := object.union(p2, {"age": 12323})
> ```
> 
> If you want a rule to [generate objects](https://www.openpolicyagent.org/docs/latest/policy-language/#generating-objects) (rather than scalar values or sets) you can do that too.
> 
> ```rego
> person["name"] = "xxx"
> person["age"] = 12323
> ```


@anderseknert 
Thank you very much.
