### ISSUE TITLE
Questions about wasm files generation 

### ISSUE THREAD

**Issue by junDD** [open-policy-agent/opa#3422]
Hi, we are using `opa build` to generate wasm files. It is partial evaluation (no data input)

When opa **0.16.1**, we generate wasm file for one rego policy file recursively. The command is 
`opa build -d /path/to/rego/file -o $target_file "data.$query_part = result"`
Example,
`opa build -d /rule/function1_directory/capability1.rego -o /wasm/function1_directory/capability1.wasm "data.function1_directory.can_search_something = result"`

We are struggling with the wasm file generation when trying to upgrade to the latest version (0.28.0). We tried two commands:
1. without bundle flag
`opa build -t wasm -e $wasm_file_path -o $target_file /path/to/rego/file`
The new wasm file is much larger than the one generated by 0.16.1. We then always encounter the magic number error
`[CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 1f 8b 08 00 @+0]`

2. with bundle flag
`opa build -b rules/ -t wasm -e wasm`
There is _only one_ policy.wasm file within that bundle with a copy of all rules and the same structure. 
The bundle structure
```
bundle
|-- data.json
|-- policy.wasm
|-- rules
    |-- function1_directory
    |   |-- can_search_something.rego
    |   |-- capability2.rego
    |-- function2_directory
    |   |- capability3.rego
    |   |- capability4.rego
    |   |- capability5.rego
    |-- function3_directory
    |   |- capability6.rego
    |   |- capability7.rego
    |   |- capability8.rego
```
I am confused about this wasm file.
1. Is this `policy.wasm` used for all rules/policies?
2. What does `entrypoint` mean? Does it mean the path to every rego policy file? If so, should I specify the different entrypoint for every repo file? like 
`opa build -b . -e rules/function1_directory/can_search_something -o can_search_something.tar.gz`

Context:
We run a script within a container to generate the wasm files. 
1. Rule File Structure
```
rule
|-- function1_directory
|   |-- can_search_something.rego
|   |-- capability2.rego
|-- function2_directory
|   |- capability3.rego
|   |- capability4.rego
|   |- capability5.rego
|-- function3_directory
|   |- capability6.rego
|   |- capability7.rego
|   |- capability8.rego

```
2. WASM File Structure (from 0.16.1)
```
wasm
|-- function1_directory
|   |-- can_search_something.wasm
|   |-- capability2.wasm
|-- function2_directory
|   |- capability3.wasm
|   |- capability4.wasm
|   |- capability5.wasm
|-- function3_directory
|   |- capability6.wasm
|   |- capability7.wasm
|   |- capability8.wasm
```
3. Rego File example
```
package function1_directory

default can_search_something = {"allowed": false, "rule": "disallowed by default"}

can_search_something = {"allowed": true, "rule": "by name"} {
	input.user.membership[_] == "allow_search_something"
}
```

**Comment by srenatus** [comment]
Heya. Thanks for writing this up -- I think I've found a spot where I must have been confusing you:

**`opa build` now only ever builds bundles**. Regardless of the flags. So, when you run `opa build -t wasm` it'll build **a bundle** that contains `/policy.wasm`. That bundle is a tarball, so you cannot run it as-is, hence the magic number error.

Passing `-b` to `opa build` makes it **interpret the directory passed** as an unpackaged bundle, so it's relevant for **how opa build consumes input**, not what it will output. It only ever outputs a bundle.

---
To your questions:

> 1. Is this policy.wasm used for all rules/policies?
> 2. What does entrypoint mean? Does it mean the path to every rego policy file? If so, should I specify the different entrypoint for every repo file? like
opa build -b . -e rules/function1_directory/can_search_something -o can_search_something.tar.gz

You can compile a single wasm module with multiple entrypoints. An entrypoint is a rule defined in the rego files you pass to `opa build`, [see the docs for a short example](https://www.openpolicyagent.org/docs/latest/wasm/#compiling-policies). 
If your rego files contain
```rego
package example

allow {
  # ...
}
```
and you build a wasm bundle with `opa build -t wasm -e example/allow example.rego`,
the evaluation of entrypoint 0 (the default) will return an object with a `result` key, its values are the evaluation of `data.example.allow`.

---

With your example code, I'd try the following:

```
opa build -t wasm -e function1_directory/can_search_something -e function1_directory/capability2 -e function1_directory/capability3
```
etc, and then see if the resulting wasm file is useful to you.

⚠️ You will have to adjust your code that's using the wasm file, since it'll have to select the proper entrypoint. It would need to call the `entrypoints()` export to figure out the mapping of entrypoints to IDs, and it'll have to call `opa_eval_ctx_set_entrypoint` to select an entrypoint for evaluation. See [exports](https://www.openpolicyagent.org/docs/latest/wasm/#exports).

How are you consuming the wasm modules? Should you be using the npm-opa-wasm, multiple entrypoint support is WIP.

You could still build one wasm file per query if this is a problem. Anyway, I'd expect the combined wasm file to be much smaller than the separate ones, as the combined one will share most of the code supporting policy decisions. But I'm curious what you find out there!

**Comment by junDD** [comment]
Thanks for the detailed explanation.
Yeah, we created one wasm file per one rego file for legacy reasons. 
Is it true that only one wasm file is needed for all rego policies? Does it also mean that the code needs to update to load policy from the right entrypoint?

**Comment by srenatus** [comment]
> Is it true that only one wasm file is needed for all rego policies?

✔️ Both things are possible, but you could compile all your policies into a single wasm module, and serve them from one and the same VM instance.

> Does it also mean that the code needs to update to load policy from the right entrypoint?

✔️ Yes. Thanks to https://github.com/open-policy-agent/npm-opa-wasm/commit/df208fefdabd802f030011566736e9453ad7059b, there's an optional second argument to `policy.evaluate()`, which is the entrypoint, selected by name or ID.

**Comment by srenatus** [comment]
Have your questions been addressed so far?  I suppose we could close this and go with another issue if you encounter problems down this road...

**Comment by anderseknert** [comment]
Closing since the questions have been answered. If I missed anything, let me know and I'll re-open, @junDD.
