### ISSUE TITLE
OPA policy performance question

### ISSUE THREAD

**Issue by kyle-burnette** [open-policy-agent/opa#3427]
Not an issue but a question. Pl bear with my ignorance. 

I wanted to get some basics clear on some of the metrics reported by opa eval and open bench commands. 

**opa eval output:**

1. Are the numbers in the first table <Metric, Value> one time costs? Particularly the timer_rego_query_eval_ns and timer_rego_query_parse_ns metrics?
2. May be redundant q but in the next table <Time, Num Eval, Num Redo, Location> in the attached sample policy file & corresponding profile output does the "data.stresstest.authz.allow" number (198.617 uS) mean it took that much time (once) to evaluate the "allow"? 
3. Reason I ask is the numbers against line 10, 19 look real small which I would have expected to be most intensive since they involve external data look ups (depending on the size of the data).
 

**opa bench output:**

1. Do the ns/op mean on an avg it takes xx nano seconds per operation (evaluating allow in my policy?)
2. If the ns/op represents average eval time then what does 'histogram_timer_rego_query_eval_ns_mean' represent? It does appear to be different but not clear. 
3. How does it generate the samples? And what are the samples - of data or something else? I did provide a data file along with the policy file when running bench. 
4. Sorry I hate asking this kind of questions but which of the numbers gives a good indicator of the policy's overall performance? 

Other related q:
In a deployed OPA instance what is the best way to get some performance numbers? Do the "resp_duration" in the log provide how it long it to process the request? I understand it is a bit coarse. Are there any other metrics than can be obtained and how? 
 
rgds
KB

[stp.rego.txt](https://github.com/open-policy-agent/opa/files/6406554/stp.rego.txt)
[opa-profile-output.txt](https://github.com/open-policy-agent/opa/files/6406557/opa-profile-output.txt)

**Comment by tsandall** [comment]
Everything in the table below is one-time except `timer_rego_query_eval_ns` which is the time it took the policy engine evaluate the policy query. In theory, everything else can be cached. The OPA HTTP server will cache everything it can. This is evident if you just start OPA and run two queries back to back:

Start OPA:

```
opa run -s
```

Run two queries back to back.

```
torin:~$ curl 'localhost:8181/v1/data?metrics&pretty'
{
  "metrics": {
    "counter_server_query_cache_hit": 0,
    "timer_rego_external_resolve_ns": 200,
    "timer_rego_input_parse_ns": 400,
    "timer_rego_query_compile_ns": 53100,
    "timer_rego_query_eval_ns": 12700,
    "timer_rego_query_parse_ns": 11200,
    "timer_server_handler_ns": 141400
  },
  "result": {}
}
torin:~$ curl 'localhost:8181/v1/data?metrics&pretty'
{
  "metrics": {
    "counter_server_query_cache_hit": 1,
    "timer_rego_external_resolve_ns": 200,
    "timer_rego_input_parse_ns": 400,
    "timer_rego_query_eval_ns": 40900,
    "timer_server_handler_ns": 92000
  },
  "result": {}
}
```

```
false
+------------------------------+-----------+
|            METRIC            |   VALUE   |
+------------------------------+-----------+
| timer_rego_data_parse_ns     | 206030661 |
| timer_rego_load_files_ns     | 634758158 |
| timer_rego_module_compile_ns | 1439327   |
| timer_rego_module_parse_ns   | 1456429   |
| timer_rego_query_compile_ns  | 168914    |
| timer_rego_query_eval_ns     | 363632    |
| timer_rego_query_parse_ns    | 12701     |
+------------------------------+-----------+
+-----------+----------+----------+-----------------------------+
|   TIME    | NUM EVAL | NUM REDO |          LOCATION           |
+-----------+----------+----------+-----------------------------+
| 198.617µs | 1        | 1        | data.stresstest.authz.allow |
| 152.014µs | 1        | 1        | stress-test-policy.rego:3   |
| 12.802µs  | 1        | 0        | stress-test-policy.rego:10  |
| 3.9µs     | 1        | 0        | stress-test-policy.rego:19  |
+-----------+----------+----------+-----------------------------+
```

To answer your other questions:

* The profiler tells you how much time (approx) was spent on each line. The first line in that table is the query. Since the expression was only evaluated once, yes, that was the time it took evaluate. Note, the profiler introduces it's own overhead (because it's keeping track of how long things take, so it's not particularly useful for micro-optimizations.) It's primarily useful to identifying hotspots in the policy where you have some large amount of iteration/search occurring (perhaps unexpectedly.)

* Those data lookups are happening in memory so they can be fast. The cost will come from having to iterate over those collections which look like arrays. Note, depending on the input you specified, those could essentially be no-ops. The request was denied which makes me wonder if you specified input.enterprise or input.user values? If you didn't then those values would be undefined and the evaluator wouldn't even bother evaluating lines 15 and 24 (which is what will actually get expensive) since the rule indexer would notice they couldn't possibly match.

* Yes, ns/op is the average. It's the total time spent evaluating (ns) over the number of times executed (op).

* The query timer (`rego_eval_query`) is maintained at within the interpreter whereas the `ns/op` value is what the caller is observing. There is some overhead associated with passing through to the interpreter. In practice, this has not been a problem.

* samples is the number of times the times executed (op). We're piggy backing on the go benchmark framework here.

* the `ns/op` number is good because it includes the overhead of calling into OPA from within Go. Of course if you're calling OPA via HTTP then there will be additional overhead.

* OPA exposes per-decision metrics in the decision log. If you want to monitor OPA, /metrics exposes a Prometheus endpoint. The resp_duration value in the access log is fine, it's a bit coarse like you said, but it's a good measurement of the entire HTTP server handler.

**Comment by tsandall** [comment]
@anderseknert I think this issue is good fodder for some docs improvements. I could imagine updating the [Monitoring](https://www.openpolicyagent.org/docs/latest/monitoring/) page with a list of those metrics and their meanings so we can point to them in future...

**Comment by kyle-burnette** [comment]
Pardon the delayed response. 

Thanks - that was helpful. No I had not run with any input values. My miss - had not looked at the sample policy closely  on the opa eval / profile doc page to realize it had inputs specified in it; so did not know to specify inputs when profiling.  Will run again with some inputs to check. 

This question can be closed. 

thanks
KB
