### ISSUE TITLE
Skip policies with the same name

### ISSUE THREAD

**Issue by kotyara85** [open-policy-agent/opa#3428]
Hello,
Is there a way to skip some of the policies if match occurred?
Let’s say I have these policies 

```
Item {
# some logic
}

Item {
# some other logic
}
```

is there a way to set a variable to skip second item if first matched?
Thank you

**Comment by anderseknert** [comment]
Yes, you could use `else` to achieve that:

```rego
item {
    # some logic
} else {
   # will only be evaluated if "some logic" is false/undefined
}
```

**Comment by tsandall** [comment]
@kotyara85 why are you trying have the second item skipped? In that example, the result will be the same since both are simply assigning true to item. Perhaps you're thinking about performance? If the [rule indexer](https://www.openpolicyagent.org/docs/latest/policy-performance/#use-indexed-statements) is able to understand the rules though, the second item would never be executed if it could not possibly match.

Use of `else` makes sense in some cases when you actually need ordering, however, it's often misused.

**Comment by kotyara85** [comment]
@tsandall because glob is expensive

**Comment by anderseknert** [comment]
@kotyara85 anything still unanswered, or should we close the issue?

**Comment by anderseknert** [comment]
Closing as answered and can reopen if needed.
