### ISSUE TITLE
Question: Partially evaluating partially unknown objects

### ISSUE THREAD

**Issue by jkbschmid** [open-policy-agent/opa#3478]
Hi everyone,

I noticed interesting behaviour during partial evaluation with a variable that is assigned a partially unknown object. 
I have the following rules that implement the same check:
```
package test
allow0 {
    user := input.user
    "admin" == user.role
}

allow1 {
    "admin" == input.user.role
}
```

## Expected Behavior
When doing partial evaluation with input `{"user":{"role":"admin"}}` and Unknowns `input.user.name`, I would expect, that OPA is able to resolve this indirect assignment and that `allow0=allow1=true`.  

## Actual Behavior

```
$ opa eval -d res/ActionResourceMapping.rego 'data.test.allow0' -p  -f pretty -i input.json -u "input.user.name" --explain=full
query:1                              Enter data.test.allow0
query:1                              | Eval data.test.allow0
query:1                              | Index data.test.allow0 (matched 1 rule)
res/ActionResourceMapping.rego:3     | Enter data.test.allow0
res/ActionResourceMapping.rego:4     | | Eval user = input.user
res/ActionResourceMapping.rego:4     | | Save user = input.user
res/ActionResourceMapping.rego:5     | | Eval "admin" = user.role
res/ActionResourceMapping.rego:5     | | Save "admin" = user.role
res/ActionResourceMapping.rego:3     | | Exit data.test.allow0
query:1                              | Exit data.test.allow0
query:1                              Redo data.test.allow0
query:1                              | Redo data.test.allow0
res/ActionResourceMapping.rego:3     | Redo data.test.allow0
res/ActionResourceMapping.rego:5     | | Redo "admin" = user.role
res/ActionResourceMapping.rego:4     | | Redo user = input.user
+---------+---------------------------+
| Query 1 | "admin" = input.user.role |
+---------+---------------------------+
```

OPA current main (0.28.0)

## Question

The reason for this is that `action` is added to the safeSet (i.e. marked as unknown), although only a subset of `action` is unknown (See https://github.com/open-policy-agent/opa/blame/280d3be2dae2a700fbf2d9e1e5c89ee9a3c42bc5/topdown/save.go#L149).

Is this just something that's not implemented yet? Or is it generally not possible, e.g. due to safety reasons when calling `func(user)`?
I would love to understand this better.
Thanks and kind regards!

**Comment by tsandall** [comment]
> Is this just something that's not implemented yet? Or is it generally not possible, e.g. due to safety reasons when calling func(user)?

We could try to make the implementation more intelligent when it comes to marking unknowns (e.g., only mark `user.name` as unknown instead of all of `user`).

I'm not sure exactly what changes would be required for this. [L776-L800 in topdown/eval.go](https://github.com/open-policy-agent/opa/blob/main/topdown/eval.go#L776-L800) are where the save decision for `var = ref` expressions is made. Currently, if the save set contains either term, then the expression is saved and variables contained in the expression are added to the save set.

The changes we would want to make are as follows:

* The expression `user = input.user` should not be saved OR the saved expression should be discarded before returning.
* The `user` variable should not be added to the save set, instead the reference `user.name` should be added.

Determining whether to save `user = input.user` would require analyzing subsequent expressions to see if they depend on an unknown. If they do not, then `user` can be bound to the value of `input.user` and evaluation can proceed. Within a single query/rule body, this would be cheap, however, it would be get more complicated if we wanted to reason across rules. We could treat that as a future improvement.

OTOH, we could try to discard the saved expression by checking whether it has any effect on the result... as long as we know that `input.user` was defined, it would not.

I think that this decision about how to handle saving (or discarding) of the unification expression is the key bit here.  Marking `user.name` as unknown by adding it to the save set seems relatively simple. We need to think about the saving/discarding more.

**Comment by jkbschmid** [comment]
Thanks for the detailed answer, @tsandall, definitely learned something.
Seems like changing OPA's behaviour in this case brings quite some complexity. Perhaps avoiding code snippets as in the example is also a good solution.

**Comment by srenatus** [comment]
"Completed" didn't seem accurate.
