### ISSUE TITLE
Clarify -b option of opa build command

### ISSUE THREAD

**Issue by dsoguet** [open-policy-agent/opa#3480]
## Expected Behavior

The behavior when -b option is used or not should be clarified.

Actually `opa build -h` explains the following

```
The 'build' command packages OPA policy and data files into bundles. Bundles are
gzipped tarballs containing policies and data. Paths referring to directories are
loaded recursively.
```
and

```
When -b is specified the 'build' command assumes paths refer to existing bundle files
or directories following the bundle structure. If multiple bundles are provided, their
contents are merged. If there are any merge conflicts (e.g., due to conflicting bundle
roots), the command fails.
```

When -b option is not set, what is assumed by opa build ?
In practice is -b is really an option ? In which case it should not be activated ?

## Actual Behavior

Running `opa build -b <some_dir> --revision <some_revision>` or `opa build <some_dir> --revision <some_revision>` seems quite similar.
The difference detected is that with -b option the roots flags content of <some_dir>/.manifest is kept into the bundle generated. Without -b option the roots flags is empty into the bundle generated.

## Steps to Reproduce the Problem

* OPA version 0.27.1

Following file can be used to bootstrap a project [SignatureAndPersistBug.tar.gz](https://github.com/open-policy-agent/opa/files/6521240/SignatureAndPersistBug.tar.gz)

Inside the directory obtained run following commands
```
opa build -b . --revision 1.0
tar -tzvf bundle.tar.gz
tar -axf bundle.tar.gz /.manifest -O
opa build . --revision 1.0
tar -tzvf bundle.tar.gz
tar -axf bundle.tar.gz /.manifest -O
```
See that the content of .manifest differs, but the content of other files are the same

## Additional Info

Current issue is related to the work done for issue https://github.com/open-policy-agent/opa/issues/3472
Globally the idea behind those issues is "how a bundle should be generated and what is its content"

**Comment by anderseknert** [comment]
Thanks for reporting this @dsoguet 👍 The different treatment of .manifest has bitten me too in the past, having a provided .manifest file silently overwritten since I did not provide the `--bundle` flag. This is unlikely to be detected until possibly much later, which is IMO the worst kind of surprise. If current behavior is kept I think we'd at least need to emit a warning when provided files are discarded, but I'm not sure we should discard provided files at all. If the user wouldn't want them, why would they provide them?

**Comment by dsoguet** [comment]
@anderseknert, from my point of view

If backward compatibility must be managed then raise a warning because the .manifest is going to be overwritten is a good solution. This warning should invite the user to use the -b option.

If backward compatibility is not a problem, then -b option should be totally deleted and become the normal behavior of the script

In fact I don't see in which case not using -b is useful. Note that without -b option, if a project contains or not a .manifest, the result is the same into the bundle generated

**Comment by tsandall** [comment]
Closing the loop on this.

I chatted offline with @anderseknert and we came to the conclusion that simply skipping the .manifest file write would be best.

This way `opa build` will behave as follows:

```
# default manifest content so .manifest not written
opa build file1 file2 dir1

# non-default manifest content (because revision specified) so .manifest written
opa build --revision "xyz" file1 file 2 dir2

# bundle loading enabled so if dir1 contains a .manifest file it will be used
opa build -b dir1 
```

In future we can extend `opa build` to support other flags like `--revision` so that users can set roots, metadata, and other future fields. Similarly we could support an explicit `--manifest` flag as well.

PR incoming for the "do not write empty manifest" behaviour.
