### ISSUE TITLE
Dependency gogo/protobuf uses previous version with high security risk

### ISSUE THREAD

**Issue by resullar-vince** [open-policy-agent/opa#3542]
## Expected Version

Dependency gogo/protobuf must be in version 1.3.2 since previous versions have a security issue detailed in this link: https://nvd.nist.gov/vuln/detail/CVE-2021-3121

Right now, it's flagging in our Black Duck scan with high security risk. Can we get this updated to the latest version please?

## Actual Version
Current gogo/protobuf dependencies are 1.3.1 and below (latest release v0.29.4):
![image](https://user-images.githubusercontent.com/54968960/121309892-1446a580-c946-11eb-864c-484aad1c1ced.png)

## Additional Info

OPA Version used: latest (v.0.29.4)

**Comment by ashutosh-narkar** [comment]
A quick scan of the dependencies and updating the `github.com/prometheus/client_golang` library seemed to remove some of the older versions of `github.com/gogo/protobuf`. I'm  probably missing a much easier way of resolving this.

**Comment by resullar-vince** [comment]
I tried doing it but it still referencing to gogo/protobuf version 1.3.1. The compliant version is 1.3.2 though.

**Comment by srenatus** [comment]
There's a bunch of cyclic dependencies between prometheus/client_golang and prometheus/common, and the latter eventually drags in a dependency on gogo/protobuf v1.1.1.

However, see https://github.com/prometheus/client_golang/issues/836 -- the issue is two-fold:

1. The dependency in `go.sum` has no consequence for the security stance of this project (or of prometheus/client_golang, for that matter)
2. Even if it wasn't there, you wouldn't know if this code base was safe from the security vulnerability in gogo/protobuf, since it's manifest in *generated code*. If code was generated or not (and with a vulnerable code generator or not) **cannot be seen** from the `go.sum` data.

That said, I'll go have a look and try to manually find the answer to (2.). I believe it's _no_, but I'll double-check.

**Comment by srenatus** [comment]
Looking at the change in `github.com/gogo/protobuf`, we find that:

1. You cannot tell which version of protoc-gen-gogo a file was built with.
2. You **can tell** if the protoc-gen-gogo code generated was used at all, from the first line of the generated file.

Checking our `vendor` directory based on that, however, yields nothing:
```
$ git co main
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
$ git grep "protoc-gen-gogo"
$
```

See also [this github search](https://github.com/open-policy-agent/opa/search?q=%22Code+generated+by+protoc-gen-gogo.%22).

**Comment by srenatus** [comment]
I'd opt for closing this. I'd try to fix the problem in your scanner, since flagging this project is a false positive. What do you think?

**Comment by resullar-vince** [comment]
Let me get back to you after doing some tests on our end.

**Comment by srenatus** [comment]
Hey there. Any news from your side?

**Comment by resullar-vince** [comment]
Sorry for the late response. I think so far it's all good. so we can close this one. thanks!
