### ISSUE TITLE
sdk: Allow client to set labels for decision logging

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#3590]
When porting the [opa-docker-authz](https://github.com/open-policy-agent/opa-docker-authz) plugin to use the SDK, one thing I find missing from setting up the client the old way is that I can no longer add arbitrary labels to be used in decision logs. While these can (and will) be sourced from a provided config file, there's still a point in allowing the client to add theirs independently of that, possibly based on values sourced from code.

Example:

```go
	labels := map[string]string{
		"app":            "opa-docker-authz",
		"id":             p.instanceID,
		"opa_version":    version_pkg.OPAVersion,
		"plugin_version": version_pkg.Version,
	}
```

I suggest the `sdk.DecisionOptions` struct is extended with a `Labels` field to allow for this.

**Comment by tsandall** [comment]
After some offline discussion we've decided to close this. Since labels are intended to identify the OPA instance, setting them per-decision seems unnecessary. For the time being, users can inject labels into the config bytes supplied to the SDK. We could look at adding a specific API for programmatically setting labels but then we'd have to accommodate different overriding behaviours. For the time being, it's simpler to close this and revisit as needed.
