### ISSUE TITLE
Add "allOf", "anyOf" support to JSON schema parsing for the type checker

### ISSUE THREAD

**Issue by aavarghese** [open-policy-agent/opa#3592]
Today, OPA's type checking with JSON schemas does not support some of the commonly used features like :

- [ ] [allOf](https://json-schema.org/understanding-json-schema/reference/combining.html#allof)
- [x] [anyOf](https://json-schema.org/understanding-json-schema/reference/combining.html#anyof)

Opening this issue to help track/discuss this enhancement work currently in-progress to use this additional schema info when JSON schema specifies it.

cc: @tsandall @vazirim @juliafriedman8 @jchen10500

**Comment by juliafriedman8** [comment]
My basic logic for the implementation of the AllOf functionality for JSON schema validation is to merge the types from all of the JSON subSchemas listed under AllOf before parsing it to convert it to a Rego type. Merging of JSON subSchemas essentially combines the passed in subSchemas based on what type they are. The only subSchemas that are actually able to be merged will be those of the same type (all schemas of type object or all schemas are of type array, for example), so that condition is checked before merging. The subSchemas are merged by unionizing their properties (in the case of an object type) or items (in the case of an array type) and creating a new subSchema that is subsequently parsed to obtain a Rego type. @tsandall

**Comment by tsandall** [comment]
Unioning the object properties/array items fields seems reasonable.

I'm curious where allOf is being used in the wild in JSON schemas today. @aavarghese or @juliafriedman8 do you have some examples?

Also, @aavarghese, re: anyOf; that should be covered by the `types.Any` implementation today (i.e., you can restrict the any to specific types...)

**Comment by aavarghese** [comment]
@tsandall We've seen quite some usage of `allOf`, `oneOf`, `anyOf` in the Kubernetes published json schemas, for example https://github.com/instrumenta/kubernetes-json-schema and internal mentions of it being 'a nice to have' support. Other than that, no concrete examples.

re: anyOf. Sounds good - we're using `types.Any` for anyOf. 

Thank you!

**Comment by srenatus** [comment]
Oops I didn't mean to close this. anyOf is deal with, allOf is still a TODO.
