### ISSUE TITLE
Why does  not support  Mysql, redis, or others storage ?

### ISSUE THREAD

**Issue by yaobo-lab** [open-policy-agent/opa#3734]
Why  don't  support  Mysql, redis, or others storage ?

**Comment by tsandall** [comment]
@yaobo-lab the short answer is that like everything else, there are tradeoffs. One of the goals of the project is to enable distributed policy enforcement. This means that OPA is not necessarily deployed as a centralized service; it's deployed at the edge, next to whatever piece of software requires policy decision-making. Because of this, OPA has to be able to serve policy decisions without depending on an external database--therefore, OPA stores all of the policy and data required for decision-making, in-memory. This has benefits for performance and availability. Moreover, we try to keep OPA as lightweight as possible. Adding in-built support for various databases has some benefits (e.g., convenience) but it also introduces bloat and makes it harder to embed. In short, it just hasn't been a high-priority, yet.

That said, you can recompile OPA with custom built-in functions that can fetch data from external sources: https://www.openpolicyagent.org/docs/latest/extensions/#custom-built-in-functions-in-go.

We're also working on support for disk-based storage ([issue](#3231)) that will pave the way for other storage layers within OPA.

**Comment by yaobo-lab** [comment]
If the policy data is enough big, how to deal with?

**Comment by haijianyang** [comment]
> If the policy data is enough big, how to deal with?

You can try this https://www.openpolicyagent.org/docs/latest/external-data/#option-5-pull-data-during-evaluation

**Comment by anderseknert** [comment]
Closing as answered.
