### ISSUE TITLE
Proposal: More flexible healthcheck behavior

### ISSUE THREAD

**Issue by gshively11** [open-policy-agent/opa#3759]
Let's consider this use case:

We want to co-locate opa with our app running in a kub pod (sidecar), such that they share the same fate.  We want to perform healthchecks against both our app and the opa server, so that kub is able to orchestrate them properly.  We don't want to send traffic to our app/opa until opa is fully initialized, including bundles and plugins.  Up to this point, the `/health` route works great.

Here's where it gets trickier.  In some custom plugins (and honestly, in the native ones as well), we would like to use `StateWarn` to indicate that the plugin is encountering a problem, so that it's visible in the status logs.  But we don't want a plugin issue to bring down opa, and by association, our app (e.g. our log ingest is down, we don't want this to bring down opa/app). Or maybe in same cases we do, and there's a `StateFatal` or something to handle that.

I'm not sure if this is the best way to handle it, but maybe adding some configureable logic to health route such that:

- during init, the opa healthcheck should fail until all bundles and plugins are fully initialized.
- once init is complete (the healthcheck passes for the first time), a flag is set, at which point some/all (configureable?) bundles and plugins should be ignored by the healthcheck
- maybe introducing a `StateFatal` or something like that for conditions in which plugin failures _should_ cause the healthcheck to fail

Thoughts?

**Comment by tsandall** [comment]
I'm wondering if we should just let users write some special policy under `system` to determine whether the OPA is operational...

```
package system.health

# generates true if the OPA is alive
live {
}

# generates true if the OPA is ready
ready {
}
```

The k8s readiness and liveness probes could be configured to query /health/ready and /health/live respectively. Internally, OPA could evaluate those special policies to generate the response. The policies could be evaluated with the status and configuration as `input`. WDYT?

**Comment by gshively11** [comment]
Oooo, I like that.  That should work for our use case.  I can take a crack at it in a bit.

**Comment by itayhac** [comment]
Hi  Team @gshively11 @srenatus 

I am working on implementing custom health checks in Open Policy Agent following the [Custom Health Checks documentation](https://www.openpolicyagent.org/docs/rest-api#custom-health-checks).

While the endpoints /health/live and /health/ready route correctly to my policy, I am encountering two issues:

1. The expected input context (e.g., input.plugins_ready, input.plugin_state) is missing or undefined during evaluation.

2. Document/data store state (data...) does not seem accessible within the system.health package context.

**Context & Goals**
Our main objective is to reduce the blast radius of bundle synchronization failures. Currently, a single corrupted or unreachable bundle can fail the readiness check and disrupt the entire instance.

We are trying to construct a /health/ready check that evaluates:

1. Data Accessibility: Validates that key data paths (e.g., data.my_bundle) are fully loaded and queryable.

2. Threshold-Based Health: Marks the bundle plugin as ready as long as the number of degraded/failed bundles remains below a threshold $X$, rather than requiring $100\%$ compliance.

**Code Snippet**

```
package system.health

default live := true

default ready := false

ready if {
    input.plugins_ready
    input.plugin_state.bundle == "OK"
}
```

as suggested in the custom-health-checks section, i would like to further extend it to support data access and bundle status. 


**Questions**
1. Debug / Configuration: Is there a specific configuration or feature flag required to expose input and data storage to the system.health package?

2. Implementation Strategy: What is the recommended way to achieve this objective?
Should we build a custom OPA plugin in Go (using OPA as a SDK library to register a custom HTTP handler and query internal bundle managers/storage directly)?
Or can this be reliably handled natively using a Rego custom health check?

Thanks in advance for any insights!
