### ISSUE TITLE
Bundle persist feature working differently than bundles loaded from elsewhere

### ISSUE THREAD

**Issue by dsoguet** [open-policy-agent/opa#3840]
## Expected Behavior

Running ``opa run --server --config-file conf/config.yaml`` with persist feature activated or not into conf/config.yaml should be equivalent

## Actual Behavior

With the MWE provided below : 
- when persist feature is not set ``opa run --server --config-file conf/config.yaml`` always works
- when persist feature is set ``opa run --server --config-file conf/config.yaml`` sometimes works, sometimes crashes

## Steps to Reproduce the Problem

* OPA version : 0.31.0
* Following two bundles files and configuration file are necessary to reproduce the problem:
    - [opa_bundle_lib.tar.gz](https://github.com/open-policy-agent/opa/files/7259648/opa_bundle_lib.tar.gz)
    - [opa_main_project.tar.gz](https://github.com/open-policy-agent/opa/files/7259649/opa_main_project.tar.gz)
    - [config.txt](https://github.com/open-policy-agent/opa/files/7259689/config.txt)

opa_bundle_lib.tar.gz contains:
- some data
- a function
- a rule

opa_main_project.tar.gz uses opa_bundle_lib.tar.gz:
- to create a rule based on opa_bundle_lib.tar.gz data
- to create a rule based on opa_bundle_lib.tar.gz function
- to create a rule based on opa_bundle_lib.tar.gz rule

config.txt (yaml not a file format supported by github...) is a configuration file to run a OPA server using the two bundles above

**Steps to reproduce:**
- Run following commands to prepare the test environment
```
mkdir -p ~/MyTest/bundle
mkdir -p ~/MyTest/conf
cd ~/MyTest
```
- Copy into ~/MyTest/bundle the two bundles file provided above
- Copy into ~/MyTest/conf the config.txt file provided above and rename it config.yaml
- Into another terminal run following command to simulate a bundle web server
```
cd ~/MyTest
python3 -m http.server 8080
```
- Into the initial terminal run several times (maybe around 20 times) following command
```
opa run --server --config-file conf/config.yaml
```
Sometimes OPA will work, sometimes OPA will crash with an exit code 1 (``echo $?``)

- Edit conf/config.yaml and comment with # the two lines ``persist: true``
- Into the initial terminal run several times (maybe around 20 times) following command
```
opa run --server --config-file conf/config.yaml
```
This time OPA will always work

## Additional Info

Another way to reproduce the problem

-  rm persisted bundles ``rm -rf .opa/bundles/*``
- comment all the block about ``opa_bundle_lib.tar.gz`` into the configuration file
- run OPA ``opa run --server --config-file conf/config.yaml``
OPA complains about missing function but does not crash
- Stop OPA
- Put back ``opa_bundle_lib.tar.gz`` block into the configuration file
- Run OPA ``opa run --server --config-file conf/config.yaml``
and wait the download of all bundles (to have them persisted)
- Comment again  the block about ``opa_bundle_lib.tar.gz`` into the configuration file
- Run OPA ``opa run --server --config-file conf/config.yaml``
OPA complains about missing function and it crashes

**Comment by ashutosh-narkar** [comment]
The issue here is that when OPA tries to load a bundle from disk and if that bundle depends on some other which hasn't yet been loaded, the original bundle will fail activation and OPA runtime will exit. So the order in which the bundles are loaded from disk leads to the activation failure. 

Activation failure would still have happened if OPA has downloaded the bundle from the remote server but it would get resolved in the successive download attempts following the activation of the bundle containing the packages being imported. We could use a similar strategy for the persisted bundles where we keep trying till all the bundles are activated. 

The problem with this approach is if the bundle containing the dependencies is not persisted and the bundle importing those dependencies is. In this case OPA will keep trying to activate the bundle without success. One can make the argument that the user should ensure that both those bundles should have been configured with `persist: true` but misconfigurations happen. Other option is to make bundle activation from persisted bundles best effort. That is OPA tries to activate persisted bundles (overcoming the bundle order issue) but does so with a time-bound or max retry count fashion. If this still fails, we update the status but don't exit the program.

Thoughts @tsandall @anderseknert ?

**Comment by anderseknert** [comment]
> One can make the argument that the user should ensure that both those bundles should have been configured with persist: true but misconfigurations happen.

Sounds like the easy fix is to make this misconfiguration an error with an explanation if so.  Since multiple bundles is uncommon and not really encouraged, I think this would be fine. It's still much better than hard crashing at "runtime".

**Comment by ashutosh-narkar** [comment]
| Sounds like the easy fix is to make this misconfiguration an error with an explanation if so.

I think the problem with this is we would have to know how the bundles depend on each other. Currently we simply try to activate a bundle w/o having to know if it depends on something else. Unless we say that all or none of the bundles in the configuration must be persisted but not sure if that's the right thing to do.  I'm leaning towards the best effort approach. You're right OPA should not crash whatever approach we take.
