### ISSUE TITLE
Ability to fetch bundles from Azure storage account using managed identities

### ISSUE THREAD

**Issue by wma1729** [open-policy-agent/opa#3916]
## Expected Behavior

OPA can fetch bundles from Azure Storage Account using `service principal`. This works very well. However, I want to deploy OPA container as a sidecar in AKS cluster where the pod is assigned a managed identity. The storage account allows read access to this managed identity. I could not find any way to use managed identity to fetch the bundle. So I used `services[].<service-name>.credential.bearer.token_path`. A process runs in the background that fetches the bearer token using the following curl command and persists it to a file that is specified in `services[].<service-name>.credential.bearer.token_path`:

```
curl --silent --get \
       --header Metadata:true \
       --data 'api-version=2018-02-01' \
       --data 'resource=https://storage.azure.com/' \
       'http://169.254.169.254/metadata/identity/oauth2/token' | jq -r .access_token
```

The problem with this approach is that I cannot use opa container. I have to write my own container that runs the script in background to periodically update the access token.

## Actual Behavior

I think it would be nice if there is a config option `services[].<service-name>.credentials.bearer.azure.use_system_assigned_identity = true`. OPA on seeing this will fetch the access token and use it for `Bearer` authentication.

## Additional Info

169.254.169.254 is the IP address for Azure Instance Metadata Service.
https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service?tabs=windows
The curl command above is from the page:
https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#get-a-token-using-curl

**Comment by Scowluga** [comment]
I'd like to take a look at this. I have some knowledge of OPA but have never contributed. May need a bit of help getting started!

**Comment by anderseknert** [comment]
Hi @Scowluga! And thanks for helping out! 👍 Yes, both the AWS and GCP metadata auth plug-ins would be a good place to start from. I wouldn't worry too much about code duplication since as you say, they are treated as separate plugins.

One thing to note about plugins like this is that we don't really have automated tests that actually interact with the external environment, like Azure in this case. In addition to unit tests, it would therefore be good if you could at least add some instructions to you PR later on how someone else could go about testing this in an Azure environment. Doesn't have to be super detailed, just things like "spin up a new Ubuntu instance, push a bundle to the azure blob storage with authentication required, start OPA with this configuration to authenticate against the blob storage" or something like that. I'd be happy to help with testing later.

Some general tips for contributing is found in the main page [README](https://github.com/open-policy-agent/opa/#want-to-contribute-to-opa). Also, feel free to ping me in the [OPA Slack](https://slack.openpolicyagent.org/) if you have questions along the way.

**Comment by Scowluga** [comment]
I've opened an initial draft PR at #3952 so subsequent discussion will happen there.
