### ISSUE TITLE
/v1/config endpoint may expose credentials provided in custom headers

### ISSUE THREAD

**Issue by dolevf** [open-policy-agent/opa#3950]
Hi OPA friends,

**Environment**
- OPA 0.31.0 
- Default Settings
- Additional service in OPA configuration

**Problem Statement**
In some cases, configurations may include passing tokens using custom headers (as opposed to using the `credentials` config with `bearer` token, etc.) as [explained here](https://www.openpolicyagent.org/docs/latest/configuration/#example).

The concern is that the `/v1/config` endpoint doesn't require authentication by default unless explicitly implemented, which may expose secrets to unauthenticated users. 

```
{
  "result": {
    "decision_logs": {
      "console": true,
      "reporting": {
        "max_delay_seconds": 90,
        "min_delay_seconds": 30
      },

.. snip ..

    "services": {
      "myservice": {
        "allow_insecure_tls": false,
        "headers": {
          "APITOKEN": "MY_CUSTOM_TOKEN_KEY"
        },
        "response_header_timeout_seconds": 10,
        "url": "http://example.com"
      }
    }
  }
}
```

**Possible Solutions**
I don't necessarily know if this requires "fixing" since it's difficult to know about all the various use cases. I see two possible options to go about this:

1. **The non-technical solution**: update the OPA docs to remind/educate users that `/v1/config` is, by default, unauthenticated, and any secrets passed in non-traditional forms could be exposed this way.
2. **The technical solution**: add `mask_headers` / `hide_headers` key with an array of header keys to the configuration name object so OPA will know what headers to hide.
3. Perhaps both. 

For the technical solution, I imagined something like this:

```
services:
  myservice:
    url: http://example.com
    response_header_timeout_seconds: 10
    allow_insecure_tls: false
    headers:
       APITOKEN: MY_CUSTOM_TOKEN_KEY
    mask_headers:
       - APITOKEN
```

This will result in masking any headers with a key equal to `APITOKEN`.

Thank you.

**Comment by ashutosh-narkar** [comment]
@dolevf we have a dedicated `credentials` field which we recommend for including secrets etc. We could add a note in the docs to remind users to use that field to include sensitive info and not the headers field.

**Comment by dolevf** [comment]
hi @ashutosh-narkar thanks for the response. Would credentials also allow for custom headers in this case? or is it mostly built in Header keys such as `Authorization`?

**Comment by ashutosh-narkar** [comment]
Credentials can be used to set the `Authorization` header from the values in the provided config.

**Comment by dolevf** [comment]
Understood, but if an OPA user uses credentials where Authorization header key isn't used, would that not be another aspect to consider?

**Comment by ashutosh-narkar** [comment]
> Understood, but if an OPA user uses credentials where Authorization header key isn't used, would that not be another aspect to consider?

IIUC you're saying users could include credentials in the headers field ?

**Comment by dolevf** [comment]
yes, e.g. OPA makes a remote request to a custom service that doesn't use `Authorization` header in particular, but instead uses something such as `X-API-TOKEN`:`secret-token`

**Comment by anderseknert** [comment]
The requirements for this to manifest as a problem:

1. OPA exposed "publicly", i.e. not just on localhost.
2. Despite publicly exposed, OPA running without authz policy protecting /config.
3. Use of non-standard HTTP header to send credentials to remote service.

Even with a "mask_headers" option, it's not unthinkable that credentials or sensitive values show up elsewhere in the config structure in other unusual configurations. I'd probably settle for an update to the docs about this unless this turns out to be more common than we think, in which case we could either have some way to mark any arbitrary value as sensitive (like "urn:sensitive:my-secret-value" or we could have a `credentials` structure similar to the current `keys`, where sensitive data could be stored. This would however require that there's some canonical way of referencing those values from anywhere else in the configuration, and when printed we'd only show the reference, not the actual value.

**Comment by anderseknert** [comment]
Oh the joys of YAML 😆 Turns out there _is_ a canonical way to reference other nodes in YAML, I've just never seen it used.
```yaml
services:
  acmecorp:
    url: https://example.com/control-plane-api/v1
    credentials:
      bearer:
        token: &token "bGFza2RqZmxha3NkamZsa2Fqc2Rsa2ZqYWtsc2RqZmtramRmYWxkc2tm"
    headers:
      APITOKEN: *token
```
This declares "token" as a [node anchor](https://yaml.org/spec/1.2.2/#692-node-anchors), which is subsequently referenced in `APITOKEN`. To my surprise this actually works with OPA, as in, the `APITOKEN` value will be that of the bearer token. Our masking system however does not take this into account, and I'm guessing it can't as this is likely resolved when parsing the YAML. Additionally, this obviously wouldn't work with configuration provided as JSON.

**Comment by dolevf** [comment]
That is interesting @anderseknert - I do agree that it's difficult to accommodate for all possible scenarios.

I think updating the docs to educate users would likely be the most beneficial.

**Comment by anderseknert** [comment]
Agreed. Would you like to contribute a doc update? :)

**Comment by dolevf** [comment]
https://github.com/open-policy-agent/opa/pull/3956
