### ISSUE TITLE
Test cases are evaluating incorrectly when used with object response

### ISSUE THREAD

**Issue by keshavprasadms** [open-policy-agent/opa#4162]
Hi there. I am seeing test cases show as PASS when ideally they should be shown as FAIL. Please see below for details -
OPA Version: 0.34.2

##### Policies
`foo.rego`
```
package foo

default allow = false

allow {
  input.message
}
```
`foo_test.rego`
```
package foo

test_foo_allow {
    data.foo.allow
}
```
`bar.rego`
```
package bar

default allow = {
  "allowed": false,
  "headers": {"X-Request-Allowed": "no"},
  "body": "Forbidden",
  "http_status": 403
}

allow {
  input.message
}
```
`bar_test.rego`
```
package bar

test_bar_allow {
    data.bar.allow
}
```
##### Tests
```
opa test -v .
FAILURES
--------------------------------------------------------------------------------
data.foo.test_foo_allow: FAIL (625.633µs)

  query:1             Enter data.foo.test_foo_allow = _
  foo_test.rego:3     | Enter data.foo.test_foo_allow
  foo.rego:5          | | Enter data.foo.allow
  foo.rego:6          | | | Fail input.message
  foo_test.rego:4     | | Fail data.foo.allow
  query:1             | Fail data.foo.test_foo_allow = _

SUMMARY
--------------------------------------------------------------------------------
data.bar.test_bar_allow: PASS (531.787µs)
data.foo.test_foo_allow: FAIL (625.633µs)
--------------------------------------------------------------------------------
PASS: 1/2
FAIL: 1/2
```

I was expecting `data.bar.test_bar_allow` to `FAIL`. Apparently if I use the below format for the default block, test cases doesn't seem to work correctly. Is this format not supported for test cases?
```
default allow = {
  "allowed": false,
  "headers": {"X-Request-Allowed": "no"},
  "body": "Forbidden",
  "http_status": 403
}
```

Where as this works as expected `default allow = false`.

The reason I am using the default block with headers and body is because I want to send a custom message and header from envoy + opa if the policy check fails. More details here - https://www.openpolicyagent.org/docs/latest/envoy-primer/#example-policy-with-object-response

**Comment by anderseknert** [comment]
Rego tests work pretty much like any other Rego rules - if all expressions in the body evaluate to true/defined, the rule is considered true (or in the case of a test, considered to `PASS`).

In the case of your policy and test:

```rego
package bar

default allow = {
  "allowed": false,
  "headers": {"X-Request-Allowed": "no"},
  "body": "Forbidden",
  "http_status": 403
}

allow {
  input.message
}

test_bar_allow {
    data.bar.allow
}
```

The default assignment on the `allow` rule will be provided to the test (since there is no `input.message`), and a defined object is considered "truthy". `false` on the other hand is (as the name implies) not considered true. 

The way the `allow` rule is defined in the above policy isn't ideal though - you'll probably want the allow to _always_ return an object. As it currently is written you'll return an object (the default assignment) if allow is undefined, but a boolean if defined. To always return an object you'll need to define another return value for allow, like:

```rego
allow = response {
  input.message

  response := {
    "allowed": true,
    "headers": {"X-Request-Allowed": "yes"},
    "body": "OK",
    "http_status": 200
  }
}
```

**Comment by keshavprasadms** [comment]
Thank you @anderseknert for your suggestion. I updated all my allow blocks to respond with an object which will have an `allowed` field and I was able to get my test cases working with below changes -

```
test_bar_allow {
    data.bar.allow.allowed
}
```
