### ISSUE TITLE
Delta bundle is rejected when using documented format of patch.json

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#4336]
When playing around with a bundle server implementation, I noticed that the delta bundles sent by the remote are rejected when presented as the documentation (and the JSON patch specification) suggests they should be:

**patch.json**
```json
[
  {"op":"upsert","path":"/bar/random","value":"6949"},
  {"op":"upsert","path":"/foo/random","value":"17935"}
]
```

```json
{
  "level":"error",
  "msg":"Bundle load failed: bundle load failed on patch decode: json: cannot unmarshal array into Go value of type bundle.Patch",
  "name":"app",
  "plugin":"bundle",
  "time":"2022-02-10T23:12:00+01:00"
}
```
This error is caused by the deserialization of the patch:

https://github.com/open-policy-agent/opa/blob/15bb78a47f9b6bb18b41d6bbf63f89ed887c3203/bundle/bundle.go#L1284-L1286

As the `Patch` includes a `data` attribute:

https://github.com/open-policy-agent/opa/blob/15bb78a47f9b6bb18b41d6bbf63f89ed887c3203/bundle/bundle.go#L61-L63

Changing the `patch.json` file produced by the remote "fixes" the problem:

```json
{"data": [
  {"op":"upsert","path":"/bar/random","value":"6949"},
  {"op":"upsert","path":"/foo/random","value":"17935"}
]}
```
That is however not a spec compliant JSON patch, nor the format [documented](https://www.openpolicyagent.org/docs/latest/management-bundles/#delta-bundle-file-format).

---

Two unrelated questions/concerns around delta bundles which I might as well raise here.

* Where does the "upsert" operation come from? The documentation links to the JSON patch spec, which makes it seem like the format follows the standard, but I can't find the upsert op there. Is it covered in some addition to the standard or is it made up? Either way, it would be good if that was mentioned in the docs. Even with "upsert" there, it would be nice if we supported the standard operations of "add" and "replace" as that is what any JSON patch library is going to provide.

* It seems strange to me that the `wasm` attribute needs to be present in the `.manifest` file of the delta bundle if present in that of the snapshot bundle, given how:
    * The .manifest file is optional to begin with. 
    * The docs describe the attribute as "a list of OPA WebAssembly (Wasm) module files in the bundle along with metadata for how they should be evaluated."
    * The same docs state that "OPA will generate an error if a delta bundle contains any policy, data or wasm binary files."

Thinking more about this, is this just a case of the docs missing a "_if present_" somewhere in that "A delta bundle update for an existing snapshot bundle, MUST have the same values for the manifest roots and wasm fields" sentence?

**Comment by anderseknert** [comment]
> We could just make this more explicit in the docs. WDYT ?

Yes, just a mention that this is not part of the spec would be fine 👍 

> Also we should update the patch file format shown in the doc.

Why? I'd rather see we removed the wrapping of the `data` attribute and keep the docs as is. As far as I can see the data wrapper adds nothing of value, and it makes the format even more distanced from the JSON patch specification.

> On the requirement of the .manifest file to be present in the delta if present in the snapshot

But  the .manifest file is documented as optional. I don't see a reason to change this just because a snapshot bundle contained a `wasm` attribute. Skippng the .manifest file altogether in the delta bundle, or including a .manifest file without a `wasm` attribute, should be perfectly fine, as it's clearly out of scope for the delta bundle. _If_, and only if, a delta bundle contains this attribute in the manifest, it should be required that it matches that of the snapshot bundle.

IMO, any metadata missing from a delta bundle should just be assumed to be inherited from the snapshot bundle.

**Comment by tsandall** [comment]
A few thoughts...

# Supported patch operations

The `upsert` operation is useful for constructing patches without having to think about non-leaf nodes in nested objects. It's not standard but the more time you spend writing code to process patch operations, the more you wish this existed. That said, I'm surprised we don't support the `add` operation; I would have thought that minimally we'd support add/remove/replace and then include upsert as well. This would give us better compatibility with JSON patch libraries.

# patch.json schema

If we make the top-level value of the patch.json file an array, we're going to regret it at some point because it means there will be no room for extension (i.e., we'd have to introduce a new file in the bundle spec). Moreoever, the `data` key signifies that the patch operations are relative to the `data` document. What would happen if we needed to patch other state, e.g., policies? Overall, I don't see this as a problem. Just wrap the patch in an object.

# .manifest requirements

> Thinking more about this, is this just a case of the docs missing a "if present" somewhere in that "A delta bundle update for an existing snapshot bundle, MUST have the same values for the manifest roots and wasm fields" sentence?

Yes, I think the docs should clarify the requirement here. If the OPA has previously activated a bundle that DID NOT contain a .manifest file, then the delta bundles MUST NOT contain a .manifest. If the OPA has previously activated a bundle that DID contain a .manifest file, then the delta bundles MAY contain a .manifest.

In the latter case, the delta bundles need to contain a .manifest if the previously activated bundle (a) declared roots or (b) specified wasm resolvers (e.g., `{"wasm": [{"entrypoint": "example/allow", "path/to/binary.wasm"}]}`).

More simply, the .manifest in a delta bundle is a _snapshot_ not a _partial_ value. Since it's a snapshot, and since we don't support root updates or wasm resolver updates in delta bundles, it would be illegal to omit the roots or wasm resolvers if they were previously supplied (because this would be the same as changing them.)

**Comment by anderseknert** [comment]
Agreed on upsert being a nice addition, having experienced the pain of the add/replace semantics myself in mutating k8s policies, although I don't think it matters as much in this context as any patch is likely to be generated by a library, so having to change the output retrieved from that library is only going to add an extra step in the patch creation process, even if it is a trivial one. Sounds like we agree on that, and `add`/`replace` should be accepted.

As for the wrapping of the JSON patch in a `data` attribute, I'm not sure I would consider having to add another file, or files, for describing policy updates a regrettable decision - in fact I would probably prefer that kind of separation as it would make the contents/effects of a delta bundle easier to determine from just a quick glance at the files included. We're basically reinventing a directory structure inside of the `patch.json` file rather than using one in the archive, e.g:

```shell
├── .manifest
├── data
│   └── patch.json
└── policy
    └── patch.json
```

On the .manifest and manifest attributes being optional vs. required, that explanation makes sense. Let's have that added to the docs!

**Comment by tsandall** [comment]
> As for the wrapping of the JSON patch in a data attribute, I'm not sure I would consider having to add another file, or files, for describing policy updates a regrettable decision - in fact I would probably prefer that kind of separation as it would make the contents/effects of a delta bundle easier to determine from just a quick glance at the files included. We're basically reinventing a directory structure inside of the patch.json file rather than using one in the archive, e.g:

This raises a couple thoughts/questions for me. Specifically about what "data" and "policy" mean in that example.

```
├── .manifest
├── data                       <--- What does "data" mean here?
│   └── patch.json
└── policy                     <--- What does "policy" mean here?
    └── patch.json
```

In the current bundle format, the directory hierarchy controls the mounting of data.json files into the `data` namespace. If you create a top-level directory named "data" and put a data.json file in it, the contents of data.json are mounted at `data.data`. Same for a top-level directory named "policy"--they'd be referenceable at `data.policy`.

One thing I could imagine supporting is patch.json files at arbitrary levels in the directory hierarchy--because .rego files _relocatable_ perhaps those patch.json files could implicitly apply to just data, in which case a top-level array value would be fine.

**Comment by anderseknert** [comment]
> This raises a couple thoughts/questions for me. Specifically about what "data" and "policy" mean in that example.

I don't see how it's different from the same attributes being baked into the patch.json file though? "data" (and possibly, at a later stage "policy") would mean the same thing as is currently encoded in the patch.json file:

```shell
{
    "data": [{ .. data JSON patch operations here }],
    "policy": [{ .. policy JSON patch (or whatever format used) operations here }],
}
```

> In the current bundle format, the directory hierarchy controls the mounting of data.json files into the data namespace.

Right, but this does not apply to delta bundles, as there are no `data.json` files, nor policies in those. The JSON patch operations clearly mark out the `path` for which an operation applies, so the directory structure in the bundle has no bearing on what gets changed.

All I'm saying is I'd rather see the patch.json files be actual JSON patch files (as the name implies, and as currently documented), and that we'd use the directory structure of delta bundles to separate data updates from policy updates (if we include those later), as it would be easier to quickly inspect a delta bundle by just looking at the contents.

Obviously, this isn't a huge deal, but since it was suggested to "fix" the docs, I just thought an alternative approach should be considered, as the documented approach seems more sensible to me.
