### ISSUE TITLE
Not able to put new policy via rest api when bundle is loaded in OPA

### ISSUE THREAD

**Issue by harshit-work** [open-policy-agent/opa#4341]
## Short description 

Getting following error
{
    "code": "invalid_parameter",
    "message": "all paths owned by bundle \"pre_loaded\""
}

* Version: 0.37.1
* Below is the curl request

curl -X PUT \
  http://localhost:8181/v1/policies/opa.cust_xyz \
  -H 'cache-control: no-cache' \
  -H 'content-type: text/plain' \
  -H 'postman-token: 20e8447a-ac02-1f8b-6c81-e95849d331ad' \
  -d 'package opa.cust_xyz

default inbound_rules = false

inbound_rules = response {
    m := input.ipv4Ranges[0]["cidrIp"]
    response := {
        "passed":  m != "0.0.0.0/0",
        "port": input.fromPort,
        "p": input.ipRanges[_] != "0.0.0.0/0",
        "message": "Security group should not allow all ips"
    }
}'

**Comment by tsandall** [comment]
This is by design. Bundles declare the package/data namespaces that they own. If you do not declare any roots in your bundle manifest then it defaults to everything. If you want to allow callers to push policies or data into an OPA that's configured to download bundles, then update your bundle to scope it's roots accordingly.

https://www.openpolicyagent.org/docs/latest/management-bundles/#multiple-sources-of-policy-and-data
