### ISSUE TITLE
Shell execute as part of policy evaluation

### ISSUE THREAD

**Issue by rmetcalf9** [open-policy-agent/opa#4671]
We have the need to call the aws sdk for various reasons as part of policy evaluation.
One example is retrieving a secret value. We have explored retrieving secrets as part of the opa-agent container boot up and passing to opa as environment variables but the problem is that from time to time the secrets are rotated. This means that unless we restart all our containers opa will stop working.

Calling the aws sdk via http.send is very complex and involves signing requests. This is very impractical in OPA. One solution would be to go one by one and add features to opa to call the aws sdk but this involves a lot of change. We would then end up with opa always being behind the latest aws sdk version.

We would like to be able to install the aws cli as part of the opa-agent container image. This will let us run the latest sdk. The problem is that there is currently no way for an opa policy to run a shell command and get the response.

If there was a shell execute command as part of opa this would resolve this and many similar issues. We could put multiple cli tools into the opa-agent container and have access to them in policies.

## What part of OPA would you like to see improved?

I would like a new function added which will execute a command on the shell.
Inputs to the function should be the shell command name, the paramaters to be passed and the environment variables to be set, and a timeout setting.
Outputs from the command should be the stdout and stderr that the command returns, as well as the result status code
Commands also need to timeout in case of a long running command.

## Describe the ideal solution

Add a shell execute command to opa

## Describe a "Good Enough" solution

Add an aws retrieve secret function to opa, then maintain that function keeping it up to date with all sdk changes. We would then also have to implement other solutions for other sdk calls that are needed as part of policy evaluation.

## Additional Context
None

**Comment by anderseknert** [comment]
Thanks for submitting this! Some thoughts: 

> Calling the aws sdk via http.send is very complex and involves signing requests. This is very impractical in OPA.

Hopefully https://github.com/open-policy-agent/opa/issues/3749 would handle most of the details around that? Been a while since I looked into that though — is there some parts which would be difficult to have implemented as part of the `http.send` built-in?

I'd be very cautious about a built-in to call arbitrary shell commands. We've previously have had requests for builtins to do file read/write operations too, and had the same concerns about those. I suppose that _if_ we had a builtin like this, it could be disabled by default, and only be enabled on demand. The [capabilities](https://www.openpolicyagent.org/docs/latest/deployments/#capabilities) feature of OPA allows this to some extent, but it currently only works for restricting bundle creation, not the OPA runtime itself... which I think would have to be a requirement here.

Another concern would be that since the default OPA image does not provide a shell, this built-in would be a no-op for the vast majority of users. It would essentially require a custom built image of OPA + a shell environment, at which point the step to instead provide a [custom builtin](https://www.openpolicyagent.org/docs/latest/extensions/#custom-built-in-functions-in-go) for this purpose wouldn't feel too far off.

Ideally, custom plugins and builtins would be addable just by providing some code in a /plugins directory or something like that, but unfortunately the story around that isn't great in Go :(

**Comment by srenatus** [comment]
> Ideally, custom plugins and builtins would be addable just by providing some code in a /plugins directory or something like that, but unfortunately the story around that isn't great in Go :(

Relevant #3631.

**Comment by rmetcalf9** [comment]
I was researching doing the signing of requests for AWS by implementing in python (rather than using the sdk). 
I started following this doc https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html to implement it but I have since realised that this process is for s3. I guess it will be the same for other AWS api's such as secretsmanager but there is no guarantee.
Also any implementation is beholden to that aws implements at their end and will always be complex.
I like the idea of being able to leverage the AWS provided SDK libraries (or cli) in some way. The maintenance overhead would be much lower and it will be a much simpler solution.

I share the concern about the shell execute feature. If used for state changes or IO then there are a lot of things developers can fall fowl of. You are giving developers a lot of rope and it will be impossible to stop them from hanging themselves! Especially if they are have the wrong idea of how OPA chooses what to execute.

I did note that there was no shell in the default image and I am intending to change my build process to building one myself with a shell in it. This has the downside of bigger less efficient images.

For me it's a balance between the complexity of implementing AWS SDK stuff myself vs being able to leverage AWS SDK's. My gut tells me that leveraging the SDK is more valuable.

I am considering an alternative approach. Creating my own docker image with both the OPA agent and a python API server application which uses the python AWS SDK (BOTO) to do what I need. Then I could make the two servers in the same container talk on a local socket and OPA can use http.send. Since it is a local socket there will be no security concerns but it breaks the docker principle of having each container do only one thing.

It's all getting complicated considering all I want to do is get a secret from secretsmanager to do one thing!

**Comment by anderseknert** [comment]
> I am considering an alternative approach. Creating my own docker image with both the OPA agent and a python API server application which uses the python AWS SDK (BOTO) to do what I need. Then I could make the two servers in the same container talk on a local socket and OPA can use http.send. Since it is a local socket there will be no security concerns but it breaks the docker principle of having each container do only one thing.

Yeah, that's probably how I'd do it too, at least until request signing works in [http.send](url). I'm not sure about the environment you'd run this in, but for Kubernetes it would just be another sidecar container. Containers running in the same pod will always run on the same host, and will be reachable on the localhost interface.

**Comment by anderseknert** [comment]
I've asked in the OPA #development Slack channel for interest in tackling the AWS request signing issue. Hopefully someone steps up to the challenge :)

**Comment by srenatus** [comment]
As another approach, you could create a little sidecar process or script that fetches your secret and feeds it into OPA's data API. It's a bit hacky, but not too bad, I'd think... 🤔

**Comment by anderseknert** [comment]
Closing this issue for now, as a viable workaround seems to have been found, and another issue exists to allow AWS request signing in `http.send`. @rmetcalf9 let me know if you think I missed something and I can open it once more.
