### ISSUE TITLE
Improve handling of numeric values in AST and storage

### ISSUE THREAD

**Issue by jc-m** [open-policy-agent/opa#473]
In the ast, InterfaceToValue() claims to "converts a native Go value x to a Value" however, json.Number is not a Go value, and this prevents using something like fathil/structs to store objects when using opa as a library.

**Comment by tsandall** [comment]
OPA should handle numeric types gracefully. Currently, OPA will barf if its given float/int types instead of json.Number. OPA should ingest float/int types wherever possible. If ingestion would cause problems, OPA should better error messages and include clear documentation about how callers can supply json.Number values.
