### ISSUE TITLE
Internationalizing documentation

### ISSUE THREAD

**Issue by Joffref** [open-policy-agent/opa#4793]
## What part of OPA would you like to see improved?
I think OPA should include some other languages in its documentation.

I'm planning to do, if you agree, the translation of the documentation in French. At least the Introduction.

**Comment by anderseknert** [comment]
That's an interesting idea @Joffref 🙂

And it's probably not a big thing to do from a technical POV, as I assume Hugo supports this well. I think the big challenge would be how to keep this maintained over time. If we update the docs — and we do all the time! — unless we have someone — and ideally at least two people, since we'd want to have someone reviewing as well — fluent in that second language commiting regularly to OPA, we won't be able to update the translation ourselves, and there's always going to be a risk of it getting out of date compared to the English version. I suppose if the translation at least initially covers only the introduction, and "what is OPA/Rego"... that might not be as much of an issue.

@peteroneilljr might have some ideas here as well.

**Comment by srenatus** [comment]
At the very least, we could add a section linking the non-english resources known today. They don't quite fit well in the ecosystem category.

**Comment by ashutosh-narkar** [comment]
Closing for now. We can re-visit based on interest and if folks would like to volunteer to help achieve this.
