### ISSUE TITLE
Huge memory consumption

### ISSUE THREAD

**Issue by rafaela-soares** [open-policy-agent/opa#4964]
## Short description 

Hello, 

We (KICS team) found a huge memory consumption when KICS* calls OPA:

<img width="883" alt="image" src="https://user-images.githubusercontent.com/74001161/182594613-6c762c6c-0ca6-4626-8b66-1cefabba8bb6.png">

(*) [KICS](https://github.com/Checkmarx/kics) is an open source static analysis tool for IaC solutions provided by Checkmarx that uses Rego as query language.

(We are using version v0.42.2, but we already tried with v0.43.0)

Can you help us figure it out why, please?

## Steps To Reproduce
1. Fork KICS
2. Switch to branch fix/memory_consumption
3. Run `go run --tags dev ./cmd/console/main.go scan -p ./assets/queries/cloudFormation/aws -v`
4. In other terminal, run `go tool pprof http://localhost:6060/debug/pprof/heap`
5. In other terminal, run `go tool pprof --http=:8030 <file_created_in_the_previous_step>`
6. In pprof, choose 'alloc_space' in Sample and  'Flame Graph' in View

## Expected behavior
Less memory consumption

**Comment by anderseknert** [comment]
Hi Rafaela! 👋 

The OPA maintainers can't really troubleshoot issues in other projects. If you think you've identified a memory leak, or just excessive use of memory in OPA, please try to:

1. Isolate the issue so that the undesired behavior can be demonstrated in OPA alone.
2. Provide examples of code (or a script, etc) and input data that consitently reproduces the issue.
3. Be specific in what your expectations of memory consumption would be vs. real memory consumption.

**Comment by rafaela-soares** [comment]
Hello, @anderseknert ! 👋
Thank you so much for the quick response.

We understand. I isolated the issue in [opa_test.zip](https://github.com/open-policy-agent/opa/files/9253376/opa_test.zip), with examples.

From what I was able to understand, the excessive use of memory in OPA occurs in functions PrepareForEval and Eval. You can see more details in the following pprof:

<img width="890" alt="image" src="https://user-images.githubusercontent.com/74001161/182659001-9754883c-d480-47fa-86f5-c62509ff0e0e.png">

I would like to understand if the "excessive" use of memory is supposed to happen or not. It seems a lot for 248 queries.

**Comment by anderseknert** [comment]
Running the main file of the archive you created, I don't even see the process in `top`, `htop`, or the system monitor app on my Mac. Is the numbers from the flame graph simply not just an accumulation of all memory used through the run, not deducting what was returned? Either way, both the flame graph and the other views show the absolute majority of memory spent in JSON serialization/deserialization.

<img width="1027" alt="Screenshot 2022-08-03 at 22 15 36" src="https://user-images.githubusercontent.com/510711/182703215-906d6c23-8b15-47d4-9acf-680a909d69e7.png">

Since the input you provide to all the queries here is constant, there's really no need to have it parsed in each iteration of the loop. Just do it once before you start querying OPA and have the parsed input provided instead, e.g.

**outside of the loop**
```go
	var x interface{}

	err = util.UnmarshalJSON(payload, &x)
	if err != nil {
		panic(err)
	}

	astPayload, err := ast.InterfaceToValue(x)
	if err != nil {
		panic(err)
	}
```
**inside of the loop**
```go
		options := []rego.EvalOption{rego.EvalParsedInput(astPayload)}

		_, err = opaQuery.Eval(timeoutCtx, options...)
```

**Comment by rafaela-soares** [comment]
Hello again, @anderseknert!

Thank you so much! Your suggestion helped a lot! 🚀 

Is it normal the memory consumption in `Compile`?

**Comment by anderseknert** [comment]
I'm happy to hear that, @rafaela-soares 🙂

Yes, I don't see anything out of the ordinary wrt memory consumption. Again, I don't think the pprof numbers can be read as "total memory consumed at any given point in time", but you'd need to consult the pprof docs for all of the options provided their, and how their respective results should be interpreted.

**Comment by rafaela-soares** [comment]
Sorry for bothering again, @anderseknert.

I did not notice that the results "disappeared" when I added `ast.InterfaceToValue(x)` ([opa_test_not_working.zip](https://github.com/open-policy-agent/opa/files/9261080/opa_test_not_working.zip)). Can you help me, please? I can not figure it out why. 

It works fine without `ast.InterfaceToValue(x), however the memory consumption remained the same in [opa_test_working.zip](https://github.com/open-policy-agent/opa/files/9261091/opa_test_working.zip).

**Comment by anderseknert** [comment]
@rafaela-soares you're not using `rego.EvalParsedInput(astPayload)`...

**Comment by rafaela-soares** [comment]
My bad! Thank you so much, @anderseknert

**Comment by anderseknert** [comment]
NP 😊 we good to close this now?

**Comment by rafaela-soares** [comment]
Yes, thank you! 🚀
