### ISSUE TITLE
add new function to GraphQl built-ins

### ISSUE THREAD

**Issue by olegroom** [open-policy-agent/opa#5125]
Can you make another graphql.isvalid funciton that takes only one param (String graphqlSchema) and check if it's valid. Check just syntax of schema

**Comment by srenatus** [comment]
Hmm could you approximate this by using [`graphql.is_valid`](https://www.openpolicyagent.org/docs/edge/policy-reference/#builtin-graphql-graphqlis_valid) with some trivial query? 🤔

**Comment by olegroom** [comment]
As far as I know even the trivial query means specifying names/fields from Schema. If so, it is impossible for us. Our product checks the validity of GraphQL Schemas commands send to us. We have no idea what will be there

**Comment by srenatus** [comment]
I see. Hmm given that we cannot overload functions, what would you call this? `graphql.schema_valid`? Is this something you could see yourself contributing? 😃

**Comment by olegroom** [comment]
Yeap, sounds great) Thx

**Comment by srenatus** [comment]
Oh contributors of every experience levels are welcome here. If you'd like a challenge, we're here to help. Just holler and we'll get you some pointers on which steps are needed to get this implemented. The basic building blocks should all be there already.

**Comment by philipaconrad** [comment]
@olegroom You can get identical functionality by just checking to see if `graphql.parse_schema` succeeds.
Example policy with helper function:

```rego
import future.keywords.if

# Example schema string:
gql := `
   type Hello {
     world: String
   }
`

# Helper function that checks to see if schema parsing succeeded.
# It will error with <undefined> when the schema has syntax errors.
schema_valid(graphql_schema_str) if {
	x := graphql.parse_schema(graphql_schema_str)
	is_object(x)
}

allow if {
	schema_valid(gql)
}
```

Try tinkering with the schema on the Rego Playground, and see if something like the above suits your usecase: https://play.openpolicyagent.org/p/5WG0qQfu4H

You can try messing up the schema, and it should cause the `allow` rule to fail.

**Comment by srenatus** [comment]
> but directed it to the gqlparser gitHub you use as mirror

👍 thanks, good call!

**Comment by olegroom** [comment]
https://github.com/vektah/gqlparser/issues/238#issuecomment-1245044227
Not sure about this answer, cause I found use of new "v2" version of parser in [internal/gqlparser/rewrite-deps.sh](https://github.com/open-policy-agent/opa/blob/45a3d8ee70241b76087aac40c21a47bc654847a5/internal/gqlparser/rewrite-deps.sh)
Shell I make contribution now obeying this https://www.openpolicyagent.org/docs/latest/contrib-code/#developer-certificate-of-origin?

**Comment by srenatus** [comment]
We're using v2.4.8, I think, based on https://github.com/open-policy-agent/opa/pull/5067.

Yeah feel free to open a PR, we'll get the DCO sorted out, it's just a matter of adding a Signed-off-by line to the commit message. Thanks!

**Comment by giautm** [comment]
Hello, 👋 

I don't think upgrading the package should resolve your problem because there are no related changes to the issue.
https://github.com/vektah/gqlparser/compare/v2.4.8...v2.5.1

You need to make a call to `ValidateSchemaDocument` to validate the schema. :)

**Comment by jkulvich** [comment]
I have made draft changes: https://github.com/open-policy-agent/opa/pull/5130.
They include gqlparser update to 2.5.1 and 2 new built-in rego functions.

**Comment by srenatus** [comment]
Huh. I would have expected that it would be cool to just ad the ValidateSchemaDocument call to the existing `parse_schema` builtin. WDYT @philipaconrad?

**Comment by srenatus** [comment]
Also if it can be helped, let's try to do one thing at a time. I don't think we need to bump the version for being able to use ValidateSchemaDocument, do we? 🤔 Just because bumping involves fixing some annoying lint errors over and over again 😅

**Comment by philipaconrad** [comment]
There's been a surprising amount of activity on this thread this morning! :sweat_smile: 

-----

>  I would have expected that it would be cool to just add the `ValidateSchemaDocument` call to the existing `parse_schema` builtin.

@srenatus It's arguably the more correct behavior, but it'll definitely surprise some downstream users, I suspect. Inputs that were fine for parsing (but not validation!) in OPA v0.44.0 will suddenly start returning validation errors if we make that change.

We'll need to call it out in the Release notes for v0.45.0. It's definitely an improvement overall, for many validation-related use cases.

> I don't think upgrading the package should resolve your problem because there are no related changes to the issue.
https://github.com/vektah/gqlparser/compare/v2.4.8...v2.5.1

@giautm You are correct here. The reason we didn't jump to v2.5.0 to begin with was because nothing past v2.4.8 was significant (in terms of features/validation rules), other than `gqlparser` changing how they expose their error system. I went with a slightly older version to avoid having to do a bunch of refactoring, and also to avoid having to fight the linter more than necessary.

> Not sure about this answer, cause I found use of new "v2" version of parser in [internal/gqlparser/rewrite-deps.sh](https://github.com/open-policy-agent/opa/blob/45a3d8ee70241b76087aac40c21a47bc654847a5/internal/gqlparser/rewrite-deps.sh)

@olegroom Before we internalized the library, we were vendoring `vektah/gqlparser/v2`. We haven't done anything special, other than rewrite the import paths to allow that module to exist as the package `opa/internal/gqlparser`, and deal with linter issues that came up.

The maintainer in the [thread you linked](https://github.com/vektah/gqlparser/issues/238#issuecomment-1245044227) is correct: all you really want is to ensure that the validation functions get called on the schema document after it's created.

**Comment by olegroom** [comment]
Then, we are currently working on adding only one is_valid_schema(string) method, which return true/false. Let us know if there is a possible somehow get the error message, cause inner Go function throw an informative error message, which I would like to have in Rego.

**Comment by philipaconrad** [comment]
Our gqlparser version is now updated to v2.5.0+, so it is now possible to add the `is_valid_schema` builtin discussed earlier in this thread. That will provide a small but useful expansion to the `graphql` suite of builtins.
