### ISSUE TITLE
glob.match mutex issue

### ISSUE THREAD

**Issue by srenatus** [open-policy-agent/opa#5273]
```rego
package p

p {
	glob.match("*.github.com", [], "api.github.com")
	glob.match("*.github.com", [], "api.github.com")
}
```

this is stuck in a deadlock. The problem is the `defer` vs `return iter(...)` in https://sourcegraph.com/github.com/open-policy-agent/opa@4dab906937b3ecfd389d95b92aa9eedb58a58ad9/-/blob/topdown/glob.go?L50-63

**Comment by philipaconrad** [comment]
@srenatus As you suspected, the deadlock there is caused by the interaction of `iter(...)` call at the end of the builtin function + a deferred mutex unlock.

The call to `iter(...)` allows the evaluator to walk the AST and start executing the *next* call to `glob.match` *before the first call has technically returned*. This means the first `glob.match` call never has the chance to give up its mutex lock, and we get a deadlock.
