### ISSUE TITLE
/eval endpoint which loads and evaluates both policy and data in a single request

### ISSUE THREAD

**Issue by andreimladin** [open-policy-agent/opa#5309]
We need OPA to expose the eval feature through API too, where we could request it by passing both data and policy in a single request in a such way they could be run in isolation.

## What is the underlying problem you're trying to solve?
By having this, OPA will be able to load policies at runtime and we will avoid the manual process of restarting it and reloading the policies rego files again and again at each new or modified rego file.

## Describe the ideal solution
The solution should accept more rego files for the policy because it could be composed of one main rego file having the verdict, but also it could refer to other shared packages (common libs) and in this case we need to send them too, they are needed for compilation and evaluation itself.

## Describe a "Good Enough" solution
I'm working on a solution for this, I will come back later with a proposal in this direction.

## Additional Context
My colleague already had a discussion with you, where he described better what we want, please see [here](https://openpolicyagent.slack.com/archives/CBR63TK2A/p1643222686198959) the thread

**Comment by anderseknert** [comment]
Hey Andrei! And thanks. While I'm sure you're aware, I just want to make it clear — there's no need to restart the OPA server to have it load policy at runtime. You'd commonly use either [bundles](https://www.openpolicyagent.org/docs/latest/management-bundles/) or the [REST API](https://www.openpolicyagent.org/docs/latest/rest-api/#create-or-update-a-policy) for that.

Just so that we know more about your use case — what is the reason for having to provide the policies as part of the request, and not asynchronosly beforehand?

**Comment by andreimladin** [comment]
Hello Anders! Thanks for your response and sorry for my delay. 

I've analyzed a little bit the possibility to do that through the bundles or making use of what REST API already has, but it's not what we actually desire.
We would like to keep simplicity, pass a policy + data in single request and receive the evaluation of that. A bundle is processed asynchronously and it requires to have in place a server where the bundle(s) is exposed; and REST API is good, but not good enough for our case, we would like to keep it in a single call and run it in isolation.

**Comment by spockz** [comment]
The main objective we have is that can evaluate a policy and input/data in *isolation* from other policies and data. We have the situation where our team is hosting a service and does not control the policies. They are changed by our consumers.

We are looking at having a single endpoint in the OPA http server that can handle this evaluation in isolation. Whether we need to pass in a bundle-id/name for fetching from a service, or pass in a bundle, or pass in just the policy files is inconsequential for us. 

We do want to prevent having a mechanism where we first PUT the policy, and then use it. We would always need to store the policy with a  PUT because we don't know whether the policy is already there (or first do a get to check).

In our solution we added the /eval endpoint through a plugin. It works, but we would like to contribute something back that would be in line with the ideas of OPA, so if we need to change to using bundles that is worth considering.

@anderseknert do you know how we can configure OPA to dynamically load bundles by name on /eval? As far we could deduce the individual bundles need to be configured up front in the OPA configuration.

Would you be interested in receiving the `/eval` endpoint as a PR? We can just add the PR to make what we did more tangible.

**Comment by anderseknert** [comment]
Hey there! 😃 

I understand the concern, but I'm not entirely convinced OPA as a _server_ is the right model for this type of evaluation. Since there is no state involved here, evaluation might as well be done entirely client-side, either by shelling out to `opa eval`, or if fortunate enough to write a Go application, via the OPA Go library.

I don't think it's only a matter of adding an endpoint either. While that might seem trivial, this endpoint would be quite detached from how OPA normally works in server mode:

* The configuration file would largely be ignored, since policy is not provided in bundles
* Decision logging would as it currently exists be useless, as there would be no record of which policy actually got evaluated
* The discovery API would have no function
* The status API would have nothing to report

To add to that, an `/eval` endpoint would add a significant cognitive burden to new users trying to grasp the use cases for the various endpoints. We already have quite a chore explaining the differences between `/v0/data` and `/v1/data`, and that's even a "simple" one. Extensive documentation could help with this, naturally, but docs only take you so far..

So... while I'm not dismissing the use case, I don't think we'll want to add and endpoint like this to the OPA server. That does not necessarily mean we couldn't include something like this within the OPA project however. I could imagine wrapping a simple server around the `rego` package, to do stateless eval on any provided policies, data and input. If you have the code to do that, I'd be happy to see it in the [contrib repo](https://github.com/open-policy-agent/contrib) 😃

**Comment by spockz** [comment]
> Since there is no state involved here, evaluation might as well be done entirely client-side, either by shelling out to opa eval, or if fortunate enough to write a Go application, via the OPA Go library.

What are then the use-cases for using opa as a *server*? Of course, we could, as a last resort, shell out to `opa eval` but that has significant downsides in the interface and protocol. Or phrased differently, given the argumentation that we can just call `opa eval` or add opa as a library, why does `opa serve` exist at all?

> The configuration file would largely be ignored, since policy is not provided in bundles

Okay. With the configuration as it is today I can see that. Would ik make sense to in addition of the static config for bundles like this

```

bundles:
  authz:
    service: acmecorp
    resource: somedir/bundle.tar.gz
    persist: true
    polling:
      min_delay_seconds: 10
      max_delay_seconds: 20
```

Have a bundle that is more dynamically determined/loaded? E.g.

```yaml
bundles:
  $dynamic:
    service: dynamic-service
    resource: $bundle-name-or-id/bundle.tar.gz
    persist: true
    polling:
      min_delay_seconds: 10
      max_delay_seconds: 20
```

It may be my lack of knowledge. Are all configured bundles downloaded ahead of time (given polling), or does the interface already provide some means to specify which bundle to use? What happens if multiple bundles provide the same package names?

> Decision logging would as it currently exists be useless, as there would be no record of which policy actually got evaluated

Okay fair, we do not need that ourselves as that logging is already done on our side. However, this seems to be an issue today as well with bundles. These policies can also dynamically change, so there is probably some bundle hash or policy hash that is being used in the logging.


> The *discovery API* would have no function (emphasis mine)

The discovery API was new for me. Perhaps we can even use this to dynamically discover all currently "active" policies and fetch them. The only tricky bit would be knowning/making sure whether the opa instance already has fetched a new policy before using it.

> The *status API* would have nothing to report

If we are to use bundles with specific, unique, names they can be reported in the status API.

**Comment by anderseknert** [comment]
> What are then the use-cases for using opa as a server?

What it always was — to provide a way to **decouple** policy evaluation from the client application, and allow centralized management of policy and data. Having the client provide everything the server needs for evaluation provides nothing to that end.

> Are all configured bundles downloaded ahead of time (given polling), or does the interface already provide some means to specify which bundle to use? 

All bundles are downloaded, although not necessarily ahead of the first evaluation. You'd normally ping the `/health` endpoint with the `bundles` [query parameter](https://www.openpolicyagent.org/docs/latest/rest-api/#health-api) to ensure all bundles have been loaded before you consider the service operational.

> What happens if multiple bundles provide the same package names?

That's fine — a package can exist across multiple files. Rules may however not provide conflicting results. So if you have one bundle that says `data.foo := 10` and another that says `data.foo := 20`, the latter bundle won't be activated due to the conflict.

> Of course we could add the code for the plugin to the contrib repo. Our first objective is to use OPA as intended [...]

Right, and I'm not sure the OPA server is intended for this use case :)

One approach could be to use a custom plugin, but I'm honestly not sure if we could accomplish this only via a plugin... or is that what you have got working already? My suggested approach for the contrib repo would otherwise just be to write a simple HTTP server to wrap the calls `rego.New`,  `Eval`, etc.

It might also be useful to check out the `opa exec` command — it's basically running `opa run` but for one-off evaluations, where you can provide the bundle(s) and input data for evaluation. It's similar to how `opa eval` does things, but with all the management capabilities of the OPA server previously mentioned available.
