### ISSUE TITLE
fmt: `_` in args getting rewritten to `_0`, `_1`...

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#5347]
Not sure what's going on here, but it's not something I'd expect.
```rego
package policy

f(_, _) := 1 {
	true
} else := 2 {
	true
}

foo := f("foo", "bar")
```
`opa fmt -w .` :=>
```rego
package policy

f(_0, _1) := 1 {
	true
} else := 2 {
	true
}

foo := f("foo", "bar")
```

**Comment by srenatus** [comment]
So looking at the code, it's done on purpose. But it's buggy, since it does not avoid clashes:

```rego
package p
import future.keywords.if

f(_, _) := 1 if _1 := 1
else := 2
```
⬇️ 
```rego
package p

import future.keywords.if

f(_0, _1) := 1 if _1 := 1

else := 2 if true
```

⚡ the first policy will satsify `f(0, 0) == 1`, the second one will _not_.

I'm still not certain if there's value in doing this in the first place, but since it was done on purpose, it seems safe to assume that there's a reason. We should still avoid clashes like these, though.
