### ISSUE TITLE
docs: Search doesn't work on the Wasm page

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#5362]
Tried on every page under the Misc category, and it works as expected on all of them except for the Wasm one, where an error saying "docsearch is not defined" is found in the browser console. Tried on both FF and Chrome.

![Screenshot 2022-11-07 at 09 00 55](https://user-images.githubusercontent.com/510711/200256733-4d61df28-793f-4eb3-b469-2b81a3cbf93a.png)

Most likely an easy fix, so marking as good first issue... but who knows :)

**Comment by srenatus** [comment]
I can reproduce this. However, the wasm page is rendered in exactly the same way every other docs page is. And it does include the docsearch stuff in its `<head>`:
https://github.com/open-policy-agent/opa/blob/fb2bde05b3551e143d9359c819b79dcd59d39837/docs/website/layouts/partials/javascript.html#L3

So, this is a riddle to me. Might be good-first-issue material when you're into JS. (Maybe we need to add some statement to [the `docsearch()` code snippet](https://github.com/open-policy-agent/opa/blob/fb2bde05b3551e143d9359c819b79dcd59d39837/docs/website/layouts/partials/javascript.html#L21) to ensure it only loads after the other stuff is loaded, or something? No expert with this 😅)

**Comment by anderseknert** [comment]
Thanks Stephan! I'll remove the good first issue label as it seems more involved than I thought, but hopefully some JS ninja can find their way here still :)

**Comment by Parsifal-M** [comment]
Hello Team :wave:!

Just a small update on this...

I've got a PR kind-of-ready for this :partying_face: but the fix is to essentially update to v3 of DocSearch, and to do that we need some additional bits of information which are not needed in v2:

-> https://docsearch.algolia.com/docs/migrating-from-v2

Namely the `appId` which I think you have to get from logging into the UI of DocSearch :smiling_face_with_tear: I have already spoken to @charlieegan3 who is going to try and find someone with the keys :crossed_fingers:, once we have the `appId` I will add it to the PR and see what happens, hopefully, it `automagically` works!

**Comment by charlieegan3** [comment]
Thanks Peter 🙏 (& belated Happy Christmas too!)

I've asked internally and will chase again when we have more people around in the new year!

**Comment by anderseknert** [comment]
Fixed at last. Thanks @charlieegan3, @Parsifal-M and others who helped out in this surprisingly big effort!

**Comment by charlieegan3** [comment]
Thanks for remembering to close the issue too!
