### ISSUE TITLE
OPA query performance

### ISSUE THREAD

**Issue by surjith** [open-policy-agent/opa#539]
We did some performance tests on the current version of OPA (0.5.x) for one of our use cases. 
Scenario:
         Registered users will belong to different groups. Each group will have access policies which determines access to resources. 
The structure of data is as follows:
```
{
  "groups": [
    {
      "groupid": "65b1cf6b-b758-4e4b-a1b3-77118c285f8e",
	  "policies": [	"pagereadpolicy" , "pagewritepolicy"],
      "users": [
        {
          "userid": "0fa73dac-0653-45c6-85f8-d1fdde8f8e18"
        },
        {
          "userid": "9819dbee-d06e-4fb7-8233-8670ddca69c5"
        },
        {
          "userid": "e449eb9e-d533-4df3-bd53-4204ca4e52c3"
        },
        {
          "userid": "1f5810bb-1884-453a-876d-0226fbe81c96"
        }
      ]
    }
],
  
  
  "accesspolicies": [
    {
      "policyid": "pagereadpolicy",      
      "access": "read",
      "resources": [
        {
          "type": "page",
          "id": "page1"
        },
        {
          "type": "page",
          "id": "page2"
        }
      ]
    },
    {
      "policyid": "pagewritepolicy",      
      "access": "write",
      "resources": [
        {
          "type": "page",
          "id": "page1"
        },
        {
          "type": "page",
          "id": "page2"
        }
      ]
    }
  ]
}

```

The performance we got varied as the number of groups and users increased. Running within a local docker container with 4 gigs memory, the results are as follows (timing obtained from fiddler for api call)

1000 groups; 100 users = .7 - .8 ms
10,000 groups; between 20 - 100 users randomly = 2 s
10000 groups; 100 users = 7 s
1000 groups; 1000 users = 7 s

one of the data files(with 1000 groups and 1000 users) and the query file attached. 

[files.zip](https://github.com/open-policy-agent/opa/files/1613559/files.zip)

**Comment by tsandall** [comment]
Thanks for opening this. OPA currently has to scan all groups, users, and accesspolicies. As a result, I'd expect the latency to grow as you showed. If the policy did not contain any variables and instead had the groups/users/accesspolicies encoded as constants in the policy, the latency would be ~constant as OPA will build a trie over the allow rules...

For example, instead of encoding the groups/users/accesspolicies in data, they would show up in the policy itself. This way the policy would look something like...

```
allow {
  input.user = "bob"
  input.method = "get"
  input.path = "/some/resource-1"
}

# ...

allow {
  input.user = "alice"
  input.method = "post"
  input.path = "/some/resource-2"
}
```

Obviously this would require you to generate policies programmatically (which is a bit inconvenient if you have the data readily available as JSON.) Luckily, in the next release of OPA, we will have an optimization in place which will effectively do this for you.

**Comment by tsandall** [comment]
This case should be handled by partial eval. Closing this in favour of future tickets around partial eval.

The alternative would be to restructure the policy to use objects instead of arrays.
