### ISSUE TITLE
An official meta language document for WASM porting

### ISSUE THREAD

**Issue by shm12** [open-policy-agent/opa#5410]
## What is the underlying problem you're trying to solve?
Currently, the Wasm consumption in different languages have some cons, which make it difficult to migrate to them:
- Every language OPA porting define its own behavior and API (for example, the Go SDK vs the JS one).
- Lack of documentation.
- Lack of features support.
- New OPA versions require re-editing of the porting.
- Not many languages are supported.

## Describe the ideal solution

I suggest providing an official document which define the poring behavior (APIs and internal) (similar to the concept of [winmd](https://learn.microsoft.com/en-us/uwp/winrt-cref/winmd-files)).
This file can include the documentation to the porting API.
After providing such a file, to support a specific language, one should write a script to generate the porting.
This way:
- All the languages porting will have the same API (Which make it easier for users to migrate between languages)
- The documentation will have to be updated only in one place.
- As well as the features support.
- As well as new OPA versions support.
- Supporting a new language will only require the generator script.
## Describe a "Good Enough" solution
The current solution is good enough :)

**Comment by srenatus** [comment]
Heya, thanks for the write-up.

I, too, would appreciate if there was a commonly used way to declare Wasm host methods. But I am not sure that this is the case today. The last time I had checked, WIT (formerly WITX) tried to solve just this problem, but it came with problems of its own: it's not able to declare recursive data types, of which we make use: JSON and the AST JSON variant (JSON plus sets) are inherently recursive.

So, since we cannot make up a format, I'm a bit at a loss here to determine how to do deal with this.

Also, what are you planning to do? Perhaps [the existing SDKs ](https://github.com/anderseknert/awesome-opa#webassembly-wasm) are a helpful resource, and you can always reach out with concrete questions.

**Comment by srenatus** [comment]
🧹 I'm cleaning this up. Let's reopen if a suitable format emerges, so this becomes actionable.
