### ISSUE TITLE
Use `data` document in mask `upsert` operations

### ISSUE THREAD

**Issue by drewcorlin1** [open-policy-agent/opa#5416]
## What is the underlying problem you're trying to solve?
The decision log masking is fantastic, but I want to be able to depend on `data` documents to include already parsed information from the request in the logs. This is largely because I want to keep the entire authorization header out of decision logs, but I want to be able to provide a subset of identifiable information from that header.

## Describe the ideal solution
I can use other modules that have already parsed out and refined parts of the request to include more context in my decision logs.
```rego
package system.log

mask[{"op": "upsert", "path": "/input/attributes/request/http/claims", "value": input.data.http_request.claims}]
```

where `data.http_request.claims` is a parsed + slightly reformatted JWT from an authorization header like
```rego
package http_request

import input.attributes.request.http as req

claims = payload {
	token := substring(req.headers.authorization, 7, -1)

	[_, payload, _] = io.jwt.decode(bearer_token)
}
```

## Additional Context
Technically this is currently possible, as I could duplicate the parsing of `input.input.attributes.request.http.headers.authorization` in my `system.log` module, but that's not ideal because it duplicates the code, and also because `claims` in this context can come from a few other locations too (query params in some cases, principal provided by envoy in some cases) so it would quickly become complicated to duplicate all of that logic in the log masking logic.

**Comment by anderseknert** [comment]
Hi there! It's been a while since I worked with masking, so please forgive me if I'm a little rusty here :) But can't you reference the same rule or function from inside of the system.log policy as you would from your "main" policy? I.e. why would you need to duplicate that logic there? If it's only a matter of the `input` attribute looking different in the two scenarios, I could imagine having a function to do the work, and to ensure the input data to the function looked the same in both invocations. But again, could be I'm just missing something obvious here 😅

**Comment by drewcorlin1** [comment]
Looks like I am able to import a function from another module so that should help significantly! The thing I can't figure out is how to reference a parsed piece of data from another module that references the input itself.

With a logging setup like
```rego
package system.log

import data.http_request.my_var

mask[{"op": "upsert", "path": "/input/attributes/request/http/myVar", "value": my_var}]
```

This works (`input.attributes.request.http.myVar` shows up as `"2"` in my logs)
```rego
package http_request

my_var := "2"
```

but this does not (`input.attributes.request.http.myVar` is missing from my logs)

```rego
package http_request

my_var := req.headers["my-var"]
```

with an input of 
```json
{
  "query": "data.istio.authz.allow",
  "input": {
      "attributes": {
          "request": {
              "http": {
                  "headers": {
                      "my-var": "1"
                  },
                  "method": "GET",
                  "path": "/route"
              }
          }
      }
  }
}
```
I'm running OPA via 
```
opa run --server --addr localhost:8181 --set=decision_logs.console=true --bundle bundle.tar.gz
```
and I'm hitting it with
```
curl -X POST --data '@./input.json' --header 'Content-Type: application/json' http://localhost:8181/v1/query
```


Reusing the function will definitely get me most of the way there, but I'm curious if there is something I'm missing when trying to reference data that came from the input request?

**Comment by anderseknert** [comment]
I was hinting at it before, but I wasn't very clear, sorry 😅 The structure of the `input` document is going to be different for "normal" policy evaluation and the evaluation done in the context of decision masking. This is due to the fact that the decision log contains not just the original input, but also the result of evaluation, metadata, and whatnot. 

The original `input` attribute in the context of decision logging policies will be stored under `input.input` (as detailed in the [docs](https://www.openpolicyagent.org/docs/latest/management-decision-logs/#masking-sensitive-data)), so in order to have your `http_request` policy work the same for both, you could either use a function, or `with` to "mock", or rather reshape, the input variable in the context of that evaluation. I'd probably use the latter, i.e. something like:

```rego
package system.log

mask[{"op": "upsert", "path": "/input/attributes/request/http/myVar", "value": my_var}] {
    my_var := data.http_request.my_var with input as input.input
}
```

**Comment by drewcorlin1** [comment]
Ah sorry I totally missed that! Feels like my brain started to ignore the word `input` 😅. This solution works for me, thanks so much for the quick help!
