### ISSUE TITLE
crypto.x509.parse_certificates validating empty file as valid certificate?

### ISSUE THREAD

**Issue by volck** [open-policy-agent/opa#5584]
## crypto.x509.parse_certificates validating empty file as valid certificate?
It seems like using the crypto.x509.parse_certificates builtin method does not invalidate empty files.

Example:

* OPA version:
```me@somemachine $ opa version
Version: 0.48.0
Build Commit: 572e5c7ea0ed118900382908e7f1b68e1e665c04
Build Timestamp: 2023-01-09T16:07:13Z
Build Hostname: 1dd169e8fd7c
Go Version: go1.19.4
Platform: linux/amd64
WebAssembly: unavailable
```

Given the policy:

```
valid_cert {
valid_cert := crypto.x509.parse_certificates(input)
}


```
using the test:

```
test_invalid_cert_emptyfile {
    not valid_cert with input as ``
}
```
the test returns false:
```
data.certificate.test_invalid_cert_emptyfile: FAIL (90.921µs)
````

* Example output that OPA returned
Flags used to run test: 
```opa test -v certificate.rego certificate_test.rego```

## Expected behavior
I would expect the test to ```pass``` as this is clearly an empty file and not a valid certificate.

**Comment by srenatus** [comment]
So I first thought this was a `not`-related fallacy, since

```rego
not valid_cert
```
will be true if either of these are true:
1. `valid_cert` evaluates to `false`
2. `valid_cert` is `undefined` (fails to evaluate to anything)

And I thought that in your case, it's probably (2.). To gain further insights, I've then run with `--strict-builtin-errors`:
```
$ opa eval -fpretty  -d x.rego data.x.test_invalid_cert_emptyfile 
undefined
$ opa eval -fpretty --strict-builtin-errors -d x.rego data.x.test_invalid_cert_emptyfile
undefined
$ echo "\"\"" | opa eval -fpretty --strict-builtin-errors -d x.rego data.x.valid_cert -I
true
```

To conclude, there's no fallacy here -- the builtin called on `""` will return `true`, plain and simple.

Looks like with no input, we'll end up feeding `""` into `x509.ParseCertificates`, and that'll return an empty list and no error, see [this golang playground](https://play.golang.com/p/ukK8pLDkt_H). Fascinating.

FWIW to change your rule to work around this, you'd do 
```rego
import future.keywords.if
valid_cert if count(crypto.x509.parse_certificates(input)) > 0
```

**Comment by charlieegan3** [comment]
At least, I think we might want to update the docs for this built in since we currently use a similar copy to the [Golang docs](https://pkg.go.dev/crypto/x509#ParseCertificates).

```
Returns one or more certificates...
```

While the docs are perhaps misleading in both the OPA and Golang for this case of empty input (since 0 is not "1 or more"), I feel that this is the correct behaviour for this builtin.

The type signature for the golang function is telling - we could get an empty slice back:

```
func ParseCertificates(der []byte) ([]*Certificate, error)
```

As I see it, getting an empty certificate chain and getting a certificate chain containing invalid x509 data are two different cases that a policy author might want to handle while using this function.

**Comment by volck** [comment]
AFAIK the other x509 related builtins invalidate empty files. So shouldn't this function also invalidate them?

**Comment by charlieegan3** [comment]
Partially, yes. `crypto.x509.parse_certificate_request` or `crypto.x509.parse_rsa_private_key` will error with an empty string for input. With the default built in error handling however, users don't see this and it's the same as undefined. `crypto.x509.parse_and_verify_certificates` will return `[false, []]`.

What I hadn't realised earlier, is that that `crypto.x509.parse_certificates` with empty input is `null` rather than `[]` 😞. This doesn't seem correct to me. My view is that `crypto.x509.parse_certificates` should return `[]` in given empty input. 

This is tricky though as changing the behaviour of a built in might break user policies who count this particular case. Given that, I'm not sure what the best course of action is.

**Comment by ashutosh-narkar** [comment]
The docs have been updated to give more clarification about how the builtin should be used. Closing this for now.
