### ISSUE TITLE
Schema validation for maps

### ISSUE THREAD

**Issue by wermerb** [open-policy-agent/opa#5601]
I would like to provide a json schema to enforce type checking with the help of rego type checker for maps.
If I understood correctly the documentation this is something that today is not possible.

Ex: lets say we have the following data representation:

```
{
  "users": {
    "aa5c4ec3-e2c8-4c75-8e1e-d2f42c4eedf1": {
      "roles": [
        "a",
        "b"
      ]
    },
    "0c540f0b-d029-42b5-97f8-586de8294c68": {
      "roles": [
        "c"
      ]
    }
  }
}
```

**Comment by charlieegan3** [comment]
I presume this data is coming from your `input`? If so, I think this is a duplicate of https://github.com/open-policy-agent/opa/issues/3341. Good news though, this is something that's currently being worked on in https://github.com/open-policy-agent/opa/pull/5572.

Hopefully that will work for your use case 🤞

**Comment by wermerb** [comment]
@charlieegan3, thanks for the quick response. I agree #5572 is a nice feature but it seems to me thats a runtime check for the server.

I was more referring to "data" object it self which can be loaded for example via bundles. ex: users.json.

I would like to do a static type checking while we write the policies with the help of METADATA + schema as described here: https://www.openpolicyagent.org/docs/latest/schemas/#using-schemas-to-enhance-the-rego-type-checker

**Comment by anderseknert** [comment]
Hi @wermerb 👋 You definitely can do type checking of maps. The only thing I'm unsure of is the dynamic key names... is that what your concern was about too?

**Comment by wermerb** [comment]
Hi @anderseknert, yes exactly, as that would require the pattern feature of the json schema which is a currently not supported.

**Comment by srenatus** [comment]
https://github.com/open-policy-agent/opa/issues/3796

**Comment by anderseknert** [comment]
We've [previously](https://github.com/open-policy-agent/opa/issues/4426) disabled checking string values with a defined `pattern` since that would add nothing of value to the type checker, and simply parsing them would sometimes cause the schema validator to fail, as any valid JS regexp isn't a valid RE2 regexp. For a few scenarios, the schemas are not user provided, but comes from e.g. Kubernetes... and so ignoring things we don't care about seemed like a better option than to crash.

As for `patternProperties` we have not disabled handling of those, but we aren't using them for type checking either (like the issue @srenatus linked above mentions). I'm not sure how much effort would be required to feed "any attribute with a key matching this pattern should conform to this type" into the type checker, but it would come with the same problem `pattern` did. That would probably be OK for most patterns, but would fail on anything not recognized by Golang's regexp dialect.

**Comment by wermerb** [comment]
I understand your reasoning behind this 100%. 

However, what if it would be an opt in feature (ex: you would need to pass in an extra flag in the cli) and the user could decide whether it fits his/her apatite for this risk.
Given that we are looking at a static type checking with either opa check or opa eval I think this could be an acceptable trade off.

**Comment by anderseknert** [comment]
Agreed. Someone would just need to step up and work to make it happen :)
Do you think we can close the issue in favor of the existing one?

**Comment by wermerb** [comment]
Should comment it under #3796? As it focusing on a different aspect of the problem.

**Comment by anderseknert** [comment]
Yes, please do 👍

**Comment by wermerb** [comment]
Closing this as discussed. Thank you for the chat guys :)

**Comment by anderseknert** [comment]
Thanks @wermerb 😃
