### ISSUE TITLE
fmt: panic on type error

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#5646]
An edge case for sure, but `opa fmt` panics on cerrtain invalid constructs, like this example.

```rego
package play

test_and_false_false {
	and([true, false]) == false
}
```

```
❯ opa fmt .
panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
github.com/open-policy-agent/opa/format.(*writer).writeCall(0x14000123a40, 0x0, {0x140002f2cf0?, 0x2, 0x2}, {0x0, 0x0, 0x0})
	/Users/anderseknert/git/opa/opa/format/format.go:781 +0x248
github.com/open-policy-agent/opa/format.(*writer).writeTermParens(0x14000123a40, 0x0?, 0x1400026bd10, {0x0?, 0x140003bf248?, 0x102dbb7ac?})
	/Users/anderseknert/git/opa/opa/format/format.go:711 +0x2b8
github.com/open-policy-agent/opa/format.(*writer).writeTerm(...)
	/Users/anderseknert/git/opa/opa/format/format.go:676
github.com/open-policy-agent/opa/format.(*writer).writeFunctionCall(0x14000123a40, 0x0?, {0x0, 0x0, 0x0})
	/Users/anderseknert/git/opa/opa/format/format.go:638 +0x2bc
github.com/open-policy-agent/opa/format.(*writer).writeExpr(0x14000123a40, 0x140001aef40, {0x0?, 0x0?, 0x140001aec00?})
	/Users/anderseknert/git/opa/opa/format/format.go:541 +0x108
github.com/open-policy-agent/opa/format.(*writer).writeBody(0x14000123a40?, {0x140005d84b8, 0x1, 0x0?}, {0x0?, 0x0?, 0x10403a520?})
	/Users/anderseknert/git/opa/opa/format/format.go:519 +0x80
github.com/open-policy-agent/opa/format.(*writer).writeRule(0x14000123a40, 0x140001aef00, 0x0?, {0x0?, 0x0?, 0x0?}, {0x0, 0x0, 0x0})
	/Users/anderseknert/git/opa/opa/format/format.go:358 +0x3bc
github.com/open-policy-agent/opa/format.(*writer).writeRules(0x10378dca0?, {0x140005d84f0, 0x1, 0x0?}, {0x0?, 0x0?, 0x0?}, {0x0?, 0x10460c108?, 0x12bc4db98?})
	/Users/anderseknert/git/opa/opa/format/format.go:305 +0x84
github.com/open-policy-agent/opa/format.(*writer).writeModule(0x14000123a40, 0x1400049b180?, {0x0?, 0xec?, 0x27?})
	/Users/anderseknert/git/opa/opa/format/format.go:272 +0x3e8
github.com/open-policy-agent/opa/format.AstWithOpts({0x103737020?, 0x1400049b100?}, {0x40?})
	/Users/anderseknert/git/opa/opa/format/format.go:152 +0x590
github.com/open-policy-agent/opa/format.Ast(...)
	/Users/anderseknert/git/opa/opa/format/format.go:61
github.com/open-policy-agent/opa/format.Source({0x140001e9f30, 0xb}, {0x14000228800?, 0x1027e4714?, 0x140003bf898?})
	/Users/anderseknert/git/opa/opa/format/format.go:40 +0xc8
github.com/open-policy-agent/opa/cmd.formatFile(0x104075058, {0x103822260, 0x14000120008}, {0x140001e9f30, 0xb}, {0x10382e6c8, 0x1400011f450}, {0x0?, 0x0?})
	/Users/anderseknert/git/opa/opa/cmd/fmt.go:111 +0x1d4
github.com/open-policy-agent/opa/cmd.opaFmt.func1({0x140001e9f30?, 0x0?}, {0x10382e6c8?, 0x1400011f450?}, {0x0?, 0x0?})
	/Users/anderseknert/git/opa/opa/cmd/fmt.go:76 +0x68
path/filepath.walk({0x140001e9f30, 0xb}, {0x10382e6c8, 0x1400011f450}, 0x103819748)
	/opt/homebrew/Cellar/go/1.19.4/libexec/src/path/filepath/path.go:433 +0xd0
path/filepath.walk({0x16d6835f8, 0x1}, {0x10382e6c8, 0x1400011f380}, 0x103819748)
	/opt/homebrew/Cellar/go/1.19.4/libexec/src/path/filepath/path.go:457 +0x1fc
path/filepath.Walk({0x16d6835f8, 0x1}, 0x103819748)
	/opt/homebrew/Cellar/go/1.19.4/libexec/src/path/filepath/path.go:520 +0x6c
github.com/open-policy-agent/opa/cmd.opaFmt({0x140002f2bc0?, 0x1, 0x0?})
	/Users/anderseknert/git/opa/opa/cmd/fmt.go:75 +0xe4
github.com/open-policy-agent/opa/cmd.glob..func1(0x104020d60?, {0x140002f2bc0?, 0x1?, 0x1?})
	/Users/anderseknert/git/opa/opa/cmd/fmt.go:53 +0x2c
github.com/spf13/cobra.(*Command).execute(0x104020d60, {0x140002f2b80, 0x1, 0x1})
	/Users/anderseknert/git/opa/opa/vendor/github.com/spf13/cobra/command.go:920 +0x5b0
github.com/spf13/cobra.(*Command).ExecuteC(0x104020a80)
	/Users/anderseknert/git/opa/opa/vendor/github.com/spf13/cobra/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/anderseknert/git/opa/opa/vendor/github.com/spf13/cobra/command.go:968
main.main()
	/Users/anderseknert/git/opa/opa/main.go:14 +0x28
```

Originally reported by @nevumx.

**Comment by Trolloldem** [comment]
I have looked into the code that is responsible for this error. The problem seems to the following: 

- in the [writeCall](https://github.com/open-policy-agent/opa/blob/main/format/format.go#L763) function, it is searched if the parsed function name is among the built-in functions, contained in this [map](https://github.com/open-policy-agent/opa/blob/main/ast/builtins.go#L29)
- if the parsed function name is not in the mentioned map, or the retrieved `Function` has an empty String as `Infix` field, the [writeFunctionCallPlain](https://github.com/open-policy-agent/opa/blob/main/format/format.go#L653) function handles the writing of the formatted function
- in the other cases, the wast majority of built-in functions has two arguments (only the [in operator](https://github.com/open-policy-agent/opa/blob/main/format/format.go#L789) has special handling
- since the writer does not check that the actual number of provided elements matches the built-in function signature, (here)[https://github.com/open-policy-agent/opa/blob/main/format/format.go#L781] the access to `x` is performed at an index  out of bounds

This behavior causes the reported bug every time that a built-in function with a corresponding `Infix` field is called with only one argument, for instance: `plus([1,2]) == 3` and `plus(1) == 3` cause the same exact error reported.

In addition to this, there is another possible unwanted behavior caused by this function. If the following code is formatted:
`plus(1, 2, 3) == 3` is formatted, the final result is `1+2 == 3` `, since the last argument is ignored by the formatting procedure.

@anderseknert I would like to work on this, starting with a fix that checks that the actual number of terms provided has a size of 2. After that, it would be nice to address in some way the other issues identified

@anderseknert

**Comment by anderseknert** [comment]
Wow, that's some thorough analysis! A fix, and potentitally future improvements, would be muh appreciated. Feel free to reach out should you need any help, but you already seem more knowledgable than me on this :)
