### ISSUE TITLE
ARM Docker Images for latest

### ISSUE THREAD

**Issue by veddermatic** [open-policy-agent/opa#5739]
## What is the underlying problem you're trying to solve?

Developers have M2 based Apple hardware, and our Docker `docker-compose.yml` file uses this:
```
image: openpolicyagent/opa
```
This will not run on those developer's machines during development.  We can switch to `openpolicyagent/opa:edge-static` during development to get it to run, but not as written by our default setup.

## Describe the ideal solution

There would be a`linux/arm64` image for `image: openpolicyagent/opa`

## Describe a "Good Enough" solution

Some context on if using `edge-static` which does have a `linux/arm64` image is suitable for deployment and if so, why it's not the default. This would be helpful for people who don't know much about Docker images  that will be deployed in a number of environments (AKA me.)

Thanks!

**Comment by anderseknert** [comment]
Hi there!

The `latest` tag also has a `-static` version: https://hub.docker.com/layers/openpolicyagent/opa/latest-static/images/sha256-b164ce18f8b7833e26995401f76ed510645f025c58b76299edac5fcfc31b2fe7?context=explore

Which is published with a linux/arm64 target. I'd suggest using that instead of `edge`.

Unless you're planning to use the Wasmtime inside of OPA, there should be no differences to the "regular" latest image.

**Comment by ashutosh-narkar** [comment]
Currently we don’t build non-static OPA binaries for linux/arm64  as the wasm lib OPA uses does not yet support linux/arm64. So as Anders mentioned the `static` variant should work on linux/arm64.
