### ISSUE TITLE
OPA debug logs expose X-AMZ-SECURITY-TOKEN header

### ISSUE THREAD

**Issue by jwineinger** [open-policy-agent/opa#5848]
## Short description 
I'm using OPA with S3 signing to retrieve bundles and with debug logs turned on. With that configuration, I see request logs that OPA makes to S3 infra. These requests have the Authorization header value overwritten to "REDACTED", but the X-AMZ-SECURITY-TOKEN header is still provided. My understanding is that this is a secret value as well and it would be preferable to have this redacted as well.

We don't normally run with debug logs turned on, but some teams do from time to time, and we don't want AWS security tokens making it into our log aggregator.

* OPA version: 0.49.0

## Steps To Reproduce
1. Configure opa to use S3 as a bundle source
2. Start opa with debug logs
3. Tail opa logs and see that the X-AMZ-SECURITY-TOKEN header value is shown while the Authorization header value is "REDACTED"

## Expected behavior
Any request headers containing secrets should be redacted. This would at least include the Authorization header and the X-AMZ-SECURITY-TOKEN headers. Perhaps auth plugins could contribute to a list of headers that should be filtered.

**Comment by ashutosh-narkar** [comment]
As discussed in [this](https://groups.google.com/g/open-policy-agent-security/c/z4Sg2m_ZRyQ/m/Kl9VzP-nDgAJ?utm_medium=email&utm_source=footer) thread, one option would be to extend [withMaskedAuthorizationHeader](https://sourcegraph.com/github.com/open-policy-agent/opa@845652e11501045706b62cb929bf3e507e4a52b0/-/blob/plugins/rest/rest.go?L335) to redact other headers in addition to the authorization header.

**Comment by rudrakhp** [comment]
@ashutosh-narkar I don't seem to have access to the thread. Can you either provide the access or briefly describe how to extend this method? Thanks!
To give you more context, we currently import OPA directly as a package to build our custom image and would like to extend/modify this masking behaviour without having to maintain our own version of OPA. Is masking written in such a way so that we can possibly override it's behaviour by just importing OPA package?

**Comment by ashutosh-narkar** [comment]
@rudrakhp as you see in https://sourcegraph.com/github.com/open-policy-agent/opa@845652e11501045706b62cb929bf3e507e4a52b0/-/blob/plugins/rest/rest.go?L335 currently we only mask the `Authorization` header. We can extend that method to accept other headers as well. 

>  Is masking written in such a way so that we can possibly override it's behaviour by just importing OPA package?

I am not sure what masking you're referring to here. There is the ability to [mask](https://www.openpolicyagent.org/docs/latest/management-decision-logs/#masking-sensitive-data) sensitive data from decision logs and this one is to mask data from OPA's debug logs. What are you trying to achieve here?

**Comment by rudrakhp** [comment]
@ashutosh-narkar thanks for the reply. To be very specific we have an use case where we want to log sone part of the authorization header (only payload of JWT token for example) instead of redacting the header completely. Is this supported currently?

The reason we require this capability is to debug prod incidents without having to reproduce/replay the requests. Also ensuring the complete header is not leaked to avoid security risks.

**Comment by rudrakhp** [comment]
So if I understand correctly, the headers logged in OPA decision logs is controlled via rego and can be modified as well (similar to the usecase I pointed out above).

**Comment by ashutosh-narkar** [comment]
>  To be very specific we have an use case where we want to log some part of the authorization header (only payload of JWT token for example) in the OPA decision logs instead of redacting the header completely. Is this supported currently?

You should be able to do this by specifying an `upsert` operation in the `mask` rule. See [this](https://www.openpolicyagent.org/docs/latest/management-decision-logs/#masking-sensitive-data) section for an example.

**Comment by yogisinha** [comment]
@ashutosh-narkar  can I take a look at this, if nobody is working on it. ? Shall I put a check specifically against X-AMZ-SECURITY-TOKEN header in withMaskedAuthorizationHeader method to redact it ? we can also maintain a list of headers to make this check if in future we have to hide another headers. we can just add the header name to list in that case.

**Comment by ashutosh-narkar** [comment]
That sound reasonable @yogisinha.

**Comment by bdjgs** [comment]
I also have the case where sensitive information is sent to OPA in the POST body. And when running with debug log level the input is logged to stdout/terminal. So it would also be great to have support for masking the information that OPA logs to stdout/terminal.

**Comment by colinjlacy** [comment]
@ashutosh-narkar since this has gone stale, I can jump on it.  I've got a flight coming up that would give me time to knock out the code and tests.  

If I'm reading through this right, the easiest way to address it would be to create a static slice of headers that we'd want to mask, and then look through it in [withMaskedAuthorizationHeader](https://github.com/open-policy-agent/opa/blob/main/plugins/rest/rest.go#L357C6-L368).  I'd imagine a future expansion would be to allow a user to set a configuration, but that sounds out of scope for this issue.  Is that all correct?

**Comment by ashutosh-narkar** [comment]
> If I'm reading through this right, the easiest way to address it would be to create a static slice of headers that we'd want to mask, and then look through it in [withMaskedAuthorizationHeader](https://github.com/open-policy-agent/opa/blob/main/plugins/rest/rest.go#L357C6-L368). I'd imagine a future expansion would be to allow a user to set a configuration, but that sounds out of scope for this issue. Is that all correct?

Correct @colinjlacy. If we extend that method to accept other headers and provide a static list to that call it should be fine for now.
