### ISSUE TITLE
Different output for WASM bundle vs `opa run -s .`

### ISSUE THREAD

**Issue by JAForbes** [open-policy-agent/opa#5874]
## Short description 

I've created a minimal reproducible example here: https://github.com/JAForbes/opa-wasm-issue

## Expected behavior

The output for both the wasm bundle should produce the same output.

**Comment by anderseknert** [comment]
Have spent some time to track this down together with @johanfylling , and we noticed pretty much accidentally that the bundle actually evaluates as expected when provided to OPA server with the `--bundle`/`-b` flag. 

```
opa run -s -b bundle.tar.gz
```
```
❯ curl -s -d '{"input": {}}' 'localhost:8181/v1/data/wasm?pretty=true'
{
  "result": {
    "common": {
      "utils": {}
    },
    "test": {
      "main": {
        "a": 18,
        "d": 18
      }
    }
  }
}
```
I believe that to be a bug in the bundle loading process, as I'd expect OPA to recognize a tar ball as a bundle in any case. But apparently the `.manifest` is only considered with the `-b` flag present (and I assume, when loaded from a remote). WDYT, @srenatus ?

**Comment by srenatus** [comment]
That's a good find. We have way too many bundle loading procedures 😅 IIRC a bundle is treated more like a directory-of-stuff when not using `-b`... 

I'm not sure what the right way forward would be. `-b` is a bit of an odd flag, it's also used to treat directories as (uncompressed) bundles...

**Comment by anderseknert** [comment]
Yeah, I can get how that's a thing when pointed at a directory, but not so much when pointed at an actual tar ball, which pretty much has to be a bundle. Why would this be any different from reading a bundle from a remote? 😑 I.e. 
```
opa run -s bundle.tar.gz
```
vs
```
opa run -s https://foo.com/bundle.tar.gz
```
I can't imagine a user thinking those would have entirely different behaviors wrt how the bundle was treated by OPA.

**Comment by srenatus** [comment]
Agreed!

**Comment by johanfylling** [comment]
What edge case is solved by not always reading the manifest file if one is present, regardless if it's inside a tarball or a directory; and if it exists, we treat the contents as a bundle?

**Comment by anderseknert** [comment]
The discussions around this in the past have largely revolved around `opa build`, which also has different behavior with or without the `-b` flag. See e.g. https://github.com/open-policy-agent/opa/issues/3480 .. IIRC we've also added some safeguards there, to warn if a `.manifest` is present in a directory which won't be accounted for in the bundle built (if `-b` is missing).

But, it's a IMHO a different thing altogether to provide OPA an _actual bundle_ and then have OPA treat is as if it was anything else. The only reason we read .tar.gz files (and not, say .zip files) in the first place is because they are _bundles_. I can't picture a single scenario where someone would have built a bundle, and then would want OPA to not read it as such. This issue, and our confusion, helps illustrate that quite clearly.

**Comment by JAForbes** [comment]
Thanks for looking into this, adding -b as a work around is good to know.  I'm wondering why the manifest would affect the evaluated result in either case though.

**Comment by anderseknert** [comment]
The `.manifest` is where the entrypoints for Wasm evaluation are stored. Without those, it'll just look like a regular Rego bundle to OPA, which is why you saw only one rule evaluated.
