### ISSUE TITLE
Add retries when download bundles via bundle service API

### ISSUE THREAD

**Issue by HarshPathakhp** [open-policy-agent/opa#5920]
## What is the underlying problem you're trying to solve?

When OPA downloads bundles via bundle service API, it may get errors such as, but not limited to - 
1. server replied with service unavailable
2. net/http: timeout awaiting response headers
3. server replied with Service Unavailable

For such eligible errors, it makes sense that OPA retries downloading the bundle again. At the same time, errors of the following types do not warrant for retries. 
1. Not Found
2. Server replied with Internal Server Error 

## Describe a "Good Enough" solution

OPA can decide whether to retry for a bundle based on classification of the error codes and messages. A global configuration parameter can be provided for the retries (optionally with a backoff config, if appropriate) for all bundle service APIs.

**Comment by srenatus** [comment]
So you're saying that HTTP status 404 and 500 should not lead to retries, but 503 (service unavailable) and 504 (gateway timeout) and the like *should retry*?

I'm not sure I see this as such a clear distinction. Especially the _internal server error_ question -- would you want to have you fleet of OPAs just stop and die because the bundles API has some sort of problem? Retrying seems like the more resilient option here -- the bundle service deployment might have been problematic, and a new iteration can be rolled out, etc. 🤔

**Comment by anderseknert** [comment]
Just to be clear, we're all aware that OPA _does_ have a retry mechanism for failed bundle downloads, right?

**Comment by charlieegan3** [comment]
😆 I had missed that part... I only looked at `Trigger`.

**Comment by ashutosh-narkar** [comment]
Closing this as OPA already supports a retry mechanism with an exponential backoff delay.
