### ISSUE TITLE
Add --schema flag to `opa test`

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#5923]
Should work identically to `opa eval`, but having to run a single command for e.g. TDD makes for less friction.

**Comment by renatosc** [comment]
I can take care of this

**Comment by renatosc** [comment]
Hi @anderseknert

I added the `--schema` flag to `opa test` and tested again my "merge error" [repo](https://github.com/renatosc/opa-merge-error) with success.

**Before the fix:**
```
opa test regos/policy2.rego tests/policy2_test.rego --schema schemas/policy2_schema.json 
Error: unknown flag: --schema
```

**After the fix:**
```
opa_darwin_amd64 test regos/policy2.rego tests/policy2_test.rego --schema schemas/policy2_schema.json 
1 error occurred: regos/policy2.rego:11: rego_type_error: undefined ref: input.dept
	input.dept
	      ^
	      have: "dept"
	      want (one of): ["department"]
```

I didn't submit the PR yet because I still need to check where to add the proper test case for that new flag.

Meanwhile, since it is my first PR, do you mind checking my [fix commit](https://github.com/renatosc/opa/commit/75f97d53ce5b4ddeac4978b12d596a7b73134efa) so I can adjust it if needed before I submit the PR?

Also, a few extra things that I noticed:

1. I still get the `merge error` if I try to run `opa test . --schema schemas` but I noticed that I also get the same `merge error` when trying to do `opa eval data.policy1.allow --data . --schema schemas`. As you pointed out, this is due to opa merging all files together. I was thinking here, maybe opa should automatically ignore the schema files/path for both `eval` and `test`? What do you think? I could work on this if you think it makes sense.

2. I noticed that the `opa test` is not reading the Metadata annotation from the rego files. Can you confirm that? If you want to open a new issue for it I can add Annotation support for `opa test` so it can read the schema info from the metadata (which is important when passing a schema directory instead of a schema file to `opa test`).

Thanks

**Comment by anderseknert** [comment]
Awesome! The commit looks fine to me, but it would be good if some tests were added just to assert this works as expected.
