### ISSUE TITLE
Misleading storage_not_found_error when delta bundle uses persistence 

### ISSUE THREAD

**Issue by jnethery** [open-policy-agent/opa#5959]
## Version Details

- Docker v4.17.0
- Image openpolicyagent/opa:latest-debug

## Description

If `persist: true` is set in the config for a delta bundle, OPA will throw the following error: 

`storage_not_found_error: <path>: document does not exist`.

This seems to be a slightly misleading or perhaps incomplete error, as it doesn't provide much information or feedback to the user.

## Steps To Reproduce
1. Add `persist: true` as a field to the bundle config for a delta bundle in `config.yaml`.
2. Run OPA, and allow it to attempt to load the bundle.
3. See the `storage_not_found_error` in the logs.

## Expected behavior
I would expect a more specific error, maybe one pointing out that not only is `persist: true` not available for delta bundles, but is also invalid.

**Comment by ashutosh-narkar** [comment]
In the [downloader](https://sourcegraph.com/github.com/open-policy-agent/opa@bafa53c5e12ff41d2683c6107dd89d7d86c170ea/-/blob/download/download.go?L117) we know if the bundle will be persisted to disk. If we can pass that to the bundle [reader](https://sourcegraph.com/github.com/open-policy-agent/opa@bafa53c5e12ff41d2683c6107dd89d7d86c170ea/-/blob/bundle/bundle.go?L387) and add a check during the [read operation ](https://sourcegraph.com/github.com/open-policy-agent/opa@bafa53c5e12ff41d2683c6107dd89d7d86c170ea/-/blob/bundle/bundle.go?L508) we should be able to generate a better error message.

**Comment by yogisinha** [comment]
Can I handle this bug. I am looking to understand OPA and contribute to it

**Comment by ashutosh-narkar** [comment]
Sure go for it @yogisinha!

**Comment by yogisinha** [comment]
Ok. thanks. it might take some time as I am new to code.

**Comment by anderseknert** [comment]
Take your time, @yogisinha! There's a #contributors channel on the OPA Slack if you'd like to get some help while you're working on this. But asking here is fine too.

**Comment by yogisinha** [comment]
I am able to replicate the error. I did the following.
1. Created a delta bundle
2. Exposed that bundle over http
3. Ran the command : opa_windows_amd64.exe run -s http://localhost:8080/bundle.tar.gz
Go the following error :

`{"addrs":[":8181"],"diagnostic-addrs":[],"level":"info","msg":"Initializing server. OPA is running on a public (0.0.0.0) network interface. Unless you intend to expose OPA outside of the host, binding to the localhost interface (--addr localhost:8181) is recommended. See https://www.openpolicyagent.org/docs/latest/security/#interface-binding","time":"2023-06-08T18:16:13-04:00"}
{"level":"info","msg":"Starting bundle loader.","name":"cli1","plugin":"bundle","time":"2023-06-08T18:16:13-04:00"}
{"level":"error","msg":"Bundle activation failed: storage_not_found_error: /c: document does not exist","name":"cli1","plugin":"bundle","time":"2023-06-08T18:16:13-04:00"}
{"level":"info","msg":"Shutting down...","time":"2023-06-08T18:16:15-04:00"}
{"level":"info","msg":"Server shutdown.","time":"2023-06-08T18:16:15-04:00"}
{"level":"info","msg":"Stopping bundle loader.","name":"cli1","plugin":"bundle","time":"2023-06-08T18:16:15-04:00"}`

**Comment by yogisinha** [comment]
I think my delta bundle is not correct. even If I hardcoded the persist to false in WithBundlePersistence method in download/download.go file, its giving same error. this is not the fix but I wanted to quickly see what happens when persist is false. 

I need some help in generating the error.
how do I generate a correct delta file? 

In my earlier attempt my patch.json looks like following. I guess its wrong. 
{
  "data": [
    {"op": "upsert", "path": "/a/b", "value": ["hello", "world"]},
    {"op": "remove", "path": "/a/c"}
  ]
}

So taking from OPA docs if I have a input.json and example.rego file, how does a example patch.json would look like ?
input.json :

`{
    "servers": [
        {"id": "app", "protocols": ["https", "ssh"], "ports": ["p1", "p2", "p3"]},
        {"id": "db", "protocols": ["mysql"], "ports": ["p3"]},
        {"id": "cache", "protocols": ["memcache"], "ports": ["p3"]},
        {"id": "ci", "protocols": ["http"], "ports": ["p1", "p2"]},
        {"id": "busybox", "protocols": ["telnet"], "ports": ["p1"]}
    ],
    "networks": [
        {"id": "net1", "public": false},
        {"id": "net2", "public": false},
        {"id": "net3", "public": true},
        {"id": "net4", "public": true}
    ],
    "ports": [
        {"id": "p1", "network": "net1"},
        {"id": "p2", "network": "net3"},
        {"id": "p3", "network": "net2"}
    ]
}`

example.rego 

`package example

default allow := false                              # unless otherwise defined, allow is false

allow := true {                                     # allow is true if...
    count(violation) == 0                           # there are zero violations.
}

violation[server.id] {                              # a server is in the violation set if...
    some server
    public_server[server]                           # it exists in the 'public_server' set and...
    server.protocols[_] == "http"                   # it contains the insecure "http" protocol.
}

violation[server.id] {                              # a server is in the violation set if...
    server := input.servers[_]                      # it exists in the input.servers collection and...
    server.protocols[_] == "telnet"                 # it contains the "telnet" protocol.
}

public_server[server] {                             # a server exists in the public_server set if...
    some i, j
    server := input.servers[_]                      # it exists in the input.servers collection and...
    server.ports[_] == input.ports[i].id            # it references a port in the input.ports collection and...
    input.ports[i].network == input.networks[j].id  # the port references a network in the input.networks collection and...
    input.networks[j].public                        # the network is public.
}`

**Comment by ashutosh-narkar** [comment]
@yogisinha try a patch document with a `upsert` operation. See [this](https://www.openpolicyagent.org/docs/latest/management-bundles/#delta-bundle-patch-operations) for more info. 

As far as implementation goes, one option is to add a check like below [here](https://sourcegraph.com/github.com/open-policy-agent/opa@5ec8e68cdcf9496bec79d60dc0bc471c1f00bd52/-/blob/plugins/bundle/plugin.go?L496) before we attempt to activate the bundle.  Alternatively we can also add a check in the bundle reader as mentioned [here](https://github.com/open-policy-agent/opa/issues/5959#issuecomment-1568863802).

```go
if u.Bundle.Type() == bundle.DeltaBundleType && p.persistBundle(name) {
        errMsg := "Persisting delta bundle to disk is not supported"
        p.log(name).Error(errMsg)
        p.status[name].SetError(fmt.Errorf(errMsg))
	if !p.stopped {
		etag := p.etags[name]
		p.downloaders[name].SetCache(etag)
	}
	return
}
```

**Comment by yogisinha** [comment]
Ok. thanks @ashutosh-narkar  I will try upsert. So there is no issue in steps what I explained [before](https://github.com/open-policy-agent/opa/issues/5959#issuecomment-1583841060) ?

Yes, I was thinking to put the code in bundle reader as there is already some checks for delta bundle there in Read() method. I can add the check there.

**Comment by yogisinha** [comment]
@ashutosh-narkar  thanks for your help. I appreciate it.

I am passing persist=true in command line through --set options as explained in OPA doc and it says that 
opa run -s http://someserver/bundle.tar.gz  sets the persist = true by default.

Here is my finding about delta bundle.
I tried **upsert** and it always succeeds whether persist is true or false.
**replace** and **remove** always fails with "storage not found error" whether persist is true or false.
So I see no behavior difference when its true or false. 

do you see any difference in  behavior when you use different values for persist  property for delta bundle?

I put your code where you suggested (before call to **activate()** inside **process** method) and ran the code with persist=**false** and loading of delta bundle still failed. The error is coming in downstream calls which starts in from acitvate() method

**Comment by yogisinha** [comment]
Hi @ashutosh-narkar , I found my issue.  data.json file inside the snapshot bundle I created was empty. So OPA was starting with no data, so it makes sense to throw the error in all the case which I was getting before. I was using the file name **input.json** when I was creating the snapshot bundle. I had to use file name as **data.json**.

But now with **persist=true**, I can successfully load the delta bundle. there is no issue.
If the path given in your delta bundle is not found in OPA memory then it throws that error and I think that is right behavior because it could not find the path to make the update. I don't think its related to **persist** property. 

For example , I did this 3 steps.
1. Loaded a valid snapshot bundle  -- produced the successful msg
2. loaded a delta bundle for **replace** operation where I put the invalid path -- produced the error because I passed the invalid path
3. loaded a delta bundle for same **replace** operation where I put the valid path  -- produced the successful msg
You can see the output:

{"level":"info","msg":"**Bundle loaded and activated successfully.**","name":"cli1","plugin":"bundle","time":"2023-06-10T09:44:14-04:00"}
{"level":"error","msg":"**Bundle activation failed: storage_not_found_error: /test: document does not exist**","name":"cli1","plugin":"bundle","time":"2023-06-10T09:45:57-04:00"}
{"level":"info","msg":"**Bundle loaded and activated successfully**.","name":"cli1","plugin":"bundle","time":"2023-06-10T09:47:03-04:00"}

I tried with both true and false values for persist property and is able to load the delta bundle.

May be we can change the error msg a little bit more clear like :   path_not_found_error: "path in delta bundle" does not exist in snapshot bundle
Your thoughts ?

**Comment by yogisinha** [comment]
HI @ashutosh-narkar @anderseknert  Can you look at my findings and let me know if its still a bug or we just need more clear error msg?

**Comment by jnethery** [comment]
Hey @yogisinha 

> But now with persist=true, I can successfully load the delta bundle. there is no issue.

The problem is that the `path_not_found_error` is thrown when persist is set to true in the config. I'm not sure how it's working according to your quote here

**Comment by jnethery** [comment]
@yogisinha If my path was invalid, then the error message would _technically_ be correct, just for the wrong reason :)

It does depend on the persist value, because the issue is that delta bundles do not persist, so the setting is invalid. The error should say something to this effect, rather than saying the path is unfound, which is not true.

**Comment by yogisinha** [comment]
@jnethery  So basically we don't want to even load the delta bundle and try to update it if the persist value is true ? So basically its a validation logic we are trying to put, right ?

**Comment by jnethery** [comment]
@yogisinha It already does not load; the solution here is simply to make the error message more clear.

I suggest following the advice of @ashutosh-narkar 

https://github.com/open-policy-agent/opa/issues/5959#issuecomment-1584998884

**Comment by yogisinha** [comment]
@jnethery  So finally we are doing this

1. if we are loading delta bundle and persist is true, we should throw clearer error msg like " **"persist"** property is passed true in config. Persisting delta bundle to disk is not supported"
2.  If we are loading delta bundle and persist is false and path is valid / invalid  - No change in behavior.

**Comment by yogisinha** [comment]
@ashutosh-narkar  @anderseknert  I have created the PR for this issue. Please review and let me know any feedback.
https://github.com/open-policy-agent/opa/pull/6006
