### ISSUE TITLE
opa run plan.json gives me the error  load error: 1 error occurred during loading: plan.json: invalid character 'ÿ' looking for beginning of value

### ISSUE THREAD

**Issue by Blueposey** [open-policy-agent/opa#6096]
<!-opa run plan.json gives me the error  load error: 1 error occurred during loading: plan.json: invalid character 'ÿ' looking for beginning of value -->

<!- steps to reproduce -->
<!--
I saved plan by doing terraform plan -out="plan.tfplan"
then I converted it to json by doing 
terraform show -json "plan.tfplan" > "plan.json"

When I do opa run plan.json I get this error  load error: 1 error occurred during loading: plan.json: invalid character 'ÿ' looking for beginning of value

I've tried a few different names for my plan and also creating a completely different terraform plan for another project. It won't let me add my json so here is a picture and also a zip of json 

[plan.zip](https://github.com/open-policy-agent/opa/files/12053469/plan.zip)

**Comment by ashutosh-narkar** [comment]
@Blueposey it would be helpful if you could provide steps to repro the issue. Also please ensure the contents of `plan.json` file that you're loading into OPA. You can post that file as well if that is relevant. Generally, it helps to debug an issue if you provide a short description of the issue, repro steps and expected behavior. Closing this one. Feel free to re-open or create a new issue with the relevant details. Thanks!
