### ISSUE TITLE
Assignment fails in REPL

### ISSUE THREAD

**Issue by timothyhinrichs** [open-policy-agent/opa#615]
```
> r2 := 7
> r2
1 error occurred: 1:1: rego_unsafe_var_error: var r2 is unsafe
> r2 = 7
> r2
7
```

**Comment by tsandall** [comment]
The REPL is compiling the query before checking if it can construct a rule. As a result, the REPL ends up with a rule like `__local0__ = 7` defined instead of `r2 = 7`.

I think the behaviour we want is as follows:

- the first time `=` is used, a rule is declared
- if a rule has been declared, `=` acts as a comparison (which is the current behaviour)
- each time `:=` is used, the rule is redeclared

For example:

```
> r2 = 7
> r2
7
> r2 = 7
true
> r2 := 8
> r2
8
> r2 := 9
> r2
9
> r2 = 9
true
```

WDYT?

**Comment by timothyhinrichs** [comment]
Sounds good to me.
