### ISSUE TITLE
Data API should return HTTP 400-499 code on policy evaluation failure

### ISSUE THREAD

**Issue by stevepatter** [open-policy-agent/opa#6243]
## What is the underlying problem you're trying to solve?

I'm performing some automated testing with OPA's REST API, using custom policies & json data, for automated testing. If I upload a policy file with multiple tests, then separately call the /data API with test data that is expected to fail the policy, the REST response does include "false" against the failing test, but it is still returned with an HTTP 200 header. 

To help with automated testing against OPA, it would be very useful if /data could return an HTTP 4xx response header, so it is easier for data upload scripts to detect test failure. 

## Describe the ideal solution

At present, posts to /data always return an HTTP 200 status code & a json response body. If any of the tests evaluate to false, return the same json body, but with an HTTP 400 status code instead (or another 4xx series code if that's more appropriate)

**Comment by anderseknert** [comment]
Hi @stevepatter 👋 

OPA does not assign any special meaning to names or values, so that a rule returns `false` or is undefined is just as normal as a rule returning `true` or some other value. Clients however, _would_ know the meaning of something like "allow", and `false`/`true` in that context, and can work with that to enforce decisions after having parsed the response.

**Comment by stevepatter** [comment]
Thanks, I've written a python script that'll parse down the output to find falses. I was thinking of regular TDD (which is probably a  layer on top of the language) where a fail because of invalid input is considered ok if it was handled right.

Thanks for having a look.
