### ISSUE TITLE
Change to built-in definitions for next release showing up in docs for the current one

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#6269]
In #6267 I added documentation to the `walk` built-in and an optimization technique that I introduced with that PR. The commit is targeting OPA v0.58.0, which is the next release, but it's already showing up in the docs for v0.57.0 which is the current one.

Something seems wrong about that, and hopefully it's isolated to the built-in definitions.

<img width="1101" alt="Screenshot 2023-10-03 at 13 33 04" src="https://github.com/open-policy-agent/opa/assets/510711/f808e12e-b963-4ad2-a620-430d4e2e8f07">

**Comment by charlieegan3** [comment]
I've had a quick looking into this. I think the issue is that these tables are based on JSON data that's not versioned.

https://github.com/open-policy-agent/opa/pull/6171/files#diff-0b5ca119d2be595aa307d34512d9679e49186307ef94201e4b3dfa079aa89938R51

I think that this impacts all versions of the docs that use:

```
{{< builtin-table cat=graph title=Graphs >}} etc etc
```

In the content.

I think the that way to address this is perhaps to merge in the `builtin_metadata.json` from each version we checkout when building the site.

**Comment by charlieegan3** [comment]
https://github.com/open-policy-agent/opa/pull/6274

**Comment by charlieegan3** [comment]
I no longer see the new message on the latest release.
<img width="982" alt="Screenshot 2023-10-05 at 09 51 23" src="https://github.com/open-policy-agent/opa/assets/1774239/46d04764-4935-4d1e-98e9-c2ef038a3c81">

I only see it on edge.
<img width="971" alt="Screenshot 2023-10-05 at 09 51 12" src="https://github.com/open-policy-agent/opa/assets/1774239/d8fa7360-0553-4990-b839-43f912f8982f">

So counting this as fixed.
