### ISSUE TITLE
Regression in version `0.56.0` with error `rego_type_error: conflicting rules`

### ISSUE THREAD

**Issue by nitrocode** [open-policy-agent/opa#6301]
## Short description 

This seemed to work fine in 0.55.0 and below for opa and conftest 0.44.1 and below. Perhaps something has been deprecated? Unsure how to resolve this in my code. It only seems to be affecting this one policy.

* OPA version: 0.56.0 throws an error of `conflicting rules` and 0.55.0 does not
* Example query, input, data, and policy that OPA was given

### dynamodb_deletion_protection.rego

```rego
package dynamodb_deletion_protection

import future.keywords

# edit: this is the faultly line pointed out below
default dynamodb_allow := false

dynamodb_allow[key] if {
    some i
    input.resource.aws_dynamodb_table[key][i].deletion_protection_enabled == true
}

warn contains sprintf(message, [key]) if {
    input.resource.aws_dynamodb_table[key]
    not dynamodb_allow[key]
    message := "aws_dynamodb_table (%s) must have deletion_protection_enabled set to true"
}
```

### dynamodb_deletion_protection_test.rego

```rego
package dynamodb_deletion_protection

import future.keywords

test_warn_without_deletion_protection if {
	count(warn) > 0 with input as {"resource": {"aws_dynamodb_table": {"test": [{}]}}}
}

test_warn_with_mixture_of_deletion_protections_explicit if {
	count(warn) > 0 with input as {"resource": {
		"aws_dynamodb_table": {
			"test1": [{"deletion_protection_enabled": false}],
			"test2": [{"deletion_protection_enabled": true}]
		}
	}}
}

test_warn_with_mixture_of_deletion_protections_implicit if {
	count(warn) > 0 with input as {"resource": {
		"aws_dynamodb_table": {
			"test1": [{}],
			"test2": [{"deletion_protection_enabled": true}]
		}
	}}
}

test_not_warn_with_deletion_protection if {
	count(warn) == 0 with input as {"resource": {"aws_dynamodb_table": {"test": [{"deletion_protection_enabled": true}]}}}
}

test_not_warn_without_dynamodb_tables if {
	count(warn) == 0 with input as {"resource": {}}
}
```

* Example output that OPA returned

> 1 error occurred: dynamodb_deletion_protection.rego:5: rego_type_error: conflicting rules data.dynamodb_deletion_protection.dynamodb_allow[key] found

### opa

```bash
✗ asdf plugin add opa
✗ asdf install opa 0.55.0
✗ asdf install opa 0.56.0
✗ asdf install opa 0.57.0
```

```bash
✗ asdf local opa 0.55.0 && opa version && opa test * -v
Version: 0.55.0
Build Commit: 4c21dddf2254632e8b28b60b73863f22bd3ae389
Build Timestamp: 2023-07-27T17:42:51Z
Build Hostname: Mac-1690480339847.local
Go Version: go1.20.6
Platform: darwin/arm64
WebAssembly: unavailable
dynamodb_deletion_protection_test.rego:
data.dynamodb_deletion_protection.test_warn_without_deletion_protection: PASS (195.834µs)
data.dynamodb_deletion_protection.test_warn_with_mixture_of_deletion_protections_explicit: PASS (194.25µs)
data.dynamodb_deletion_protection.test_warn_with_mixture_of_deletion_protections_implicit: PASS (118.75µs)
data.dynamodb_deletion_protection.test_not_warn_with_deletion_protection: PASS (97.125µs)
data.dynamodb_deletion_protection.test_not_warn_without_dynamodb_tables: PASS (67.916µs)
--------------------------------------------------------------------------------
PASS: 5/5
```

```bash
✗ asdf local opa 0.56.0 && opa version && opa test * -v
Version: 0.56.0
Build Commit: 016cb07ac95cdf11c67c4cfc730e032d086cdb9c
Build Timestamp: 2023-08-31T14:16:16Z
Build Hostname: Mac-1693491906065.local
Go Version: go1.21.0
Platform: darwin/arm64
WebAssembly: unavailable
1 error occurred: dynamodb_deletion_protection.rego:5: rego_type_error: conflicting rules data.dynamodb_deletion_protection.dynamodb_allow[key] found
```

```bash
✗ asdf local opa 0.57.0 && opa version && opa test * -v
Version: 0.57.0
Build Commit: c2f42aa94ab47cfc0101e79f53672e64cb77a6e8
Build Timestamp: 2023-09-28T12:31:12Z
Build Hostname: Mac-1695904815154.local
Go Version: go1.21.1
Platform: darwin/arm64
WebAssembly: unavailable
1 error occurred: dynamodb_deletion_protection.rego:5: rego_type_error: conflicting rules data.dynamodb_deletion_protection.dynamodb_allow[key] found
```

### conftest

```bash
✗ asdf plugin add conftest
✗ asdf install conftest 0.44.1
✗ asdf install conftest 0.45.0
```

```bash
✗ asdf local conftest 0.44.1 && conftest --version && conftest verify --policy .
Conftest: 0.44.1
OPA: 0.54.0

5 tests, 5 passed, 0 warnings, 0 failures, 0 exceptions, 0 skipped
```

```bash
✗ asdf local conftest 0.45.0 && conftest --version && conftest verify --policy .
Conftest: 0.45.0
OPA: 0.56.0
Error: running verification: load: loading policies: get compiler: 1 error occurred: dynamodb_deletion_protection.rego:5: rego_type_error: conflicting rules data.dynamodb_deletion_protection.dynamodb_allow[key] found
```

## Expected behavior

```
PASS: 5/5
```

## Additional context

- https://github.com/open-policy-agent/opa/releases/tag/v0.56.0
- https://github.com/open-policy-agent/opa/compare/v0.55.0...v0.56.0

**Comment by nitrocode** [comment]
cc: @johanfylling in case one of the recent partial PRs could have impacted? Please look if you get a chance.

For now, I plan to pin our version cause I cannot seem to figure out the root cause of the error.

**Comment by anderseknert** [comment]
Thanks @nitrocode for you detailed report! That's indeed a change in behavior between versions, and some bisecting to find out what caused this would be good. I'm surprised this worked in past versions though 😅 

The conflict here is that your default boolean assignment:
```rego
default dynamodb_allow := false
```
Won't ever be assigned, as `dynamodb_allow` is also defined as a set-generating rule:
```rego
dynamodb_allow[key]
```
Even when empty, that'll never be undefined, which it would need to be for the default condition to trigger. Your tests never excercise that path either, and if they did, there would not be much of a path to test. 

I guess it could be argued that since the default condition never triggers, it's not really a _conflict_, but "only" dead code. Anyway, removing that will solve the issue reported in your tests.

**Comment by johanfylling** [comment]
I think it's a valid suspicion that this was introduced in the changes that went into general-ref head support, and associated changes to partial eval.
However, as @anderseknert suggests, it was never a valid construct to declare the same rule as both a single-value boolean rule simultaneously as a multi-value partial set rule. The change in behavior is that OPA now recognizes this as an error at compile-time, rather than allowing you to write code (`default dynamodb_allow := false`) that will never be executed at eval-time. 
Essentially, this was a drive-by bug fix, and should have been recognized as such and properly reported in the release.

This change is unlikely to get reverted, so my recommendation is, instead of pinning an older OPA version, to instead remove the conflicting `default` declaration on line `5` in `dynamodb_deletion_protection.rego`, i.e:

```rego
default dynamodb_allow := false
```

**Comment by nitrocode** [comment]
Oh wow that was a lot easier of a fix than I thought. Thank you very much to the both of you for weighing in so quickly and swiftly.
