### ISSUE TITLE
OPA test - fails to identify the keyword present in policy name and still passes all the tests without failing

### ISSUE THREAD

**Issue by Megha-96** [open-policy-agent/opa#6768]
## Short description 
Example policy

`package irn.intuit.peoplemgmt.promopackage

default authorize = {
	"decision": "deny",
	"cause": [{"category": "ACCESS_DENIED", "detail": "User not allowed to access this resource"}],
}

authorize = deny[output] {
	deny
}

authorize = permit[output] {
	permit
}

deny[output] {
	not permit
	output := "deny "
}

permit[output] {
	output := "permit"
}`

**Comment by srenatus** [comment]
Please provide an example policy.

**Comment by Megha-96** [comment]
I have updated the description. The policy name has promoPackage but if you write any tests it will still pass.

**Comment by srenatus** [comment]
I'm confused is _that_ your exact policy? Because that package name works fine -- I just tried in the playground.

How do you experience
>  the bundles do now allow such path at all

exactly?

**Comment by srenatus** [comment]
BTW I think it's instructive to run your policy on the playground: [see here](https://play.openpolicyagent.org/p/uYh8avxRdj).

In the lower right, you'll notice some Regal findings, and one of them stands out to me: "impossible not".

>  bugs/impossible-not: Impossible `not` condition ([Learn more](http://docs.styra.com/regal/rules/bugs/impossible-not))

That line, 

```rego
deny[output] {
    not permit # <------
    output := "deny "
}
```
**cannot fail** because it's a multi-value rule (or "partial set rule"). Even if its body never succeeds, the result with be an empty set, and `not ...` of that is _false_.

As a remedy, you could write `count(permit) == 0` or `permit == set()`. [See here for more details.](https://docs.styra.com/regal/rules/bugs/impossible-not)

**Comment by anderseknert** [comment]
Adding to what @srenatus said, there are more impossible conditions, or expressions that are essentially constant in your policy:

```rego
authorize = deny[output] {
    deny
}

authorize = permit[output] {
    permit
}
```
As both `deny` and `permit` are multi-value rules, they will always evaluate to _something_ (minimum, an empty set), so they'll always evaluate "truthy".

Perhaps if you describe what you're trying to accomplish, we can try and help write a policy for that purpose 🙂

**Comment by Megha-96** [comment]
Thank your helping. I think we got the issue. This is not a bug, a miss from our end.
