### ISSUE TITLE
Reuse service from configuration in http.send

### ISSUE THREAD

**Issue by rob-valor** [open-policy-agent/opa#6916]
### Problem
When making `http.send` requests, we can't (re)use a service from the [services](https://www.openpolicyagent.org/docs/latest/configuration/#services) configuration.

### Solution and advantage
Being able to define a _service_  as part of a `http.send` would allow us to reuse the url to the service, setting headers and timeout and most important reuse [OAuth2 Client Credentials](https://www.openpolicyagent.org/docs/latest/configuration/#oauth2-client-credentials) functionality.

It would be really useful to have something like `http.send({"service":"acmecorp",...})` which makes the code much less verbose and potentially avoid duplicate logic and configuration.

**Comment by anderseknert** [comment]
Hi there! 

Similar ideas have been brought up in the past (sometimes by me, even!) and I agree that it would simplify some scenarios. The core of the problem is that you'd now have a policy that has a hard dependency on OPA being run as a server. In other words, that policy wouldn't be `opa eval`able, `opa bench`able, etc... really any other command than `opa run --server`. For that reason, I think the duplication of some config is a necessary evil.

**Comment by rob-valor** [comment]
Ah, that's indeed a clear reason why it's not supported. Then we'll use the [token retrieval example](https://www.openpolicyagent.org/docs/latest/oauth-oidc/#token-retrieval) as a base for our solution. 

Thanks.

**Comment by anderseknert** [comment]
Sounds good! And let me know if you have any questions around that.
