### ISSUE TITLE
opa build should provide an option to preserve print statements

### ISSUE THREAD

**Issue by me-viper** [open-policy-agent/opa#7194]
## What is the underlying problem you're trying to solve?

`opa build` has no option to preserve `print` statements. As result when target is `wasm` print statements are always erased.

## Describe the ideal solution

Provide a flag for `opa build` to preserve build statements

## Describe a "Good Enough" solution

N/A

## Additional Context

N/A

**Comment by anderseknert** [comment]
Providind a flag to preserve print statements implies that print statements are normally erased by the `opa build` command, which they are not. I think the better solution is to just keep them unconditionally. If the target environment isn't fond of them, they can always provide the built-in function as a no-op.

But perhaps there are some reasons for doing it this way I'm not aware of. @srenatus?

**Comment by me-viper** [comment]
Ether approach works for me as long as prints stay in wasm. Should I create new PR with no flag and just `WithEnablePrintStatements(true)`?

**Comment by anderseknert** [comment]
Changing the logic of the open PR is IMHO preferable over creating a new, but either way would be fine. Let's see what @srenatus says first though. Either way, you'll have some way to have `print` calls in wasm, I'm sure :)

**Comment by srenatus** [comment]
So, couple of thoughts, or rather, what I'd like to answer to figure out what a good approach is:

1. Has anything in `opa build -t wasm` changed: were print statements preserved before a certain point in time?
2. Do the various Wasm SDKs for OPA support print already? We cannot change a default that makes all the other projects fail to run OPA's Wasm modules because they bail out when they see a builtin that they don't support. By its nature, `print()` is SDK-dependent.

**Comment by anderseknert** [comment]
1. Probably not, and that seems like an oversight.
2. How is that any different from OPA adding a new SDK-dependent built-in? Even [strings.count](https://www.openpolicyagent.org/docs/latest/policy-reference/#builtin-strings-stringscount), added 3 releases back is marked as SDK-dependent.

**Comment by srenatus** [comment]
> How is that any different from OPA adding a new SDK-dependent built-in? Even [strings.count](https://www.openpolicyagent.org/docs/latest/policy-reference/#builtin-strings-stringscount), added 3 releases back is marked as SDK-dependent.

It's different because it'll break **existing** stuff: Before, your policy using print() was compiled to wasm and ran fine with your SDK, after, it'll throw a runtime exception because this "new" builtin isn't in the SDK.

**Comment by anderseknert** [comment]
So

**Comment by anderseknert** [comment]
Sorry, fat fingers on mobile 😄

So our main concern is that we have users compiling their policies to wasm full of print statements that they expect to do nothing?

**Comment by srenatus** [comment]
Before, you could rely on print() statements getting dropped.
After, your policy Wasm fails at runtime.

This is a pretty bad user experience if you ask me. If you want to do it the boring way, you'd bump the OPA Wasm major number, so compatibility checks will catch the problem early, when instantiating the Wasm module. You'd say that every SDK that supports version 2.1 (or wherever we're at right now) _must_ provide `print()`.

Alternatively, you can claim the number of Wasm users who may have `print()` in their policies is so low that annoying them is a minor problem.

Spot-checked a few SDKs for support for `print()`, and there's no positive match -- presumably because nobody has been expecting `print()` to work in wasm modules before:
- https://github.com/open-policy-agent/npm-opa-wasm/blob/main/src/builtins/index.js
- https://github.com/StyraInc/opa-java-wasm/tree/main/core/src/main/java/com/github/andreaTP/opa/chicory/builtins
- https://github.com/matrix-org/rust-opa-wasm/blob/main/src/builtins/mod.rs

**Comment by srenatus** [comment]
OK what I'm trying to say is: Sure, go ahead, but let's ensure that that **at least** the SDKs we control support `print()` first.

With `print()` statements preserved in Wasm, but without SDK support for it, the user experience becomes twofold:
1. You don't use `print()` and everything is as it was before.
2. You use `print()` and everything is broken.

So, let's fix (2.) _to at least a basic extent_ before going this route, what do you think?

**Comment by anderseknert** [comment]
Sounds good to me!

**Comment by srenatus** [comment]
So. I've changed my mind, complete U-turn, and this is why:

> I think the better solution is to just keep them unconditionally. If the target environment isn't fond of them, they can always provide the built-in function as a no-op.

If we unconditionally include `print()` statements, we'll have the Wasm code (from the policy) and the Wasm SDKs *do quite a bit of work* for each `print()`[^1], even if the SDK user decides to provide their own `print()` implementation that ignores the calls. So, for these folks, it would be preferable to not include `print()` at all.

I think another flag might be best. If the ordinary build code flow doesn't remove the `print()` statements, the flag might be better called `--wasm-include-print` or something similar. What do you think?

That way, we can also make the change now, since the user is given a choice -- if their SDK has no idea about print(), they can just not opt-in.

-----
[^1]: the IR and Wasm code will contain the expressions to build the comprehension that is used as `internal.print()`'s argument, and it'll have to do a cross-VM call, including the serialization of the arguments to JSON.

**Comment by anderseknert** [comment]
Alright then. Sounds like you should just rename the flag then @me-viper

**Comment by me-viper** [comment]
Done
