### ISSUE TITLE
Fix bundle state request

### ISSUE THREAD

**Issue by koponkin** [open-policy-agent/opa#794]
Status request contains errors when all is OK!

Steps to reproduce:
1. Run `bundle` server
2. Run `opa` service
3. Stop `bundle` server
4. OPA service still running and send POST requests with `connection refused` error - expected result
5. Run `bundle` server (without any changes in policy/data)

OPA send request to `bundle` server, get response `NOT_MODIFIED`, but status request does not change and OPA continue send requests with `connection refused` error.

please fix it ASAP

**Comment by bkhablenko** [comment]
I second this.

Basically, what @koponkin is saying is that once OPA fails to download a bundle due to a connectivity issue, it will keep reporting its status with an error code until it successfully downloads & activates a bundle – and this won't happen unless there are either policy or data updates on the server (see [this statement](https://github.com/open-policy-agent/opa/blob/master/plugins/bundle/plugin.go#L223-L225) for reference).

The described behavior makes sense only if OPA continues to experience connectivity issues, but once it receives any response from the bundle server, `304 Not Modified` included, I believe it should stop reporting an error.
