### ISSUE TITLE
gRPC API

### ISSUE THREAD

**Issue by gam-phon** [open-policy-agent/opa#841]
What do you think of offering a grpc server with the http server? so no need to develop a specific client for each language. like [open-policy-agent/client-python](https://github.com/open-policy-agent/client-python)  the clients will be generated

**Comment by tsandall** [comment]
Adding a gRPC server to OPA to complement the HTTP server makes sense. If protobufs are used to serialize the messages, I would want to understand how we can support arbitrary input data in the policy evaluation requests. If that's not possible then we would need to look at alternatives, e.g., some kind of custom encoding (though that would require per-language libraries) or embedding JSON inside the message (maybe not the worst option).

The other thing to think about is avoiding duplication between the HTTP server and the gRPC server. I think we would want to refactor logic in the HTTP server first so that it could be shared across both.

If this is an area you are interested in contributing to, I'd be happy to help you get started. The first thing to answer (in my mind) would be the serialization question and then the second thing would be to figure out how to refactor the server to avoid duplication. Once those were taken care of, I think the gRPC server implementation would be relatively straightforward.

**Comment by gam-phon** [comment]
@tsandall [Envoy API is switching from v1 REST API to v2 gRPC API](https://blog.envoyproxy.io/evolving-a-protocol-buffer-canonical-api-e1b2c2ca0dec). We can learn from their experience and the reasons of switch without backward compatibility.

I would like to help in this, but to be honest. I am working with OPA in a personal side project that is more of an experimental than production product. So maybe someone who is more experience than me can help ^_^.

**Comment by repenno** [comment]
GRPC supports arbitrary data through "strings" as opaque fields.  But, I wonder what is the requirement behind implementing GRPC since this would be a very large endeavor. Not only defining protobufs, GRPC infra, but we would need to write all tests, hook up to current infrastructure, etc.

Generated code and documented schema is good but this would be a rounding error as far the amount of work is concerned. Is there a performance problem today with REST? Other pressing issue or good use-case?

**Comment by tsandall** [comment]
I'm hesitant to suggest that we work on this right now. The benefit of adding a gRPC API at this time is limited in my opinion. It would need to provide a measurable performance improvement to warrant the work. IMO the major benefit to this work would be a slightly cleaner server implementation (which could be embedded/reused in other projects.)

**Comment by tsandall** [comment]
I am going to close this for the time being as it doesn't seem like a blocker for OPA adoption at this point. It's also worth noting that we have added support for plugins--so if someone wanted to write a gRPC server for OPA they could configure OPA to load the server dynamically on startup. We still need docs for that feature but the changes were in #883.

**Comment by kindermoumoute** [comment]
I kinda feel there is still a need for a native support of gRPC as its adoption is growing among many organizations. Plus it's a CNCF incubating project.

> I would want to understand how we can support arbitrary input data in the policy evaluation requests.

What about a flag `--protoschema` similar to what is done with the jsonschema validation?

In the future we could also imagine some smoother integration by using proto schema from a [protobuf schema registry](https://docs.buf.build/roadmap/#the-buf-schema-registry).
